"""ÖSYM yayımlanmış fizik sorularının yapısal analizi (STEP 10).

Kaynak: osym.gov.tr "Temel Soru Kitapçıkları ve Cevap Anahtarları" duyurularındaki resmî PDF'ler
(dokuman.osym.gov.tr). Sorular PDF'den görsel olarak okunmuş; soru metni KOPYALANMAMIŞTIR, yalnız yapısal özet.
question_no = AYT Fen Bilimleri testinin Fizik bölümündeki sıra (1-14); TYT için Fizik bölümü sırası (1-7).
"""

_D = "https://dokuman.osym.gov.tr/pdfdokuman"
URLS = {
    ("AYT", 2018): f"{_D}/2018/YKS/AYT_01072018.pdf",
    ("TYT", 2018): f"{_D}/2018/YKS/TYT_01072018.pdf",
    ("AYT", 2019): f"{_D}/2019/YKS/TSK/ayt_yks_2019_web.pdf",
    ("TYT", 2019): f"{_D}/2019/YKS/TSK/tyt_yks_2019_web.pdf",
    ("AYT", 2020): f"{_D}/2020/YKS/TSK/ayt_yks_2020.pdf",
    ("TYT", 2020): f"{_D}/2020/YKS/TSK/tyt_yks_2020.pdf",
    ("AYT", 2021): f"{_D}/2021/YKS/TSK/ayt_yks_2021.pdf",
    ("TYT", 2021): f"{_D}/2021/YKS/TSK/tyt_yks_2021.pdf",
    ("AYT", 2022): f"{_D}/2022/YKS/TSK/yks_2022_ayt.pdf",
    ("TYT", 2022): f"{_D}/2022/YKS/TSK/yks_2022_tyt.pdf",
    ("AYT", 2023): f"{_D}/2023/YKS/TSK/yks_ayt_2023_kitapcik_g5A2H.pdf",
    ("TYT", 2023): f"{_D}/2023/YKS/TSK/yks_tyt_2023_kitapcik_T23ky.pdf",
    ("AYT", 2024): f"{_D}/2024/YKS/TSK/yks_ayt_2024_kitapcik_ts85k.pdf",
    ("TYT", 2024): f"{_D}/2024/YKS/TSK/yks_tyt_2024_kitapcik_T24kt.pdf",
    ("AYT", 2025): f"{_D}/2025/YKS/TSK/yks_ayt_2025_kitapcik_st12.pdf",
    ("TYT", 2025): f"{_D}/2025/YKS/TSK/yks_tyt_2025_kitapcik_d250.pdf",
}

ANNOUNCEMENTS = [
    {"id": "ann-osym-2028-not-found", "title": "ÖSYM'nin 2028 YKS / Maarif Modeli için resmî açıklaması: osym.gov.tr'de bulunamadı",
     "organization": "ÖSYM (osym.gov.tr)", "url": "https://www.osym.gov.tr/SinavGrubu/Index/2", "date": "2026-10-02",
     "summary": "YKS duyuru listesi ve 2026-YKS Kılavuzu PDF'i tarandı; 2028 sınavı, Maarif Modeli veya beceri temelli soru modeline dair ÖSYM kaynaklı resmî açıklama bulunamadı. Blog iddiaları duyuru olarak kaydedilmedi.",
     "relevance": "2028 YKS biçimi hakkında ÖSYM tarafından yayımlanmış bağlayıcı bir belge yok; analiz 2018-2025 gerçek sorularına ve 11. sınıf program sınırlarına dayanır.",
     "verified_read": True},
    {"id": "ann-meb-2025-12-yks-lgs-2028", "title": "YKS ve LGS'de yeni müfredata uyumlu soru modeli 2028'de hayata geçecek",
     "organization": "MEB (ÖSYM ile iş birliği)", "url": "https://www.meb.gov.tr/yks-ve-lgsde-yeni-mufredata-uyumlu-soru-modeli-2028de-hayata-gececek/haber/39265/tr",
     "date": "2025-12-15",
     "summary": "MEB Bakan Yardımcısı: yeni müfredata uyumlu, beceri ve bağlam temelli soru modeli 2028'de YKS ve LGS'de kullanılacak; soru modelleme ÖSYM ile sürüyor; çoktan seçmeli biçim korunacak; örnek sorular MEB platformlarından paylaşılacak.",
     "relevance": "Soru biçiminin bilgi hatırlamadan bağlam içinde bilgi kullanımına kayacağını resmî düzeyde bildirir; sınav sistemi (TYT-AYT) değişikliği değil.",
     "verified_read": True},
    {"id": "ann-meb-2024-11-osym-ziyaret", "title": "Bakan Tekin, ÖSYM Başkanı Ersoy'u kabul etti",
     "organization": "MEB", "url": "https://meb.gov.tr/bakan-tekin-osym-baskani-ersoyu-kabul-etti/haber/35320/tr", "date": "2024-11-04",
     "summary": "9. sınıfta Maarif Modeli ile başlayan öğrencilerin YKS'ye 2028'de gireceği, 10-12. sınıfların eski müfredatla sınava gireceği; TYT ve AYT için MEB-ÖSYM uzman çalıştayları yapıldığı belirtildi.",
     "relevance": "2028 YKS'nin Maarif müfredatına uyumlu olacağını ve geçiş takvimini doğrular.",
     "verified_read": True},
]

ITEMS = []


def Q(year, exam, no, topic, los, out, fam, fm, skills, c, i, m, flags, distractor, strategy, summary, fit, fit_reason, conf, rm="official_pdf"):
    """Kompakt kayıt üretici. flags: boşlukla ayrılmış {ms gr tb ex dl} (multi_step, graph, table, experimental, daily_life)."""
    f = set(flags.split())
    assert f <= {"ms", "gr", "tb", "ex", "dl"}, flags
    return {"year": year, "exam": exam, "question_no": no, "source_url": URLS[(exam, year)], "read_method": rm, "topic": topic,
            "learning_outcomes": los, "out_of_11_scope": out, "question_family": fam, "family_match": fm, "skills": skills,
            "conceptual_load": c, "interpretation_load": i, "mathematical_load": m, "multi_step": "ms" in f, "graph_based": "gr" in f,
            "table_based": "tb" in f, "experimental_context": "ex" in f, "daily_life_context": "dl" in f, "distractor_structure": distractor,
            "solution_strategy": strategy, "summary": summary, "fit_2028": fit, "fit_reason": fit_reason, "confidence": conf}


# Ortak çeldirici yapısı etiketleri
ROMAN = "I-II-III öncülleri; şıklar öncül kombinasyonları (Yalnız I … I, II ve III)"
NUM = "sayısal şıklar (A–E artan değerler)"


# ============================ 2018 AYT (14/14 okundu) ============================
ITEMS += [
    Q(2018, "AYT", 1, "Makara düzeneğinde bağlı cisimlerin ivmesi (Newton II)", ["FİZ.11.1.5"], "", "connected-bodies-same-acceleration", "exact", ["KB2.14"],
      2, 2, 2, "ms", NUM, "Her sistemde net kuvvet / toplam kütle; birinden kütle bulunup diğerinin ivmesine geçilir",
      "Biri doğrudan çekilen, biri asılı ağırlıklarla çekilen iki özdeş sandıktan birinin ivmesi verilip diğerinin ivmesi isteniyor.",
      "yes", "Aynı ivmeyle hareket eden bağlı cisimler programda var; tek sistemde farklı ivmeli cisim yok.", "HIGH"),
    Q(2018, "AYT", 2, "Çembersel yörüngeden kopan taşın hız-ivme vektörleri", ["FİZ.11.1.9", "FİZ.11.1.3"], "", "string-cut-trajectory", "exact", ["KB2.16.3"],
      2, 2, 0, "ms dl", "nokta kümeleri (Yalnız II, I ve IV, …)", "Kopma anındaki hız teğettir; sonra ivme düşey g olduğundan hız düşey olan noktalar seçilir",
      "Düşey çemberde döndürülen taş serbest kalınca hız ve ivmenin birbirine paralel olduğu kopma noktaları isteniyor.",
      "yes", "Çembersel hareketin hız vektörü ve iki boyutlu hareketin ivmesi (yalnız g) doğrudan kapsamda.", "HIGH"),
    Q(2018, "AYT", 3, "Buz pateni: karşılıklı itme, momentum ve itme", [], "12. sınıf FİZ.12.1.3", None, "none", [],
      2, 1, 0, "dl", ROMAN, "Momentum korunumu: eşit büyüklükte momentum, kütle farkından hız karşılaştırması",
      "İki patenci birbirini iterek zıt yönlere kayıyor; hız, momentum ve itme büyüklüklerinin hangisinin öğrencide daha büyük olduğu soruluyor.",
      "no", "İtme-momentum 12. sınıfa (FİZ.12.1.3-4) taşındı; 11. sınıf programında yok.", "HIGH"),
    Q(2018, "AYT", 4, "Çubuğun dengesi ve tork oranı", [], "12. sınıf FİZ.12.1.1", None, "none", [],
      2, 2, 2, "", "kesirli şıklar (1/3, 2/3, 3/2, 3, 1)", "Mil noktasına göre tork dengesi; kuvvet kolu oranı",
      "Eşit bölmeli çubuk iki kuvvetle dengede; birinin torku verilmişken diğerinin torkunun oranı bulunuyor.",
      "no", "Tork ve denge 12. sınıf (FİZ.12.1.1-2) konusudur.", "HIGH"),
    Q(2018, "AYT", 5, "Düzgün elektrik alanda asılı yüklü cismin sapma açısı", ["FİZ.11.2.2", "FİZ.11.1.5"], "", "efield-force-balance-droplet", "partial", ["KB2.14"],
      2, 2, 0, "ms", ROMAN, "Denge: tanα = qE/mg; hangi niceliğin artınca açının arttığına nitel karar",
      "Elektrik alanda ipe asılı yüklü cisim dengede; ip uzunluğu, kütle ve alan artırılınca sapma açısının değişimi soruluyor.",
      "yes", "Alan–kuvvet oran/yön yorumu ve serbest cisim diyagramı; hesap gerekmiyor.", "HIGH"),
    Q(2018, "AYT", 6, "Manyetik alandaki akım taşıyan çubuğun harekete geçmesi", ["FİZ.11.2.8"], "", "wire-force-direction-rhr", "exact", ["FBAB10"],
      2, 2, 0, "ex", "hareket durumu seçenekleri (hareketsiz / I ya da II yönünde hızlanır / sabit hızlı)", "Sağ el kuralıyla kuvvet yönü; sürtünmesiz rayda ivmeli hareket",
      "Mıknatıs içinde ray üstünde duran çubuk, anahtar kapanınca akım taşır; çubuğun ilk hareketinin yönü ve türü soruluyor.",
      "yes", "Akımlı tele etki eden kuvvetin yönü ve F=BIL mantığı doğrudan kapsamda.", "HIGH"),
    Q(2018, "AYT", 7, "Transformatörde doğru ve alternatif akımla sekonder gerilimi", ["FİZ.11.2.13", "FİZ.11.2.12"], "", "transformer-turns-voltage-current-ratio", "partial", ["FBAB8"],
      3, 2, 0, "ms", "iki sütunlu şıklar (Sıfırdır / primerden büyük / küçük)", "DC primerde akı değişimi yok → sekonder sıfır; AA'da sarım oranına göre karşılaştırma",
      "Biri doğru akım, biri alternatif akım kaynağına bağlı iki transformatörün sekonder gerilimlerinin primere göre durumu soruluyor.",
      "yes", "Transformatör nitelikleri yalnız yorumlanıyor; sayısal sarım hesabı yok, program ile uyumlu.", "HIGH"),
    Q(2018, "AYT", 8, "Sarkacın en alt noktasında net kuvvet, ivme ve hız yönleri", ["FİZ.11.1.5", "FİZ.11.1.9"], "", "net-force-motion-state", "partial", ["KB2.14"],
      2, 3, 0, "", "vektör çizimi seçenekleri (üç vektörün yön kombinasyonları)", "Merkezcil ivme merkeze, net kuvvet ivmeyle aynı yön; hız teğet",
      "Salınan bilyenin en alt noktasından geçerken net kuvvet, merkezcil ivme ve hız vektörlerinin yönlerini gösteren doğru çizim seçiliyor.",
      "yes", "Net kuvvet-ivme ilişkisi ve çembersel hareketin merkezcil ivmesi kapsamda; sarkaç yalnız bağlam.", "MEDIUM"),
    Q(2018, "AYT", 9, "Dünya'nın yörüngesinde günberi: hız, açısal momentum, çekim kuvveti", [], "programda yok (kütle çekim/Kepler; açısal momentum yalnız 12. sınıf FİZ.12.1.6 dönme bağlamında)", None, "none", [],
      3, 2, 0, "", ROMAN, "Günberide hız ve çekim büyük; açısal momentum korunur (eşit)",
      "Dünya'nın Güneş'e en yakın olduğu günle uzak olduğu günün çizgisel hız, açısal momentum ve çekim kuvveti büyüklükleri karşılaştırılıyor.",
      "no", "Kütle çekim ve Kepler yasaları 9-12. sınıf programında yer almıyor.", "MEDIUM"),
    Q(2018, "AYT", 10, "Yay-kütle ve basit sarkaç periyotlarının eşitlenmesi", [], "programda yok (BHH periyot hesabı; 10. sınıf FİZ.10.4.1 yalnız kavramsal)", None, "none", [],
      2, 2, 3, "ms", NUM, "T=2π√(l/g) ile T=2π√(m/k) eşitlenir; k=mg/l",
      "Düşey yaya asılı kütlenin periyodu, belirli uzunluktaki basit sarkaçla eşit olacak şekilde yay sabiti soruluyor.",
      "no", "Basit harmonik hareket hesabı yeni programda yok.", "HIGH"),
    Q(2018, "AYT", 11, "Radyo dalgalarının doğası", [], "12. sınıf FİZ.12.3.5", None, "none", [],
      1, 1, 0, "dl", ROMAN, "Elektromanyetik dalga: enine, boşlukta yayılır, ses değildir",
      "Radyo vericisinden alıcıya gelen dalganın ses mi, enine mi, maddesel ortam gerektirir mi olduğu öncüllerle yargılanıyor.",
      "no", "Elektromanyetik dalgalar 12. sınıf (FİZ.12.3.5) konusu.", "HIGH"),
    Q(2018, "AYT", 12, "Döteryum-trityum füzyonu ve çekirdek kararlılığı", [], "12. sınıf FİZ.12.4.8", None, "none", [],
      3, 2, 0, "", ROMAN, "Enerji açığa çıkması: ürün çekirdek bağlanma enerjisi başına daha kararlı",
      "Füzyon tepkimesi enerji verdiğine göre hangi çekirdeklerin birbirine göre daha kararlı olması gerektiği öncüllerle soruluyor.",
      "no", "Nükleer enerji 12. sınıf (FİZ.12.4.8) konusu.", "MEDIUM"),
    Q(2018, "AYT", 13, "Fotoelektrik olay: Ek–f grafiği", [], "12. sınıf FİZ.12.4.2", None, "none", [],
      3, 2, 0, "gr", ROMAN, "Eğim h evrensel; eşik frekansı üstündeki f için elektron çıkar",
      "Maksimum kinetik enerji–frekans grafiğinden eğimin, eşik frekansının ve dalga boyunun yorumlanmasına dair öncüller değerlendiriliyor.",
      "no", "Fotoelektrik olay 12. sınıf (FİZ.12.4.2) konusu.", "HIGH"),
    Q(2018, "AYT", 14, "X ışınlarının görünür ışığa göre büyüklükleri", [], "12. sınıf FİZ.12.3.5", None, "none", [],
      2, 1, 0, "dl", ROMAN, "Elektromanyetik tayf sırası: X ışını frekansı büyük, dalga boyu küçük, hız aynı",
      "X ışınlarının canlılara zarar verebilmesinin hız, dalga boyu ve frekanstan hangisinin görünür ışıktan kesinlikle büyük olmasından kaynaklandığı soruluyor.",
      "no", "Elektromanyetik tayf 12. sınıf (FİZ.12.3.5) konusu.", "HIGH"),
]

# ============================ 2019 AYT (14/14 okundu) ============================
ITEMS += [
    Q(2019, "AYT", 1, "Göreli hız: iki aracın hız vektörlerinden gözlemciye göre hız", [], "9. sınıf FİZ.9.2.4 (vektör toplama); hareketli referans yalnız 11. sınıf zenginleştirmede", None, "none", [],
      2, 2, 2, "ms dl", "büyüklük+yön çiftleri (15√2 güneybatı …)", "Referans değişimi: vektör farkı; dik bileşenlerden Pisagor",
      "Batıya ve kuzeye sabit hızla giden iki araçtan birinin sürücüsüne göre diğerinin hızının büyüklüğü ve yönü isteniyor.",
      "no", "Vektör toplama 9. sınıf konusu; hareketli referanstan bakış 11. sınıf programında yalnız zenginleştirme düzeyinde.", "MEDIUM"),
    Q(2019, "AYT", 2, "Farklı yüksekliklerden yatay fırlatılan cisimlerin ilk hız oranı", ["FİZ.11.1.3"], "", "2d-horizontal-launch", "exact", ["FBAB10"],
      2, 2, 2, "ms gr", "kesirli/köklü oran şıkları (1/4, 1/√2, 1/2, 1, √2)", "Düşme süresi √h ile orantılı; aynı menzilde v ∝ 1/t",
      "Aynı noktaya düşen ve farklı yüksekliklerden yatay atılan iki cismin ilk hızlarının oranı soruluyor; yol şekille veriliyor.",
      "yes", "İki boyutta sabit ivmeli hareket için sayısal hesap programda kapsam içinde (CALC_INCLUDED).", "HIGH"),
    Q(2019, "AYT", 3, "Çarpışma testi: ortalama itme kuvveti", [], "12. sınıf FİZ.12.1.3", None, "none", [],
      2, 1, 2, "dl", NUM, "İtme = momentum değişimi; F = m·Δv/Δt",
      "Hareketli arabadan duran mankenin durması için gereken en az ortalama kuvvet, kütle, hız ve çarpışma süresiyle hesaplatılıyor.",
      "no", "İtme-momentum 12. sınıfa taşındı.", "HIGH"),
    Q(2019, "AYT", 4, "Dengedeki sandıkta net kuvvet sıfırken ivme, tork ve momentum", ["FİZ.11.1.4"], "tork ve momentum öncülleri 12. sınıf FİZ.12.1.1-3", None, "none", [],
      2, 2, 0, "dl", ROMAN, "Net kuvvet sıfır → ivme sıfır; tork ve momentum için 'kesinlikle' ayrımı",
      "Birkaç kişinin taşıdığı sandığa etkiyen bileşke kuvvet sıfırken kütle merkezi ivmesi, toplam tork ve çizgisel momentumun kesinlikle sıfır olup olmadığı yargılanıyor.",
      "form_changes", "Yalnız net kuvvet–ivme öncülü 11. sınıfta; tork ve momentum öncülleri 12. sınıf, biçim değişmeli.", "MEDIUM"),
    Q(2019, "AYT", 5, "Farklı yarıçaplı iletken bilyelerde yük aktarımı sonrası yük ve potansiyel", [], "programda yok (iletkenlerde yük paylaşımı, elektriksel potansiyel; 8. sınıf elektriklenme temel kabul)", None, "none", [],
      3, 2, 0, "ex", ROMAN, "Dokundurma sonrası potansiyeller eşit; yük miktarı yarıçapa bağlı, aynı işaretli",
      "İki farklı boyutta metal bilye yüklenip dokundurulduktan sonra net yük, potansiyel ve yük cinsi ile ilgili öncüller değerlendiriliyor.",
      "no", "Elektriksel potansiyel ve iletkende yük dağılımı yeni 9-12. sınıf programında yok.", "MEDIUM"),
    Q(2019, "AYT", 6, "Mıknatıs ve silginin halkadan düşerken Lenz etkisi", ["FİZ.11.2.10", "FİZ.11.2.11"], "", "magnet-falling-through-ring", "exact", ["KB2.4", "FBAB10"],
      3, 3, 0, "ex", "beş durum önermesi (yükseklik karşılaştırması, kutup/kütle bağımlılığı)", "Mıknatıs akı değişimi nedeniyle frenlenir; silgi serbest düşer; kontrol değişkeni mantığı",
      "Mıknatıs ile silgi alüminyum halkadan düşerken halkada akım oluşmasının mıknatısı geciktirmesi nedeniyle bunların halkayı geçtikten sonraki yükseklikleri karşılaştırılıyor.",
      "yes", "Akı değişimi ve indüksiyon akımının yönü/etkisi nitel; programda hesapsız kapsam uygun.", "HIGH"),
    Q(2019, "AYT", 7, "Müzik çalar devresinde frekansa göre direnç gösteren eleman", [], "programda yok (bobin/kondansatör reaktansı, AA devre elemanları)", None, "none", [],
      3, 2, 0, "dl", ROMAN, "Kondansatör düşük frekansa büyük direnç; bobin yüksek frekansa büyük direnç; reosta frekanstan bağımsız",
      "Düşük frekanslı sinyallere daha büyük direnç gösterecek devre elemanının bobin, reosta ve kondansatörden hangileri olabileceği soruluyor.",
      "no", "Bobin ve kondansatörün AA'daki davranışı programda yok.", "HIGH"),
    Q(2019, "AYT", 8, "Otoyol virajlarını güvenli kılan önlemler", ["FİZ.11.1.10"], "", "banked-curve", "exact", ["FBAB10"],
      2, 1, 0, "dl", ROMAN, "Eğimli viraj ve sürtünme kuvveti merkezcil kuvvete katkı; yarıçap küçültmek tehlikeli",
      "Araçların virajda güvenli dönmesi için yol-lastik sürtünmesi, virajın eğimi ve yarıçapına ilişkin önlemlerden hangilerinin uygulanması gerektiği öncüllerle soruluyor.",
      "yes", "Yatay ve eğimli viraj ile viraj güvenliği programda doğrudan var.", "HIGH"),
    Q(2019, "AYT", 9, "Kollarını gövdesine yaklaştıran patencide açısal momentum ve eylemsizlik momenti", [], "12. sınıf FİZ.12.1.5-6", None, "none", [],
      2, 2, 0, "dl", "iki sütunlu şıklar (artar / azalır / değişmez)", "Dış tork yok → açısal momentum korunur; kütle merkeze yaklaşınca eylemsizlik momenti azalır",
      "Buz pistinde dönen kişi kollarını gövdesine yaklaştırınca açısal momentum ve eylemsizlik momentinin nasıl değiştiği soruluyor.",
      "no", "Eylemsizlik momenti ve açısal momentum korunumu 12. sınıf konusu.", "HIGH"),
    Q(2019, "AYT", 10, "Yay-kütle sistemlerinde titreşim frekansları karşılaştırması", [], "programda yok (basit harmonik hareket frekansı, yay bağlama; 12. sınıf FİZ.12.2.1-2 yalnız Hooke)", None, "none", [],
      3, 3, 0, "ms", "frekans sıralaması şıkları (fX < fY = fZ …)", "f ∝ √(k_eş/m); eğik düzlem frekansı değiştirmez; seri yay k_eş küçük",
      "Düşeyde asılı, eğik düzlemde ve iki yaya seri asılı üç özdeş kütlenin titreşim frekansları arasındaki sıralama soruluyor.",
      "no", "Basit harmonik hareket ve yay sabitlerinin eşdeğeri yeni programda yok.", "MEDIUM"),
    Q(2019, "AYT", 11, "Elektromanyetik tayfta hız, frekans ve dalga boyu karşılaştırması", [], "12. sınıf FİZ.12.3.5", None, "none", [],
      2, 1, 0, "", ROMAN, "Aynı ortamda sürat aynı değil (boşlukta eşit); frekans: X > mikrodalga; dalga boyu: kırmızı > mavi",
      "Gama, X, mikrodalga, radyo ve görünür ışık dalgalarının sürat, frekans ve dalga boyu bakımından birbirine göre durumu öncüllerle sınanıyor.",
      "no", "Elektromanyetik dalga sınıflandırması 12. sınıf (FİZ.12.3.5-6).", "HIGH"),
    Q(2019, "AYT", 12, "Radyoaktif bozunma zincirinde yayınlanan parçacıklar", [], "12. sınıf FİZ.12.4.8 (yalnız sorgulama düzeyi; bozunma türleri programda açık değil)", None, "none", [],
      3, 2, 1, "ms", "iki sütunlu şıklar (β⁻/β⁺/α kombinasyonları)", "Kütle ve atom numarası değişimini izleyerek bozunma türünü bulma",
      "Bizmut çekirdeğinin iki ardışık bozunmayla kurşuna dönüşmesinde her adımda yayınlanan parçacığın türü kütle ve proton sayısı değişiminden bulunuyor.",
      "no", "Radyoaktif bozunma 12. sınıfta yalnız nükleer enerji sorgulaması kapsamında.", "MEDIUM"),
    Q(2019, "AYT", 13, "Fotoelektrik düzenekte kullanılabilecek eşik enerjisi sınırı", [], "12. sınıf FİZ.12.4.2", None, "none", [],
      3, 2, 3, "ms", NUM, "E = hc/λ ile ışık enerji aralığı; eşik ≤ foton enerjisi koşulu",
      "Dalga boyu aralığı ve hc değeri verilen ışıkla fotoelektron koparabilmek için metalin eşik enerjisinin en çok ne olabileceği hesaplatılıyor.",
      "no", "Fotoelektrik olay 12. sınıf konusu.", "HIGH"),
    Q(2019, "AYT", 14, "Termal kamera, PET ve sonarın görüntü oluşturma prensipleri", [], "12. sınıf FİZ.12.3.7", None, "none", [],
      2, 2, 0, "dl", "üçlü eşleştirme şıkları (cihaz sıralamaları)", "Cihaz–dalga türü eşleştirme (kızılötesi, ses, antiparçacık)",
      "Üç görüntüleme cihazının hangi fiziksel ilkeyle (kızılötesi yayım, ses yansıması, antiparçacık yok oluşu) görüntü oluşturduğu eşleştiriliyor.",
      "no", "Dalga kullanan cihazlar 12. sınıf (FİZ.12.3.7); PET kapsam dışı.", "MEDIUM"),
]

# ============================ 2020 AYT (14/14 okundu) ============================
ITEMS += [
    Q(2020, "AYT", 1, "Hareketli vagonda düşey atılan topun yere göre görülen yörüngesi", ["FİZ.11.1.3"], "", "2d-moving-reference-launch", "exact", ["FBAB10"],
      2, 2, 0, "dl", "yörünge çizimi seçenekleri (düşey doğru, eğri ve yatay-eğri kombinasyonları)", "Yatay bileşen vagonla aynı sabit hız, düşey bileşen sabit ivmeli; bileşke yörünge parabol",
      "Sabit hızla giden vagonda yukarı doğru atılan topun, yerde duran gözlemciye göre tepe noktasına kadar izlediği yolun şekli seçiliyor.",
      "form_changes", "Hareketli referanstan bakış programda yalnız zenginleştirme önerisidir; bileşenlerin bağımsızlığı kapsamda, soru nitel biçimde korunabilir.", "MEDIUM"),
    Q(2020, "AYT", 2, "Duvara yatay kuvvetle bastırılan tuğlalarda statik sürtünme kuvvetleri", ["FİZ.11.1.7", "FİZ.11.1.6", "FİZ.11.1.5"], "", "friction-wall-press", "exact", ["FBAB10"],
      2, 2, 1, "", "sıralama şıkları (fK > fL = fN … fK = fL = fN)", "Düşey denge: statik sürtünme ağırlığa eşittir; bastırma kuvveti sürtünmeyi belirlemez, yalnız kütle önemlidir",
      "Farklı kütleli ve farklı yatay kuvvetle duvara bastırılıp hareketsiz kalan üç tuğlanın duvara uyguladığı statik sürtünme kuvvetlerinin büyüklük sıralaması isteniyor.",
      "yes", "Statik sürtünmenin uygulanan kuvvete değil dengeye bağlı olması ve FCD yorumu programda doğrudan var.", "HIGH"),
    Q(2020, "AYT", 3, "Yukarı fırlatılan cismin hareketinde ivme yönü, hız bileşenleri ve mekanik enerji tablosu", ["FİZ.11.1.3"], "mekanik enerji öncülü 10. sınıf FİZ.10.2.4 ön bilgisi", "2d-angled-launch", "exact", ["FBAB10"],
      2, 2, 0, "tb", ROMAN, "Yatay bileşen sabit, ivme hep aşağı, düşey hız yükselirken azalır alçalırken artar, mekanik enerji korunur; her satır ayrı sınanır",
      "Hava direnci yokken yukarıya açılı fırlatılan cismin çıkış ve iniş evrelerinde ivme yönü, hız bileşenleri ve mekanik enerjisi için hazırlanmış tablonun doğru satırları seçiliyor.",
      "yes", "İki boyutlu hareketin bileşen yorumu ve yalnız g ivmesi doğrudan kapsamda; hesap gerekmiyor.", "HIGH"),
    Q(2020, "AYT", 4, "Çembersel ray (loop) ve yükseklikteki hedefe ulaşan oyuncak arabanın en küçük ilk hızı", ["FİZ.11.1.10"], "", "rail-system-circular", "exact", ["FBAB10"],
      3, 2, 3, "ms dl", NUM, "İki koşulun büyüğü alınır: çemberin tepesinde geçiş hızı koşulu ve hedef yüksekliğe çıkma; mekanik enerji korunumuyla ilk hıza geçilir",
      "Sürtünmesiz rayda önce küçük bir çember sonra yükselen yolu izleyen oyuncak arabanın, yüksekteki balona ulaşması için gereken en küçük ilk hız hesaplatılıyor.",
      "form_changes", "Düşey çember geçiş koşulu kapsamda ancak programda ray sistemlerinde matematiksel işlem açıkça dışlanır; ray bağlamı ve enerji hesabı çıkarılmalı.", "HIGH"),
    Q(2020, "AYT", 5, "Eşit kütleli iki arabanın esnek çarpışmasında hız ve momentum değişimi", [], "12. sınıf FİZ.12.1.4", None, "none", [],
      2, 3, 0, "", ROMAN, "Eşit kütleli esnek çarpışmada hız vektörleri takas edilir; yön ve momentum değişimi vektör olarak okunur",
      "Birimkareli zeminde hız vektörleri verilen eşit kütleli iki arabanın merkezî esnek çarpışmasından sonra hızlarının yönü ve momentumlarının değişip değişmediği yargılanıyor.",
      "no", "Momentum korunumu ve çarpışmalar 12. sınıfa (FİZ.12.1.3-4) taşındı; 11. sınıfta yok.", "HIGH"),
    Q(2020, "AYT", 6, "Yatay kuvvetle duvara dayalı sürtünmesiz bloklar dizisinde temas kuvvetleri", ["FİZ.11.1.5", "FİZ.11.1.4"], "", "newton3-action-reaction", "partial", ["KB2.14"],
      2, 2, 0, "", "kesirli şıklar (1/4, 1/2, 1, 3/2, 2)", "Her blok dengede: temas kuvvetleri zincirde birbirine eşit aktarılır; kütleler çeldiricidir",
      "Yatay kuvvetle itilen ve duvara dayanan üç farklı kütleli sürtünmesiz bloktan ilkinin ikinciye uyguladığı kuvvet verilip duvarın sonuncuya uyguladığı kuvvet isteniyor.",
      "yes", "Newton yasaları ve dengede serbest cisim diyagramı kapsamda; ivmesiz sistem olduğundan hesap kısıtı da sorun çıkarmıyor.", "MEDIUM"),
    Q(2020, "AYT", 7, "Düzgün elektrik alana dik fırlatılan zıt yüklü parçacıkların yörüngesi", ["FİZ.11.2.2", "FİZ.11.1.5"], "", "efield-charged-particle-deflection", "exact", ["KB2.14"],
      2, 3, 0, "dl", "yörünge çizimi çiftleri (sapma yönü ve yörünge biçimi kombinasyonları)", "Pozitif yük alan yönünde, negatif yük ters yönde kuvvet alır; başlangıç hızına dik sabit kuvvet eğri yörünge verir",
      "Yer çekimi yokken sağa yönlü düzgün alana dik hızla gönderilen pozitif ve negatif yüklü iki parçacığın alan içindeki yörüngelerini gösteren doğru çizim seçiliyor.",
      "yes", "Alan yönü ile yük işareti ilişkisi ve kuvvetin hareket yörüngesine etkisi nitel düzeyde kapsamda.", "HIGH"),
    Q(2020, "AYT", 8, "Manyetik alanda hareket eden iletken çubuğun uçlarında yük ayrışması", ["FİZ.11.2.8", "FİZ.11.2.11"], "hareketli yüke etki eden kuvvetin yönü programda ayrı çıktı değil (yalnız FİZ.11.2.8 notu)", None, "none", [],
      3, 3, 0, "", "işaret çiftleri (+/−, nötr kombinasyonları)", "Hareketli yüklere kuvvet yönü sağ el kuralıyla bulunur; pozitif yük bir uca toplanır, öbür uç negatif kalır",
      "Sayfa düzlemine dik alanda sabit hızla ilerleyen nötr metal çubuğun iki ucunda oluşan elektrik yük dağılımının işaretleri soruluyor.",
      "form_changes", "Hareket eden iletkende yük ayrışması indüksiyon gerilimi ile ilişkili ama serbest yüke etki eden kuvvet ayrı çıktı değil; bağlam ve yön kuralı açıkça verilmeli.", "MEDIUM"),
    Q(2020, "AYT", 9, "Elektriğin yüksek gerilimde taşınmasının temel nedeni", ["FİZ.11.2.13"], "", "transformer-transmission-loss", "exact", ["FBAB8"],
      1, 1, 0, "dl", "gerekçe ifadeleri (enerji kaybı, gerilim düşmesi, süre, depolama, talep)", "Yüksek gerilimde akım küçülür, iletim hattında ısı kaybı azalır; yanlış gerekçeler elenir",
      "Enerjinin santrallerden uzaktaki tüketim bölgelerine yüksek gerilimde taşınmasının temel gerekçesi seçeneklerden bulunuyor.",
      "yes", "Transformatörlerin kullanım alanı ve iletimde enerji kaybı nitel olarak doğrudan programdadır.", "HIGH"),
    Q(2020, "AYT", 10, "Dönme dolabın kabinlerinde farklı noktalardaki merkezcil kuvvet", ["FİZ.11.1.10", "FİZ.11.1.9"], "", "circular-analogies", "partial", ["FBAB10"],
      2, 2, 1, "dl", "sıralama şıkları (FA = FB = FC = FD … FC > FA > FB = FD)", "Sabit açısal hız ve sabit yarıçapta F = mω²r aynıdır; konum merkezcil kuvvetin büyüklüğünü değiştirmez",
      "Sabit açısal hızla dönen dönme dolapta kütle merkezinin eksene uzaklığı sabit olan bir kişiye A, B, C, D noktalarında etkiyen merkezcil kuvvet büyüklükleri karşılaştırılıyor.",
      "yes", "Düzgün çembersel harekette merkezcil kuvvet modeli ve düşey düzlem bağlamı programda doğrudan var.", "HIGH"),
    Q(2020, "AYT", 11, "Momentumu değişen ama kütlesi ve kinetik enerjisi sabit hareketin yorumu", ["FİZ.11.1.4", "FİZ.11.1.9"], "çizgisel momentum 12. sınıf FİZ.12.1.3; iş-enerji 10. sınıf FİZ.10.2.1-2 ön bilgisi", "net-force-motion-state", "partial", ["KB2.14"],
      3, 3, 0, "", ROMAN, "Hız büyüklüğü sabit, yönü değişen hareket tanınır (düzgün çembersel); net kuvvet ve ivme var, kuvvet iş yapmaz",
      "Çizgisel momentumu değişen fakat kütle ve kinetik enerjisi sabit kalan cisim için net kuvvet, yapılan iş ve ivmenin sıfır olup olmadığı kesin yargılarla sınanıyor.",
      "form_changes", "'Momentum' dili 12. sınıfa ait; hızın yönü değişen sabit sürat bağlamıyla yeniden yazılırsa çembersel hareket çıktısına uyar.", "MEDIUM"),
    Q(2020, "AYT", 12, "Eylemsizlik momentinin bağlı olduğu nicelikler", [], "12. sınıf FİZ.12.1.5", None, "none", [],
      2, 1, 0, "", ROMAN, "Eylemsizlik momenti dönmeye direncin ölçüsüdür, kütleye ve eksene uzaklığa bağlıdır, dönüş yönüne bağlı değildir",
      "Bir cismin belirli bir eksene göre eylemsizlik momentine dair üç yargıdan (direncin ölçüsü, kütle, dönüş yönü) hangilerinin doğru olduğu soruluyor.",
      "no", "Eylemsizlik momenti 12. sınıf (FİZ.12.1.5) konusu.", "HIGH"),
    Q(2020, "AYT", 13, "İki dairesel su dalgası kaynağında girişim noktaları", [], "12. sınıf FİZ.12.3.2", None, "none", [],
      2, 3, 0, "dl", "nokta kümeleri (Yalnız A, B ve C, …)", "Tepe-tepe ve çukur-çukur kesişim noktalarında yapıcı, tepe-çukur kesişiminde yıkıcı girişim; hareketsiz kalanlar yıkıcı düğüm noktalarıdır",
      "Aynı fazlı iki dairesel su dalgası kaynağının çizilen dalga tepelerinde A, B, C noktalarından hangilerinde hafif cisimlerin hareketsiz kalabileceği soruluyor.",
      "no", "Dairesel su dalgalarında girişim 12. sınıf (FİZ.12.3.2) konusu.", "HIGH"),
    Q(2020, "AYT", 14, "Ay yüzeyinde basit sarkaç ve yay-kütle periyotlarının değişimi", [], "programda yok (sarkaç ve yay periyodu; 10. sınıf FİZ.10.4.1 yalnız deneyim düzeyi, farklı g yalnız 11. sınıf zenginleştirme)", None, "none", [],
      3, 2, 0, "ex dl", "iki sütunlu şıklar (artar / azalır / değişmez)", "Sarkaç periyodu g'ye bağlı, yay-kütle periyodu g'den bağımsız; Ay'da g küçük olduğundan sarkaç periyodu artar",
      "Basit sarkaç ve düşey yay-kütle düzeneği aynı koşullarla Ay'a taşınsaydı iki periyodun nasıl değişeceği sorulan simülasyon bağlamlı bir deney senaryosu.",
      "no", "Salınım periyotlarının bağlı olduğu değişkenler yeni programda yok; farklı gezegen g'si yalnız serbest düşme zenginleştirmesinde geçer.", "MEDIUM"),
]

# ============================ 2021 AYT (14/14 okundu) ============================
ITEMS += [
    Q(2021, "AYT", 1, "Birimkareli düzlemde üç yük: bileşke elektriksel kuvvetin yönü", ["FİZ.11.2.1"], "", "coulomb-direction-newton3", "partial", ["FBAB10"],
      2, 3, 0, "", "vektör yönü okları (A–E sekiz yönden beşi)", "Verilen bileşkeden yük işaretleri çıkarılır; sonra aynı yüklerin Y üzerindeki kuvvetleri vektör olarak toplanır; çekme-itme yönleri belirlenir",
      "Karelerden oluşan zeminde X üzerindeki bileşke kuvvet verilmişken, aynı X ve Z yüklerinin Y'ye uygulayacağı bileşkenin olabilecek yönü soruluyor.",
      "yes", "Coulomb kuvvetinin yönü ve vektörel toplama programda hesapsız (yön) düzeyde var; işaret çıkarımı beceriye uygun.", "MEDIUM"),
    Q(2021, "AYT", 2, "Atılıp aynı yükseklikte tutulan topta sporcunun ortalama hızı", ["FİZ.11.1.3"], "", "2d-angled-launch", "exact", ["FBAB10"],
      2, 2, 2, "ms dl", NUM, "Yatay bileşen sabit; aynı seviyede yakalanan topun yer değiştirmesi yataydır, ortalama hız yatay hız bileşenine eşittir (v·cos53)",
      "Yatayla belirli açıyla atılıp aynı yükseklikte yakalanan topun atış ile tutuş arasında sporcunun ortalama hızının büyüklüğü hesaplatılıyor.",
      "yes", "İki boyutta sabit ivmeli hareketin bileşenleri ve trigonometrik hız bileşeni programda hesap düzeyinde var.", "HIGH"),
    Q(2021, "AYT", 3, "Basamak kenarından üç farklı yönde aynı hızla vurulan topun yere çarpma sürati", ["FİZ.11.1.3"], "", "2d-velocity-at-point", "exact", ["FBAB10"],
      2, 2, 0, "ms", "sıralama şıkları (vK > vL > vM … vK = vL = vM)", "Aynı ilk sürat ve aynı düşme yüksekliği: yatay bileşen sabit, v² = v0² + 2gh; açıdan bağımsız eşit sürat",
      "Hava direnci yokken basamak kenarından eşit büyüklükte ilk hızla, üç farklı eğimle fırlatılan topun yere çarpma anındaki süratlerinin birbirine göre durumu soruluyor.",
      "yes", "İki boyutlu harekette bir noktadaki hız ve bileşen mantığı kapsamda; enerji korunumu yerine kinematikle de çözülebilir.", "HIGH"),
    Q(2021, "AYT", 4, "El arabasının iki dengesinde kuvvet, tork ve net kuvvet değişimi", [], "12. sınıf FİZ.12.1.1-2", None, "none", [],
      3, 3, 0, "dl", ROMAN, "O noktasına göre tork dengesi: ağırlığın kolu sıfırlanınca uygulanan kuvvet ve torku azalır; net kuvvet iki durumda da sıfırdır",
      "Karpuzlu el arabası, yük merkezi tekerlek ekseniyle aynı düşeye getirilerek dengede tutulunca el kuvvetinin, onun torkunun ve net kuvvetin ilk duruma göre azalıp azalmadığı soruluyor.",
      "no", "Tork ve denge 12. sınıf (FİZ.12.1.1-2) konusudur.", "HIGH"),
    Q(2021, "AYT", 5, "İki noktasal yükün çevresinde noktalar arası elektriksel potansiyel farkı", [], "programda yok (elektriksel potansiyel ve potansiyel farkı; Coulomb ve alan yalnız oran/yön düzeyinde)", None, "none", [],
      3, 3, 2, "ms", ROMAN, "V = kq/d ile her noktanın toplam potansiyeli bulunur; uzaklık aralıkları verilince hangi çiftte fark sıfır olabilir sınanır",
      "+q ve +2q yükleri çevresinde çizilen eş merkezli çemberler üzerindeki K, L, M noktalarından hangi çiftlerin arasındaki potansiyel farkının sıfır olabileceği soruluyor.",
      "no", "Elektriksel potansiyel yeni programda yok; yalnız kuvvet ve alan oran/yön düzeyinde (FİZ.11.2.1-2).", "HIGH"),
    Q(2021, "AYT", 6, "Bobin, demir bilye ve bakır yuvalı devrede bilyenin hareketi", ["FİZ.11.2.7", "FİZ.11.2.6"], "", "emag-verify-and-apply", "partial", ["KB2.6"],
      2, 3, 0, "ex", "hareket senaryoları (periyodik yukarı-aşağı, hareketsiz, yapışık, sabit, asılı kalma)", "Devre kapanınca bobin bilyeyi çeker; bilye yuvadan ayrılınca akım kesilir, alan kalkar ve düşer; bu döngü yineler",
      "Bilyenin devreyi tamamladığı bir elektromıknatıslı kapalı kutuda anahtar kapatılınca demir bilyenin hareketine ilişkin olası yargı seçiliyor.",
      "yes", "Elektromıknatısın çalışma ilkesini yeni bir düzenekte yorumlama; hesapsız ve programdaki akım makarası alanı bilgisine uygun.", "MEDIUM"),
    Q(2021, "AYT", 7, "Enerji iletim hattında iki transformatörün sarım sayısı ilişkileri", ["FİZ.11.2.13"], "", "transformer-turns-voltage-current-ratio", "exact", ["FBAB8"],
      2, 2, 0, "dl", "sarım karşılaştırması çiftleri (N1p < N1s ve N2p > N2s …)", "İletimde akım küçük, gerilim büyük olmalı: ilk trafo yükseltici, ikinci alçaltıcı; sarım oranları buna göre sıralanır",
      "Santral çıkışında gerilimi yükselten ve evde 220 V'a indiren iki transformatörün primer ve sekonder sarım sayıları arasındaki doğru ilişki çifti seçiliyor.",
      "yes", "Yükseltici/alçaltıcı transformatör ve iletimde enerji kaybı programdaki yorum düzeyinde, hesapsız.", "HIGH"),
    Q(2021, "AYT", 8, "Düzgün çembersel hareketle ilgili tork, net kuvvet ve merkezcil ivme", ["FİZ.11.1.9", "FİZ.11.1.10"], "tork öncülü 12. sınıf FİZ.12.1.1", "horizontal-circle", "partial", ["KB2.14"],
      2, 3, 0, "", ROMAN, "Net kuvvet merkezcil ve sıfır değildir, merkezcil ivme sıfırdan farklıdır; kuvvet yarıçap doğrultusunda olduğundan merkeze göre tork sıfırdır",
      "Sürtünmesiz yatay düzlemde düzgün çembersel hareket yapan cisim için merkeze göre tork, net kuvvet ve merkezcil ivmeden hangilerinin sıfır olduğu soruluyor.",
      "form_changes", "Net kuvvet ve merkezcil ivme kapsamda; merkeze göre tork öncülü 12. sınıf konusu, çıkarılırsa soru uyar.", "MEDIUM"),
    Q(2021, "AYT", 9, "Yer sabit (jeosenkron) uydunun yörünge yarıçapı ve dönme koşulu", [], "programda yok (uydu hareketi, kütle çekim, yörünge periyodu; Astronomi yalnız disiplinler arası ilişki)", None, "none", [],
      3, 3, 0, "dl", "düzeltme önerileri (kütle azalt/artır, yarıçap büyüt/küçült, ters yön)", "Uydu doğuya hareket ediyorsa açısal hızı Dünya'dan büyük; periyot uzatmak için yarıçap büyütülür, kütle etkisizdir",
      "Yerden bakana göre sabit durması gereken televizyon uydusu doğuya kayıyorsa bu hatayı düzeltmek için kütle, yarıçap veya dönüş yönü seçeneklerinden hangisinin değiştirileceği soruluyor.",
      "no", "Kütle çekim, uydu yörüngeleri ve Kepler ilişkileri 9-12. sınıf programında yok.", "MEDIUM"),
    Q(2021, "AYT", 10, "Basit harmonik hareketin konum-zaman grafiğinden periyot, genlik ve denge", [], "programda yok (basit harmonik hareketin x–t grafiği; 10. sınıf FİZ.10.4.1-2 yalnız periyot ve genlik kavramları)", None, "none", [],
      2, 2, 1, "gr", ROMAN, "Grafikten periyot (tam salınım süresi), genlik (maksimum uzaklık) ve konum sıfır anı okunur; genlikle tepeden tepeye aralık karıştırılmaz",
      "Sinüs biçimli konum-zaman grafiği verilen cismin periyodu, genliği ve belirli bir anda denge konumunda olup olmadığına dair üç yargı değerlendiriliyor.",
      "no", "Basit harmonik hareket yeni programda yok; periyot-genlik yalnız dalga bağlamında 10. sınıfta.", "MEDIUM"),
    Q(2021, "AYT", 11, "Çift yarıkta yeşil yerine kırmızı ışık kullanılınca saçak değişimi", [], "12. sınıf FİZ.12.3.3 (ve FİZ.12.3.6)", None, "none", [],
      2, 2, 0, "ex", ROMAN, "Dalga boyu büyüyünce saçak genişliği artar; merkezî aydınlık saçak aynı yerde kalır; diğer saçakların yeri değişir",
      "Çift yarık deneyinde ışığın rengi yeşilden kırmızıya çevrilince saçak genişliği, merkezî aydınlık saçağın yeri ve diğer saçakların yeri hakkındaki yargılar sınanıyor.",
      "no", "Işıkta girişim 12. sınıf (FİZ.12.3.3) konusu.", "HIGH"),
    Q(2021, "AYT", 12, "Radyoaktif ve kararlı çekirdeklerin ortak özellikleri", [], "12. sınıf FİZ.12.4.8 (radyoaktivite programda yalnız nükleer enerji sorgulaması düzeyinde)", None, "none", [],
      3, 2, 0, "", ROMAN, "Her öncül hem radyoaktif hem kararlı çekirdek için sınanır; yalnız radyoaktife özgü özellikler elenir",
      "Rastgele seçilen radyoaktif ve kararlı bir çekirdek için kendiliğinden ışıma, nötron fazlası ve bozunmayla başka çekirdeğe dönüşme özelliklerinden hangilerinin ortak olabileceği soruluyor.",
      "no", "Çekirdek kararlılığı ve radyoaktivite 12. sınıf nükleer enerji bölümündedir.", "MEDIUM"),
    Q(2021, "AYT", 13, "Elektroskoplarda morötesi ışıkla fotoelektron kopması ve yük cinsi", [], "12. sınıf FİZ.12.4.2 (elektrikle yüklenme 8. sınıf ön bilgi)", None, "none", [],
      3, 3, 0, "ex", "iki sütunlu şıklar (pozitif / negatif / nötr)", "Eşik enerjisini aşan foton yalnız negatif yüklü elektroskoptan elektron söker, yaprak biraz kapanır; pozitifte değişim görünmez",
      "Morötesi ışıkla aydınlatılan iki elektroskoptan birinin yaprakları biraz kapanırken diğerinde değişim yok; her birinin yük cinsi için olası eşleşme seçiliyor.",
      "no", "Fotoelektrik olay 12. sınıf (FİZ.12.4.2) konusudur.", "HIGH"),
    Q(2021, "AYT", 14, "Lazer ışığının elde edilişinde atomda gerçekleşen olaylar", [], "programda yok (lazer; atomda uyarılma ve foton yayınlama 12. sınıf FİZ.12.4.7 çerçevesinde anılmıyor)", None, "none", [],
      2, 1, 0, "dl", ROMAN, "Lazerde uyarılma ve uyarılmış ışıma gerçekleşir; füzyon çekirdek olayıdır, atom düzeyinde olmaz",
      "Lazer ışığı üretilirken atomda uyarılma, foton yayınlama ve füzyon olaylarından hangilerinin gerçekleştiği öncüllerle soruluyor.",
      "no", "Lazer ve uyarılmış ışıma yeni 9-12. sınıf programında açıkça yok.", "MEDIUM"),
]

# ============================ 2022 AYT (14/14 okundu) ============================
ITEMS += [
    Q(2022, "AYT", 1, "Sürtünmesiz yatayda iki kişinin farklı yönlerde etkilediği kolinin hareket yönü", ["FİZ.11.1.4", "FİZ.11.1.5"], "vektör toplama ön bilgisi 9. sınıf FİZ.9.2.4", "net-force-motion-state", "exact", ["KB2.14"],
      2, 3, 0, "dl", ROMAN, "Ahmet kolayı yatay iter, Ali iple çeker; bileşke bu iki kuvvet arasında kalır, yalnız büyüklük oranına göre ulaşılabilen yönler seçilir",
      "Yandan itilen ve iple çekilen kolinin, iki kuvvetin büyüklükleri değiştikçe üç işaretli yönden hangilerine doğru harekete geçebileceği soruluyor.",
      "yes", "Bileşke kuvvet ile hareket yönü ilişkisi programda doğrudan var; hesap gerekmiyor.", "MEDIUM"),
    Q(2022, "AYT", 2, "Sabit hızlı kamyonda duran sandığa etki eden kuvvetler (yerdeki gözlemci)", ["FİZ.11.1.4", "FİZ.11.1.5"], "", "newton1-inertia", "exact", ["KB2.14"],
      2, 2, 0, "dl", ROMAN, "Sabit hızda net kuvvet sıfır: yatay kuvvet yok; düşey kuvvetler dengede, sandık kamyona ağırlığı kadar bastırır",
      "Yatay yolda sabit hızla giden kamyonun kasasında durağan sandık için yatay kuvvet, düşey kuvvet ve net kuvvet yargıları yerdeki gözlemciye göre değerlendiriliyor.",
      "yes", "Eylemsizlik ve net kuvvetin sıfır olduğu durumun yorumu programda doğrudan; soru biçimi uygun.", "HIGH"),
    Q(2022, "AYT", 3, "Yumurtanın sert zemine ve yumuşak ambalaja çarpması: temas süresi, momentum ve ortalama kuvvet", [], "12. sınıf FİZ.12.1.3", None, "none", [],
      2, 2, 0, "ex dl", ROMAN, "Momentum değişimi aynı; temas süresi artar, ortalama kuvvet azalır; her nicelik ayrı ayrı sınanır",
      "Aynı yükseklikten sert zemine ve köpükle sarılı hâlde bırakılan iki yumurtanın temas süresi, momentum değişimi ve ortalama kuvvetin ikinci durumda artıp artmadığı soruluyor.",
      "no", "İtme-momentum 12. sınıf (FİZ.12.1.3) konusu.", "HIGH"),
    Q(2022, "AYT", 4, "Makas seçimi ve tel konumuna göre kesme kuvvetinin büyüklüğü", [], "12. sınıf FİZ.12.1.1", None, "none", [],
      2, 3, 1, "dl", "beş şekil seçeneği (makas ve tel konumu kombinasyonları)", "Tork dengesi: kesme kuvveti kuvvet kolunun kesme noktasına olan kola oranıyla artar; birimkareli şekilden kollar okunur",
      "Farklı boy ve destek noktalı üç makas arasından, telin hangi konumunda aynı el kuvvetiyle bıçakların tele en büyük kuvveti uygulayacağı şekillerden seçiliyor.",
      "no", "Tork ve kaldıraç 12. sınıf (FİZ.12.1.1) konusudur.", "HIGH"),
    Q(2022, "AYT", 5, "Parçacığın düz yörünge ve çember yörüngesinde elektrik ya da manyetik alan türü", ["FİZ.11.2.2", "FİZ.11.2.8"], "yüklü parçacığa manyetik alanın uyguladığı kuvvet programda ayrı çıktı değil (yalnız FİZ.11.2.8 notu)", None, "none", [],
      3, 3, 0, "ex", "iki bölge için alan türü ve yönü çiftleri (elektrik/manyetik, sembol ve ok yönü)", "Çembersel yörünge manyetik alanı gösterir; kuvvet yönü ve yük işaretinden alan sembolü çıkarılır; düz yörünge için uyumlu alan türü seçilir",
      "Pozitif yüklü parçacığın birinci bölgede düz, ikincisinde çembersel gittiği bilinirken iki bölgedeki alanın türü ve yönü için olası çift seçiliyor.",
      "no", "Hareketli yüke etki eden manyetik kuvvet ve çembersel yörünge programda yok; yalnız alan yönü ve yük işareti ilişkisi var.", "MEDIUM"),
    Q(2022, "AYT", 6, "Compton olayında saçılan fotonun hız, momentum ve dalga boyu değişimi", [], "12. sınıf FİZ.12.4.2 (foton kavramı; Compton olayı programda anılmıyor)", None, "none", [],
      3, 2, 0, "", ROMAN, "Işık hızı değişmez; enerji kaybı momentumu azaltır, dalga boyu artar",
      "X-ışını fotonlarının serbest elektronlardan saçılmasında saçılan fotonun hız, momentum ve dalga boyunun gelene göre azalıp azalmadığı öncüllerle soruluyor.",
      "no", "Compton olayı 11-12. sınıf programında yok; foton kavramı 12. sınıfta.", "MEDIUM"),
    Q(2022, "AYT", 7, "Transformatörün uçlarının 110 V cihaz ve 220 V prize bağlanması", ["FİZ.11.2.13"], "", "transformer-turns-voltage-current-ratio", "partial", ["FBAB8"],
      2, 3, 0, "dl", "uç eşleştirme dizileri (K, L, M, N için 1-4 kablo permütasyonları)", "220 V'u 110 V'a indirmek için çok sarımlı bobin primerdir (prize), az sarımlı sekonderdir (cihaza); uç harfleri şekle göre eşleşir",
      "Sarım sayıları arasında iki kat fark olan hazır bir transformatörün K, L, M, N uçlarının 110 V cihaz kabloları ile prize hangi sırayla bağlanacağı soruluyor.",
      "yes", "Alçaltıcı transformatörün yapısı ve primer-sekonder ilişkisi hesapsız yorum düzeyinde programda var.", "MEDIUM"),
    Q(2022, "AYT", 8, "Dönen hedef tahtasında farklı yarıçaplardaki oklar: çizgisel ve açısal sürat", ["FİZ.11.1.10"], "", "circular-kinematics", "exact", ["FBAB10"],
      1, 2, 0, "dl", "iki sütunlu sıralama şıkları (vK = vL = vM … vM > vL > vK; ωK = ωL = ωM …)", "Aynı cisim üzerindeki noktaların açısal hızı eşit; v = ωr olduğundan yarıçap büyüdükçe çizgisel sürat büyür",
      "Sabit açısal hızla dönen hedef tahtasında merkeze farklı uzaklıkta saplanan K, L, M oklarının çizgisel süratleri ve açısal süratleri arasındaki ilişkiler soruluyor.",
      "yes", "Çizgisel sürat, açısal hız ilişkisi programda doğrudan var; hesap gerekmiyor.", "HIGH"),
    Q(2022, "AYT", 9, "Eliptik yörüngede Yerküre'nin iki konumunda açısal momentum ve çizgisel hız", [], "programda yok (kütle çekim ve eliptik yörünge; açısal momentum korunumu 12. sınıf FİZ.12.1.6 dönme bağlamında)", None, "none", [],
      3, 2, 0, "", "iki sütunlu şıklar (LA = LB, vA < vB … )", "Merkezî kuvvet torksuzdur: açısal momentum korunur; yarıçap büyük olan konumda çizgisel hız küçüktür",
      "Güneş çevresinde eliptik yörüngedeki Yerküre'nin Güneş'e uzak ve yakın iki konumunda Güneş-Yerküre sisteminin açısal momentumu ile çizgisel hız büyüklükleri karşılaştırılıyor.",
      "no", "Kütle çekim ve Kepler yasaları 9-12. sınıf programında yok; açısal momentum 12. sınıf.", "HIGH"),
    Q(2022, "AYT", 10, "Yaya bağlı cismin basit harmonik hareketinde ivme, esneklik potansiyel enerjisi ve kuvvet-hız yönü", [], "programda yok (basit harmonik hareket; yay potansiyel enerjisi 12. sınıf FİZ.12.2.3)", None, "none", [],
      3, 2, 0, "", ROMAN, "Sürat en küçükken (uç noktada) ivme ve potansiyel enerji en büyüktür; yay kuvveti hareket boyunca hızla hep ters yönlü değildir",
      "Sürtünmesiz düzlemde yaya bağlı cismin salınımında süratin en düşük olduğu andaki ivme ve potansiyel enerji ile kuvvet ve hızın yönleri öncüllerle sınanıyor.",
      "no", "Basit harmonik hareket yeni programda yok; yay potansiyel enerjisi 12. sınıf FİZ.12.2.3.", "MEDIUM"),
    Q(2022, "AYT", 11, "Doppler etkisinin gözlenebildiği dalga türleri", [], "programda yok (Doppler olayı; dalga türleri 10. sınıf FİZ.10.4.3, elektromanyetik dalga 12. sınıf FİZ.12.3.5)", None, "none", [],
      2, 1, 0, "", ROMAN, "Doppler etkisi kaynağa ve alıcıya göre hareketle her dalga türünde (mekanik ve elektromanyetik) gözlenir",
      "Kaynak ile alıcı arasındaki göreli hareketle frekansın farklı algılanması tanımı verilip enine, boyuna ve elektromanyetik dalgalardan hangilerinde bunun görülebileceği soruluyor.",
      "no", "Doppler etkisi yeni 9-12. sınıf programında yok.", "HIGH"),
    Q(2022, "AYT", 12, "Standart modelde Higgs bozonuyla etkileşen parçacıklar", [], "12. sınıf FİZ.12.4.6", None, "none", [],
      2, 1, 0, "", ROMAN, "Higgs alanıyla etkileşen kütleli parçacıklar (elektron, kuarklar) ile kütlesiz foton ayrılır",
      "Higgs bozonu ile kütle kazanma bilgisi verilip foton, elektron ve yukarı kuarktan hangilerinin Higgs bozonuyla etkileştiği soruluyor.",
      "no", "Standart model 12. sınıf (FİZ.12.4.6) konusu.", "HIGH"),
    Q(2022, "AYT", 13, "Özel görelilik kuramının postülaları", [], "programda yok (özel görelilik postülaları; 12. sınıf yalnız kütle-enerji eşdeğerliğini anar)", None, "none", [],
      2, 1, 0, "", ROMAN, "Işık hızı gözlemciden ve kaynaktan bağımsız sabittir; fizik yasaları eylemsiz gözlemcilere göre aynıdır",
      "Özel göreliliğin dayandığı varsayımlardan ışık hızının gözlemci ve kaynak hareketinden bağımsızlığı ile fizik yasalarının gözlemciye bağlılığı yargılarının doğruluğu soruluyor.",
      "no", "Özel görelilik 9-12. sınıf programında yok.", "HIGH"),
    Q(2022, "AYT", 14, "Tıbbi görüntülemede MR, ultrason ve tomografinin dalga türleri", [], "12. sınıf FİZ.12.3.7 (ve FİZ.12.3.5)", None, "none", [],
      2, 2, 0, "dl", ROMAN, "Metal yasağı manyetik alana, zararlı ışın X-ışınına, dalga kullanmama ultrasona işaret eder; yöntemler eşleştirilir",
      "Üç kişinin görüntüleme cihazına dair ipuçlarından (metal yasağı, zararlı ışın, elektromanyetik dalga yokluğu) hangi yöntem hangi kişiye ait olabilir sorgulanıyor.",
      "no", "Dalga kullanan görüntüleme cihazları 12. sınıf (FİZ.12.3.7) konusu.", "MEDIUM"),
]
