"""STEP 8 — Ünite 1 (Kuvvet ve Hareket) soru ailesi ontolojisinin elle yazılmış kaynak verisi.

Soru ailesi = aynı fiziksel durum + aynı ölçülen süreç bileşeni + aynı çözüm mantığı. Sayılar, bağlam ve
gösterim değişince aile değişmez; bunlar `variations` altında toplanır.

Kanıt kuralları (build_question_families.py doğrular):
  - ("tb", sayfa, "öğe", "anahtar")    : ders kitabı; `anahtar` o sayfanın metninde geçmek zorunda
  - ("prog", "anchor")                 : resmî öğretme uygulaması; anchor ilgili çıktının metninde geçmek zorunda
  - ("kil", sayfa)                     : MEB Bağlam Temelli Soru Yazım Kılavuzu (yöntem ilkesi)
Piyasa (Tier 3) ve ÖSYM kanıtı STEP 9–10'da eklenecek; bu aşamada iddia edilmez.

Hata türü kodları (STEP 13'te ayrıntılandırılacak): CONCEPTUAL_ERROR, FORMULA_SELECTION_ERROR,
FORMULA_APPLICATION_ERROR, SIGN_ERROR, UNIT_ERROR, VECTOR_ERROR, GRAPH_READING_ERROR, TABLE_READING_ERROR,
ALGEBRA_ERROR, ARITHMETIC_ERROR, QUESTION_INTERPRETATION_ERROR, METHOD_SELECTION_ERROR, PREREQUISITE_GAP,
CARELESS_ERROR
"""


def QF(slug, name, components, concepts, formulas, stimulus, structure, given, asked, variations, distractors,
       errors, methods, difficulty, evidence, scope="CORE", scope_note=None, shortcuts=()):
    return dict(slug=slug, name=name, components=components, concepts=concepts, formulas=formulas,
                stimulus=stimulus, structure=structure, given=given, asked=asked, variations=variations,
                distractors=distractors, errors=errors, methods=methods, difficulty=difficulty,
                evidence=evidence, scope=scope, scope_note=scope_note, shortcuts=list(shortcuts))


D = lambda text, targets: {"distractor_logic": text, "targets": targets}   # targets: yanılgı ya da hata
E = lambda text, code: {"error": text, "error_type": code}
V = lambda kind, text: {"kind": kind, "text": text}  # kind: common | graph | table | experimental | daily_life

FAMILIES = [
    # ======================= FİZ.11.1.1 =======================
    QF("ff-mass-independence", "Serbest düşmede ivmenin kütleden bağımsızlığı",
       ["FİZ.11.1.1:a", "FİZ.11.1.1:b"], ["serbest-dusme", "yer-cekimi-ivmesi", "kutle", "hava-direnci"], ["free-fall-v-v0zero"],
       ["DAILY_LIFE_CONTEXT", "DIAGRAM", "TEXT"],
       "Hava direncinin ihmal edildiği (ya da edilmediği) bir ortamda farklı kütleli cisimler aynı yükseklikten bırakılır; düşme süreleri, hızları ya da ivmeleri karşılaştırılır.",
       ["kütleler", "ortam (havalı / havasız)", "bırakılma yüksekliği"], ["ivme / süre / hız karşılaştırması"],
       [V("common", "Havasız ortamda tüy ve çekiç; vakum tüpünde madeni para ve tüy"),
        V("daily_life", "Ay yüzeyinde astronotun çekiç-tüy deneyi"),
        V("experimental", "Farklı kütleli bilyelerin düşme sürelerinin ölçüldüğü veri tablosu"),
        V("common", "Hava direnci ihmal EDİLMEYEN durumla karşılaştırma (yaprak kâğıt / buruşturulmuş kâğıt)")],
       [D("Ağır cisim daha büyük ivmeyle düşer / önce yere ulaşır", "Ağırlık arttıkça serbest düşme ivmesi artar (Aristotelesçi yanılgı)"),
        D("Hafif cisim hava direnci yokken de daha yavaş düşer", "Hava direnci ile kütle etkisini karıştırma"),
        D("Kütle iki katına çıkınca düşme süresi yarıya iner", "İvmeyi kütleyle doğru orantılı sanma")],
       [E("İvmeyi kütleye bağlı sanmak", "CONCEPTUAL_ERROR"),
        E("'Hava direnci ihmal' koşulunu gözden kaçırmak", "QUESTION_INTERPRETATION_ERROR")],
       ["Kavramsal: serbest düşmede tek kuvvet ağırlık; a = G/m = g kütleden bağımsız"],
       {"range": ["kolay", "orta"], "drivers": ["Hava direncinin olduğu durumla karşılaştırma eklenirse orta"]},
       [("prog", "serbest düşen farklı kütleli cisimlere örnek olacak görselleri"), ("tb", 16, "1. Etkinlik", "Serbest Düşme")]),
    QF("ff-data-pattern-g", "Serbest düşme verisinden ivmenin bulunması",
       ["FİZ.11.1.1:a", "FİZ.11.1.1:b"], ["serbest-dusme", "yer-cekimi-ivmesi", "ivme", "hareket-grafikleri"], ["free-fall-v-v0zero"],
       ["TABLE", "GRAPH", "DATA_SET", "EXPERIMENT"],
       "Serbest düşen cismin eşit zaman aralıklarındaki hız (ya da konum) değerleri verilir; hız değişiminin sabit olduğu örüntüsünden ivme bulunur ya da genellenir.",
       ["t – ϑ tablosu ya da ϑ-t grafiği"], ["ivmenin büyüklüğü / sabit olup olmadığı / farklı gezegende g"],
       [V("table", "Saniyede bir ölçülen hız değerleri (0, 10, 20, 30 m/s ...)"),
        V("graph", "ϑ-t grafiğinin eğiminden g"),
        V("common", "Dünya ve Mars gibi farklı çekim ivmeli ortamlarda aynı deney (kitap ÖD-4)"),
        V("experimental", "Fotokapılı düzenekte ardışık geçiş süreleri")],
       [D("Hızlar arttığı için ivme de artıyor", "Hız ile ivmeyi karıştırma"),
        D("Konum farklarının sabit olduğunu varsayıp ivmeyi sıfır bulma", "Konum ve hız tablosunu karıştırma")],
       [E("ϑ-t yerine x-t grafiğinin eğimini ivme sanmak", "GRAPH_READING_ERROR"),
        E("Ardışık farklar yerine değerlerin kendisini kullanmak", "TABLE_READING_ERROR")],
       ["Ardışık hız farkı / zaman aralığı", "ϑ-t grafiğinin eğimi"],
       {"range": ["kolay", "orta"], "drivers": ["Konum verisinden ivmeye gitmek orta"]},
       [("tb", 122, "ÖD-4", "Mar"), ("prog", "Serbest düşme hareketi yapan cisimlerin ivmeleriyle ilgili genelleme yapar")],
       scope_note="Farklı gezegenler programda zenginleştirme önerisi; kitap ölçme sorusunda (ÖD-4) kullanıyor."),
    QF("ff-reaction-time-ruler", "Düşen cetvelle tepki süresinin ölçülmesi",
       ["FİZ.11.1.2:a", "FİZ.11.1.2:c"], ["serbest-dusme", "yer-cekimi-ivmesi"], ["free-fall-h-v0zero"],
       ["EXPERIMENT", "DAILY_LIFE_CONTEXT", "TABLE"],
       "Bir kişi cetveli bırakır, diğeri yakalar; cetvelin düştüğü uzunluktan tepki süresi (ya da tersi) bulunur.",
       ["yakalanan cetvel uzunluğu"], ["tepki süresi / karşılaştırma"],
       [V("experimental", "Farklı öğrencilerin yakalama mesafeleri tablosundan en hızlı tepkiyi bulma"),
        V("common", "Tepki süresi verilip cetvelin düştüğü uzunluğu bulma")],
       [D("Yakalama mesafesi iki katsa tepki süresi de iki kat", "h ∝ t² yerine h ∝ t sanma")],
       [E("h = ½gt² yerine h = g·t kullanmak", "FORMULA_SELECTION_ERROR"),
        E("cm'yi m'ye çevirmemek", "UNIT_ERROR")],
       ["h = ½gt² ile t = √(2h/g)"],
       {"range": ["kolay", "orta"], "drivers": ["Oran sorusu (√ ilişkisi) orta"]},
       [("tb", 120, "ÖD-1", "cetvel")]),

    # ======================= FİZ.11.1.2 =======================
    QF("ff-kinematics-v0zero", "İlk hızsız serbest düşmede hız-yükseklik-süre hesabı",
       ["FİZ.11.1.2:c"], ["serbest-dusme", "yer-cekimi-ivmesi"], ["free-fall-h-v0zero", "free-fall-v-v0zero", "free-fall-v2-v0zero"],
       ["TEXT", "DIAGRAM", "DAILY_LIFE_CONTEXT"],
       "Durgun bırakılan cismin yüksekliği, süresi ya da yere çarpma hızından ikisi bilinmeyen üçüncüsü sorulur.",
       ["h, t, ϑ'den biri ya da ikisi", "g"], ["kalan nicelik"],
       [V("common", "Belli bir yükseklikten düşen cismin son 1 saniyede aldığı yol"),
        V("common", "İki cismin farklı yüksekliklerden bırakılıp düşme sürelerinin oranı"),
        V("daily_life", "Kuyuya bırakılan taşın sesinin duyulma süresi (ses hızı ihmal ya da dahil)")],
       [D("Yükseklik iki katına çıkınca süre de iki kat", "h ∝ t² ilişkisini doğrusal sanma"),
        D("Son 1 saniyedeki yolu toplam yolun yarısı sanma", "Eşit sürelerde eşit yol alındığını sanma")],
       [E("ϑ² = 2gh'de karekök almayı unutmak", "ALGEBRA_ERROR"),
        E("½ katsayısını unutmak", "FORMULA_APPLICATION_ERROR")],
       ["Uygun zamansız/zamanlı bağıntı seçimi", "Oran-orantı (√ ilişkisi)"],
       {"range": ["kolay", "orta"], "drivers": ["Son saniye / oran soruları orta"]},
       [("tb", 29, "Kontrol Noktası", "Serbest"), ("tb", 24, "Örnek", "matematiksel")],
       shortcuts=["ardışık eşit sürelerde yollar 1:3:5:7"]),
    QF("ff-upward-throw", "Yukarı yönlü serbest düşme: tepe noktası, çıkış ve iniş",
       ["FİZ.11.1.2:c"], ["serbest-dusme", "tepe-noktasi-hareket", "maksimum-yukseklik"], ["free-fall-v-general", "free-fall-h-general", "free-fall-v2-general"],
       ["TEXT", "DIAGRAM", "DAILY_LIFE_CONTEXT"],
       "Yukarı ilk hızla fırlatılan cismin maksimum yüksekliği, çıkış süresi, havada kalma süresi ya da belirli bir andaki hızı sorulur.",
       ["ϑ₀", "g", "(varsa) atış yüksekliği"], ["h_max / t_çıkış / t_toplam / ϑ(t)"],
       [V("common", "Binanın çatısından yukarı atılan taşın yere çarpma süresi ve hızı (kitap 6. Alıştırma)"),
        V("daily_life", "Mezuniyet kepinin fırlatılması"),
        V("graph", "Hareketin ϑ-t grafiğinin aşağı yön negatif seçilerek çizimi")],
       [D("Tepe noktasında ivme sıfırdır", "Hız sıfır olunca ivmenin de sıfır olduğunu sanma"),
        D("İniş süresi çıkış süresinden uzundur (aynı seviyeye dönüşte)", "Simetriyi bilmeme"),
        D("Tepe noktasında cisim dengededir", "Anlık durmayı dengeyle karıştırma")],
       [E("Yönü değişince ivmenin işaretini de değiştirmek", "SIGN_ERROR"),
        E("Toplam süreyi tek denklemle bulurken kökün negatif/pozitif seçimini yanlış yapmak", "ALGEBRA_ERROR")],
       ["Tepe noktası koşulu (ϑ = 0)", "Tek denklemle işaretli çözüm", "Simetri"],
       {"range": ["orta", "zor"], "drivers": ["Yerden yüksekte atış ve toplam süre zor"]},
       [("tb", 28, "6. Alıştırma", "yukarı doğru"), ("prog", "ilk hızı sıfırdan farklı olan serbest düşen cisimlerin")],
       shortcuts=["simetri: aynı seviyeye çıkış ve iniş süreleri eşit", "h_max = ϑ₀²/2g"]),
    QF("ff-downward-throw-or-moving-carrier", "Aşağı ilk hızlı düşme ve hareketli taşıyıcıdan bırakma",
       ["FİZ.11.1.2:c"], ["serbest-dusme", "hiz"], ["free-fall-h-general", "free-fall-v-general"],
       ["TEXT", "DAILY_LIFE_CONTEXT"],
       "Cisim aşağı yönlü ilk hızla atılır ya da düşey hareket eden bir taşıyıcıdan (kuş, balon, asansör) bırakılır; ilk hız taşıyıcının hızıdır.",
       ["taşıyıcının hızı ve yönü", "yükseklik ya da süre"], ["yere ulaşma süresi / hızı / yükseklik"],
       [V("daily_life", "Dalışa geçen şahinin pençesinden düşen solucan (kitap ÖD-10)"),
        V("common", "Yukarı çıkan balondan bırakılan kum torbası (önce yükselir)")],
       [D("Bırakılan cismin ilk hızı sıfırdır", "Taşıyıcının hızını cisme aktarmama"),
        D("Yukarı çıkan balondan bırakılan cisim hemen aşağı düşer", "İlk hız yönünü yok sayma")],
       [E("İlk hızı sıfır almak", "CONCEPTUAL_ERROR"),
        E("İlk hızın yönünü işaretle göstermemek", "SIGN_ERROR")],
       ["İlk hızlı serbest düşme bağıntıları, yön seçimi"],
       {"range": ["orta", "zor"], "drivers": ["Yukarı hareket eden taşıyıcı zor"]},
       [("tb", 127, "ÖD-10", "şahin")]),
    QF("ff-passing-point-twice", "Aynı noktadan iki kez geçiş süreleri",
       ["FİZ.11.1.2:c"], ["serbest-dusme", "tepe-noktasi-hareket"], ["free-fall-h-general"],
       ["DIAGRAM", "DAILY_LIFE_CONTEXT"],
       "Yukarı atılan cismin belirli bir noktadan çıkarken ve inerken geçme anları verilir; ilk hız, tepe yüksekliği ya da noktalar arası uzaklık sorulur.",
       ["iki geçiş anı (t₁, t₂)"], ["ilk hız / tepe yüksekliği / nokta yüksekliği"],
       [V("daily_life", "Fırlatılan kepin L noktasından iki kez geçmesi (kitap ÖD-2)"),
        V("common", "İki farklı noktadan geçiş süreleri farkı")],
       [D("Tepeye çıkış süresi t₂ − t₁ kadardır", "Simetri ortasını yanlış bulma (doğrusu (t₁+t₂)/2)")],
       [E("Simetri merkezini yanlış belirlemek", "METHOD_SELECTION_ERROR")],
       ["Simetri: tepeye çıkış süresi (t₁+t₂)/2", "h = ½g·t₁·t₂ ilişkisi"],
       {"range": ["zor", "AYT-üstü"], "drivers": ["İki bilinmeyenli simetri kurgusu"]},
       [("tb", 120, "ÖD-2", "kep")],
       shortcuts=["tepe süresi = (t₁+t₂)/2"]),
    QF("ff-equal-interval-ratios", "Ardışık eşit zaman aralıklarında alınan yolların oranı",
       ["FİZ.11.1.2:b", "FİZ.11.1.2:c"], ["serbest-dusme"], ["free-fall-h-v0zero"],
       ["DIAGRAM", "TABLE", "DAILY_LIFE_CONTEXT"],
       "Durgun bırakılan cismin ardışık eşit sürelerde aldığı yollar (h, 3h, 5h, 7h ...) üzerinden yükseklik ya da süre sorulur.",
       ["yükseklik oranları ya da aralık sayısı"], ["toplam süre / yükseklik / yolların oranı"],
       [V("daily_life", "Farklı yükseklikteki platformlardan atlayan kule atlama sporcuları (kitap ÖD-3)"),
        V("common", "Damlayan musluktan eşit aralıklarla düşen damlaların aralıkları")],
       [D("Eşit sürelerde eşit yollar alınır", "Sabit hızlı hareket sanma"),
        D("Yollar 1:2:3:4 oranında artar", "Toplam yol ile aralık yolunu karıştırma")],
       [E("Toplam yolu (1:4:9) aralık yolu (1:3:5) sanmak", "CONCEPTUAL_ERROR")],
       ["Tek sayılar kuralı", "h ∝ t²"],
       {"range": ["orta", "zor"], "drivers": []},
       [("tb", 29, "Kontrol Noktası", "Serbest"), ("tb", 121, "ÖD-3", "Önder")],
       shortcuts=["ardışık eşit sürelerde yollar 1:3:5:7"]),
    QF("ff-motion-graphs", "Serbest düşmenin konum-hız-ivme grafikleri",
       ["FİZ.11.1.2:b", "FİZ.11.1.2:c"], ["serbest-dusme", "hareket-grafikleri", "grafik-egim-alan"], [],
       ["GRAPH"],
       "Serbest düşen (ya da yukarı atılan) cismin x-t, ϑ-t, a-t grafiklerinden biri verilir ya da çizilmesi istenir; grafikler arası dönüşüm yapılır.",
       ["hareket tarifi ya da bir grafik", "pozitif yön seçimi"], ["doğru grafik / grafikten nicelik"],
       [V("graph", "Yukarı atılıp yere düşen cismin ϑ-t grafiği (yön seçimine göre)"),
        V("graph", "ϑ-t grafiği altındaki alandan yükseklik"),
        V("graph", "Yere çarpıp sekme içeren ϑ-t grafiği (kitap 7. Alıştırma)")],
       [D("a-t grafiğinde tepe noktasında ivme sıfıra iner", "Tepe noktasında ivmenin sıfır olduğunu sanma"),
        D("Yukarı atışın ϑ-t grafiği tepe noktasında kırılır", "İvmenin yön değiştirdiğini sanma"),
        D("x-t grafiği doğrusal çizilir", "Sabit hızlı hareketle karıştırma")],
       [E("Pozitif yön seçimini grafik boyunca tutarlı uygulamamak", "SIGN_ERROR"),
        E("Grafik eğimi ile grafik değerini karıştırmak", "GRAPH_READING_ERROR")],
       ["Eğim ve alan yorumu", "Tutarlı yön seçimi"],
       {"range": ["orta", "zor"], "drivers": ["Sekme ve yön değişimi zor"]},
       [("prog", "hız-zaman, ivme-zaman ve konum-zaman grafiklerini çizer"), ("tb", 122, "ÖD-3e", "Hız-z")]),
    QF("ff-data-evidence", "Serbest düşme veri setinden kanıta dayalı açıklama",
       ["FİZ.11.1.2:a", "FİZ.11.1.2:b", "FİZ.11.1.2:c"], ["serbest-dusme", "hareket-grafikleri"], ["free-fall-h-v0zero"],
       ["TABLE", "EXPERIMENT", "DATA_SET"],
       "Bir deneyin (fotokapı, video analizi, sensör) zaman-konum ya da zaman-hız verisi verilir; hangi verinin hangi sonucu desteklediği, eksik verinin ne olması gerektiği ya da hatalı ölçüm sorulur.",
       ["ölçüm tablosu"], ["veriye dayalı yargı / eksik değer / hatalı ölçüm"],
       [V("table", "Bir değeri hatalı girilmiş ölçüm tablosunda hatayı bulma"),
        V("experimental", "Video karelerinden konum ölçümü")],
       [D("Konumlar eşit arttığı için hareket sabit hızlıdır", "Konum farklarını incelemeden yargıya varma")],
       [E("Tabloda konum ile yer değiştirmeyi karıştırmak", "TABLE_READING_ERROR")],
       ["Ardışık farklar ve ikinci farklar", "Grafiğe dökme"],
       {"range": ["orta"], "drivers": []},
       [("tb", 21, "2. Etkinlik", "Veri"), ("prog", "Serbest düşme hareketi ile ilgili verileri toplayarak kaydeder"), ("kil", 114)]),

    # ======================= FİZ.11.1.3 =======================
    QF("2d-horizontal-launch", "Yatay ilk hızla iki boyutlu hareket (eski adı: yatay atış)",
       ["FİZ.11.1.3:a"], ["iki-boyutta-sabit-ivmeli-hareket", "bilesenlerin-bagimsizligi", "menzil", "ucus-suresi"],
       ["2d-horizontal-range", "free-fall-h-v0zero"], ["DIAGRAM", "DAILY_LIFE_CONTEXT"],
       "Belli yükseklikten yatay hızla fırlatılan cismin uçuş süresi, menzili ya da çarpma hızı sorulur; süre düşey hareketten bulunur.",
       ["yükseklik", "yatay hız"], ["t_uçuş / menzil / çarpma hızı"],
       [V("daily_life", "Masa tenisinde servis (kitap ÖD-5)"), V("daily_life", "Yapay şelaleden akan su (kitap ÖD-6)"),
        V("common", "Aynı yükseklikten farklı yatay hızlarla atılan cisimlerin düşme sürelerini karşılaştırma"),
        V("common", "Aynı anda yatay atılan ve serbest bırakılan cisimlerin yere ulaşma sırası")],
       [D("Yatay hızı büyük olan cisim daha geç yere düşer", "Bileşenlerin bağımsızlığını bilmeme"),
        D("Çarpma hızı yalnız düşey hızdır", "Yatay bileşeni unutma")],
       [E("Uçuş süresini yatay hareketten bulmaya çalışmak", "METHOD_SELECTION_ERROR"),
        E("Çarpma hızında bileşenleri skaler toplamak", "VECTOR_ERROR")],
       ["Bileşenlere ayırma: düşeyde serbest düşme, yatayda sabit hız"],
       {"range": ["kolay", "orta"], "drivers": ["Çarpma hızı ve açısı orta"]},
       [("tb", 123, "ÖD-5", "masa"), ("tb", 124, "ÖD-6", "şelale"), ("prog", "yalnızca yer çekimi ivmesi etkisi altında iki boyutta")]),
    QF("2d-angled-launch", "Yatayla açılı ilk hızla iki boyutlu hareket (eski adı: eğik atış)",
       ["FİZ.11.1.3:a", "FİZ.11.1.3:b"], ["iki-boyutta-sabit-ivmeli-hareket", "vektor-bilesenleri", "maksimum-yukseklik", "menzil", "trigonometrik-oranlar"],
       ["2d-velocity-components", "2d-vertical-up-phase", "2d-horizontal-range"], ["DIAGRAM", "DAILY_LIFE_CONTEXT", "TEXT"],
       "Yatayla α açısıyla atılan cismin tepe yüksekliği, uçuş süresi, menzili ya da tepe noktasındaki hızı sorulur.",
       ["ϑ₀", "α (özel açılar: 37°, 53°, 30°, 45°, 60°)"], ["h_max / t_uçuş / menzil / tepe hızı"],
       [V("daily_life", "Gösteri alanında farklı açılarla top atışı (kitap ÖD-8)"),
        V("daily_life", "Yanardağdan fırlayan kaya (kitap ÖD-13)"),
        V("common", "Yerden yüksek bir noktadan açılı atış"),
        V("graph", "Yatay ve düşey bileşenlerin ayrı x-t, ϑ-t, a-t grafikleri")],
       [D("Tepe noktasında hız sıfırdır", "Yatay bileşeni unutma"),
        D("Tepe noktasında ivme sıfırdır", "İvmeyi hıza bağlı sanma"),
        D("sin ve cos'un yeri değişmiş seçenek", "Açının hangi eksenle ölçüldüğüne bakmama")],
       [E("Bileşenlerde sin/cos'u karıştırmak", "VECTOR_ERROR"),
        E("Menzili ϑ₀·t ile hesaplamak", "FORMULA_APPLICATION_ERROR")],
       ["Bileşenlere ayırma", "Tepe noktası koşulu (ϑᵧ = 0)", "Simetri"],
       {"range": ["orta", "zor"], "drivers": ["Yerden yüksek atış ve özel olmayan açı zor"]},
       [("tb", 125, "ÖD-8", "Atış"), ("tb", 130, "ÖD-13", "kaya"), ("tb", 39, "Kontrol Noktası", "menzil")],
       shortcuts=["tümler açılarda menziller eşit", "45°'de menzil en büyük (aynı seviyeye dönüşte)"]),
    QF("2d-velocity-at-point", "İki boyutlu harekette bir noktadaki hız vektörü",
       ["FİZ.11.1.3:a"], ["iki-boyutta-sabit-ivmeli-hareket", "vektor-bilesenleri", "cizgisel-hiz"],
       ["2d-velocity-components", "2d-vertical-up-phase"], ["DIAGRAM", "TEXT"],
       "Hareketin bir anındaki hızın büyüklüğü ya da yatayla yaptığı açı sorulur (bileşenlerin vektörel toplamı).",
       ["ϑ₀, α, t ya da konum"], ["hızın büyüklüğü / yönü"],
       [V("common", "Balkondan 45° ile atılan anahtarın hız bileşenleri ve bileşke hızı (kitap ÖD-14d)"),
        V("common", "Hız vektörünün yatayla 45° yaptığı an")],
       [D("Bileşke hız, bileşenlerin toplamıdır", "Vektörleri skaler toplama")],
       [E("Pisagor yerine düz toplama", "VECTOR_ERROR")],
       ["Bileşenleri bulup Pisagor / tanjant"],
       {"range": ["orta"], "drivers": []},
       [("tb", 133, "ÖD-14d", "bileşenlerinin")]),
    QF("2d-component-data", "İki boyutlu hareketin bileşenlerinin veriden ayrıştırılması",
       ["FİZ.11.1.3:a"], ["iki-boyutta-sabit-ivmeli-hareket", "bilesenlerin-bagimsizligi", "sabit-hizli-hareket", "sabit-ivmeli-hareket"],
       ["2d-horizontal-range", "free-fall-h-v0zero"], ["TABLE", "EXPERIMENT", "DATA_SET"],
       "Video ya da stroboskopik fotoğraftan alınan x(t), y(t) verilerinden yatay bileşenin sabit hızlı, düşey bileşenin sabit ivmeli olduğu örüntüsü bulunur; eksik değer ya da ivme sorulur.",
       ["eşit aralıklı x ve y konum tablosu"], ["bileşenlerin hareket türü / g / eksik konum"],
       [V("table", "Eşit zaman aralıklarında x değerlerinin eşit, y farklarının düzgün arttığı tablo"),
        V("experimental", "Stroboskopik fotoğrafta topun ardışık konumları")],
       [D("Yatay konum farkları da artar", "Yatayda ivme olduğunu sanma"),
        D("Düşey konum farkları eşittir", "Düşeyde sabit hız sanma")],
       [E("Konum değerlerini fark almadan yorumlamak", "TABLE_READING_ERROR")],
       ["Bileşen başına ardışık farklar"],
       {"range": ["orta"], "drivers": []},
       [("prog", "hareket bileşenlerini eksenlere göre sabit hızlı ve sabit ivmeli hareket ile ilişkilendirir")]),
    QF("2d-launch-onto-incline-or-steps", "Eğik düzlem ya da basamaklara düşen iki boyutlu hareket",
       ["FİZ.11.1.3:b"], ["iki-boyutta-sabit-ivmeli-hareket", "bilesenlerin-bagimsizligi", "trigonometrik-oranlar"],
       ["2d-horizontal-range", "free-fall-h-v0zero"], ["DIAGRAM"],
       "Cisim bir eğik düzlemden ya da basamaklardan atılır; hangi basamağa düşeceği ya da eğik düzlemin neresine çarpacağı sorulur.",
       ["ilk hız", "eğim açısı ya da basamak ölçüleri"], ["çarpma noktası / süre"],
       [V("common", "Eğik düzlemin tepesinden yatay atılan topun düzleme çarptığı nokta (kitap ÖD-11)")],
       [D("Cisim ilk basamağa düşer", "Yatay ve düşey yer değiştirme ilişkisini kurmama")],
       [E("Yatay ve düşey yer değiştirmeyi aynı denkleme yanlış bağlamak", "METHOD_SELECTION_ERROR")],
       ["tanθ = düşey/yatay yer değiştirme koşulu"],
       {"range": ["zor", "AYT-üstü"], "drivers": ["Geometrik koşul kurulması"]},
       [("tb", 128, "ÖD-11", "basamak")]),
    QF("2d-component-graphs", "İki boyutlu hareketin bileşen grafikleri",
       ["FİZ.11.1.3:a", "FİZ.11.1.3:b"], ["iki-boyutta-sabit-ivmeli-hareket", "hareket-grafikleri", "bilesenlerin-bagimsizligi"], [],
       ["GRAPH"],
       "Hareketin yatay ve düşey bileşenleri için x-t, ϑ-t, a-t grafiklerinden doğru olanlar seçilir ya da çizilir.",
       ["hareket tarifi"], ["bileşen grafikleri"],
       [V("graph", "Yatay ϑₓ-t grafiğinin sabit, düşey ϑᵧ-t grafiğinin eğimi −g doğru olduğunu seçme")],
       [D("Yatay ϑ-t grafiği azalan doğru", "Yatayda da ivme olduğunu sanma")],
       [E("Yatay ve düşey grafikleri karıştırmak", "GRAPH_READING_ERROR")],
       ["Bileşen bazlı grafik analizi"],
       {"range": ["orta"], "drivers": []},
       [("tb", 129, "ÖD-11e", "grafiklerini"), ("prog", "matematiksel hesaplamalar ve grafiklere dayalı yorumlar")]),
    QF("2d-moving-reference-launch", "Hareketli referanstan açılı atış",
       ["FİZ.11.1.3:b"], ["iki-boyutta-sabit-ivmeli-hareket", "vektor-bilesenleri"], ["2d-horizontal-range"],
       ["DIAGRAM", "TEXT"],
       "Hareket eden araç ya da kişi tarafından atılan cismin yere göre hareketi sorulur.",
       ["taşıyıcı hızı", "atış hızı ve açısı"], ["yere göre menzil / yörünge"],
       [V("common", "Hareketli kamyonetten dik yukarı atılan top (yere göre iki boyutlu)")],
       [D("Top atıldığı noktanın gerisine düşer", "Taşıyıcı hızının cisme aktarıldığını bilmeme")],
       [E("Yere göre ve taşıyıcıya göre hızları karıştırmak", "CONCEPTUAL_ERROR")],
       ["Hızları vektörel toplayıp iki boyutlu hareket"],
       {"range": ["zor", "AYT-üstü"], "drivers": ["Bağıl hız"]},
       [("prog", "Öğrenciler, yalnızca yer çekimi ivmesi etkisi altında")],
       scope="ENRICHMENT", scope_note="Programda zenginleştirme önerisi ('Hareketli referanslardan farklı açılarla atılan cisimler'); temel kapsam dışı."),

    # ======================= FİZ.11.1.4 =======================
    QF("newton1-inertia", "Eylemsizlik durumlarının yorumlanması",
       ["FİZ.11.1.4:a", "FİZ.11.1.4:b"], ["eylemsizlik", "newton-birinci-yasa", "bileske-kuvvet"], [],
       ["DAILY_LIFE_CONTEXT", "TEXT"],
       "Günlük bir durumda (fren yapan otobüs, emniyet kemeri, masa örtüsü çekme) cisimlerin davranışı eylemsizlikle açıklanır.",
       ["günlük durum"], ["açıklama / doğru ifade"],
       [V("daily_life", "Aniden fren yapan otobüste yolcuların öne savrulması"),
        V("daily_life", "Sabit hızla giden araçta ivmesiz hâl (bileşke kuvvet sıfır)")],
       [D("Hareket eden cismin hareketini sürdürmesi için kuvvet gerekir", "Hareket–kuvvet yanılgısı (impetus)"),
        D("Yolcuyu öne iten bir kuvvet vardır", "Eylemsizliği kuvvet sanma")],
       [E("Sabit hızlı harekette bileşke kuvveti sıfırdan farklı sanmak", "CONCEPTUAL_ERROR")],
       ["Kavramsal: F_net = 0 ⇔ sabit hız"],
       {"range": ["kolay"], "drivers": []},
       [("tb", 40, "4. Etkinlik", "Kuvvet"), ("prog", "Bileşke kuvvet ile cisimlerin hareketi arasındaki ilişkiler")]),
    QF("newton2-f-m-a-relations", "Kuvvet–kütle–ivme ilişkisi (tablo ve grafik)",
       ["FİZ.11.1.4:a", "FİZ.11.1.4:b"], ["newton-ikinci-yasa", "bileske-kuvvet", "kutle", "ivme"], ["newton-second-law"],
       ["TABLE", "GRAPH", "EXPERIMENT"],
       "Farklı kuvvet ve kütleler için ölçülen ivme değerlerinden ilişki kurulur, eksik değer bulunur ya da F-a / a-m grafiği yorumlanır.",
       ["F, m, a tablosu ya da grafiği"], ["ilişki / eksik değer / grafik türü"],
       [V("table", "Sürtünmeli ve sürtünmesiz ortamda uygulanan kuvvetler ve ivmeler (kitap ÖD-15)"),
        V("graph", "F-a grafiğinin eğiminin kütle olduğunu yorumlama"),
        V("graph", "a-1/m grafiği")],
       [D("Kütle iki katına çıkınca ivme de iki kat olur", "Ters orantıyı doğru orantı sanma"),
        D("Sürtünmeli ortamda F-a grafiği orijinden geçer", "Sürtünmenin eşik etkisini bilmeme")],
       [E("Uygulanan kuvveti bileşke kuvvet sanmak", "CONCEPTUAL_ERROR"),
        E("Grafik eğiminin fiziksel anlamını yanlış okumak", "GRAPH_READING_ERROR")],
       ["F_net = m·a ile oran", "Grafik eğimi"],
       {"range": ["kolay", "orta"], "drivers": ["Sürtünme eklenirse orta"]},
       [("tb", 134, "ÖD-15", "kuvvet değerleri"), ("tb", 43, "Etkinlik", "matematiksel model")]),
    QF("newton3-action-reaction", "Etki-tepki kuvvet çiftlerinin belirlenmesi",
       ["FİZ.11.1.4:a", "FİZ.11.1.4:b"], ["etki-tepki", "kuvvet", "normal-kuvvet"], [],
       ["DIAGRAM", "DAILY_LIFE_CONTEXT"],
       "Etkileşen cisimlerde hangi kuvvetlerin etki-tepki çifti olduğu, büyüklükleri ve neden birbirini dengelemedikleri sorulur.",
       ["etkileşim durumu"], ["kuvvet çifti / karşılaştırma"],
       [V("daily_life", "Balondan çıkan havanın balonu itmesi (kitap 17. Alıştırma)"),
        V("daily_life", "Kamyon ile otomobilin çarpışmasında kuvvetler"),
        V("common", "Masadaki kitapta ağırlık–normal kuvvet ile etki-tepki çiftlerinin ayırt edilmesi")],
       [D("Ağırlık ve normal kuvvet etki-tepki çiftidir", "Dengeleyen kuvvetlerle etki-tepkiyi karıştırma"),
        D("Büyük kütleli cisim daha büyük kuvvet uygular", "Etki-tepkinin eşitliğini bilmeme"),
        D("Etki-tepki kuvvetleri birbirini dengeler", "Farklı cisimlere etki ettiğini gözden kaçırma")],
       [E("Kuvvetin hangi cisme etki ettiğini belirtmemek", "CONCEPTUAL_ERROR")],
       ["'A'nın B'ye uyguladığı kuvvet' dili ile çift eşleme"],
       {"range": ["kolay", "orta"], "drivers": []},
       [("tb", 50, "17. Alıştırma", "Balon")]),
    QF("net-force-motion-state", "Bileşke kuvvet ile hareket durumunun ilişkisi",
       ["FİZ.11.1.4:a"], ["bileske-kuvvet", "newton-ikinci-yasa", "hiz", "ivme"], ["newton-second-law"],
       ["DIAGRAM", "TABLE"],
       "İlk hız ve kuvvet vektörleri verilen cisimlerin hızlanıp yavaşlayacağı ya da yön değiştireceği belirlenir.",
       ["ilk hız ve kuvvet vektörleri"], ["hareket türü"],
       [V("table", "Tahta blokların ilk hız ve kuvvet vektörlerine göre hareket tablosu (kitap ÖD-26)")],
       [D("Cisim her zaman kuvvet yönünde hareket eder", "Hız yönünü ivme yönüyle karıştırma")],
       [E("Kuvvet ile hız yönünü özdeşleştirmek", "CONCEPTUAL_ERROR")],
       ["İvme yönü = bileşke kuvvet yönü; hızla aynı yönse hızlanır, zıtsa yavaşlar"],
       {"range": ["kolay", "orta"], "drivers": []},
       [("tb", 140, "ÖD-26", "tahta")]),

    # ======================= FİZ.11.1.5 =======================
    QF("fbd-identify-forces", "Serbest cisim diyagramı çizme / doğru diyagramı seçme",
       ["FİZ.11.1.5:a", "FİZ.11.1.5:b"], ["serbest-cisim-diyagrami", "agirlik", "normal-kuvvet", "gerilme-kuvveti", "surtunme-kuvveti"], [],
       ["DIAGRAM", "DAILY_LIFE_CONTEXT"],
       "Bir ya da birkaç cisme etki eden tüm kuvvetler belirlenip vektörlerle gösterilir; doğru diyagram seçilir.",
       ["durum görseli"], ["kuvvetlerin listesi / doğru diyagram"],
       [V("daily_life", "Görsellerdeki cisimler (asılı lamba, kayan kutu, iple çekilen kızak)"),
        V("common", "Diyagrama 'hareket yönünde kuvvet' ya da 'merkezcil kuvvet' eklenmiş hatalı seçenekler")],
       [D("Hareket yönünde ayrı bir 'hareket kuvveti' oku", "Hareket–kuvvet yanılgısı"),
        D("Merkezcil kuvvet ayrı bir kuvvet olarak çizilmiş", "Merkezcil kuvveti ayrı kuvvet sanma"),
        D("Cismin başka cisme uyguladığı kuvvet diyagrama eklenmiş", "Kuvvetin hangi cisme etki ettiğini karıştırma")],
       [E("Diyagrama tepki kuvvetlerini ekleyerek çift sayım yapmak", "CONCEPTUAL_ERROR"),
        E("Kuvveti eksik çizmek (normal ya da sürtünme)", "CARELESS_ERROR")],
       ["Temas noktalarını tek tek tarama + uzaktan kuvvet (ağırlık)"],
       {"range": ["kolay", "orta"], "drivers": []},
       [("tb", 53, "5. Etkinlik", "Serbest Cisim"), ("prog", "Bir cisme etki eden kuvvetleri belirler")]),
    QF("fbd-equilibrium-tension", "Dengedeki asılı sistemlerde ip gerilmeleri",
       ["FİZ.11.1.5:b", "FİZ.11.1.5:c"], ["serbest-cisim-diyagrami", "gerilme-kuvveti", "vektor-bilesenleri", "newton-birinci-yasa"], ["weight"],
       ["DIAGRAM"],
       "İplerle asılı, dengedeki cisimlerde ip gerilmeleri ya da kuvvetölçer değerleri bulunur.",
       ["kütleler", "ip açıları"], ["gerilme / kuvvetölçer değeri"],
       [V("common", "30° açılı iplerle asılı cisimlerde kuvvetölçer okumaları (kitap ÖD-27)"),
        V("common", "Makaradan geçen ipin iki ucundaki eşit gerilme")],
       [D("Kuvvetölçer iki ucundaki ağırlıkların toplamını gösterir", "İpin her yerindeki gerilmenin aynı olduğunu bilmeme")],
       [E("Bileşenlere ayırmada sin/cos karıştırmak", "VECTOR_ERROR")],
       ["Bileşke kuvvet = 0, bileşen denklemleri"],
       {"range": ["orta", "zor"], "drivers": ["Çok ipli sistemler zor"]},
       [("tb", 141, "ÖD-27", "kuvvetölçer")],
       scope_note="Kuvvet dengesi; tork içermeyen (noktasal cisim) dengeyle sınırlı. Tork 12. sınıf."),
    QF("frictionless-incline", "Sürtünmesiz eğik düzlemde hareket",
       ["FİZ.11.1.5:c"], ["egik-duzlem", "vektor-bilesenleri", "serbest-cisim-diyagrami", "newton-ikinci-yasa"], ["frictionless-incline", "newton-second-law"],
       ["DIAGRAM"],
       "Sürtünmesiz eğik düzlemde serbest bırakılan ya da itilen cismin ivmesi, normal kuvveti ya da hızı sorulur.",
       ["eğim açısı", "kütle", "ek kuvvet"], ["ivme / normal kuvvet / süre"],
       [V("common", "Eğim açısı değişince ivmenin değişimi"),
        V("common", "Farklı eğimli iki düzlemde aynı yükseklikten kayan cisimler")],
       [D("Normal kuvvet ağırlığa eşittir", "Eğik düzlemde N = mg cosθ olduğunu bilmeme"),
        D("Ağır cisim daha büyük ivmeyle kayar", "İvmenin kütleden bağımsızlığını bilmeme")],
       [E("sin ile cos'u karıştırmak", "VECTOR_ERROR")],
       ["Eğime paralel–dik bileşenler"],
       {"range": ["orta"], "drivers": []},
       [("tb", 60, "Örnek", "sin")]),
    QF("connected-bodies-same-acceleration", "Aynı ivmeli bağlı cisimler (ip-makara, birlikte itilen bloklar)",
       ["FİZ.11.1.5:b", "FİZ.11.1.5:c"], ["bagli-cisim-sistemi", "gerilme-kuvveti", "newton-ikinci-yasa", "serbest-cisim-diyagrami"],
       ["system-acceleration", "newton-second-law"], ["DIAGRAM", "EXPERIMENT"],
       "İple ya da temasla bağlı, aynı ivmeyle hareket eden cisimlerin ortak ivmesi ve ip gerilmesi/temas kuvveti sorulur.",
       ["kütleler", "dış kuvvetler", "(varsa) sürtünme"], ["sistem ivmesi / ip gerilmesi / temas kuvveti"],
       [V("experimental", "Makaradan geçen iple bağlı A ve B cisimleri (kitap ÖD-28)"),
        V("common", "Yatay masada çekilen, masadan sarkan cisimle bağlı blok"),
        V("common", "Arka arkaya itilen iki blokta temas kuvveti")],
       [D("İp gerilmesi asılı cismin ağırlığına eşittir", "Sistem ivmeli iken dengede gibi düşünme"),
        D("Temas kuvveti uygulanan kuvvete eşittir", "Kütle payını hesaba katmama")],
       [E("İç kuvveti (ip gerilmesi) dış kuvvet gibi toplamak", "CONCEPTUAL_ERROR"),
        E("Tek cisim denkleminde yanlış kütle kullanmak", "FORMULA_APPLICATION_ERROR")],
       ["Bütün sistem için F_net = m_top·a, sonra tek cisim"],
       {"range": ["orta", "zor"], "drivers": ["Sürtünme ve üç cisim zor"]},
       [("tb", 142, "ÖD-28", "makaradan"), ("tb", 61, "Örnek", "Hareket")],
       scope_note="Programa göre yalnız aynı ivmeli sistemler; farklı ivmeli (kayan üst blok, hareketli makara) sistem hesapları kapsam dışı."),
    QF("accelerating-frame-pendulum", "İvmeli araçta asılı cismin sapması",
       ["FİZ.11.1.5:c"], ["serbest-cisim-diyagrami", "gerilme-kuvveti", "newton-ikinci-yasa", "vektor-bilesenleri"],
       ["pendulum-in-accelerating-car"], ["DAILY_LIFE_CONTEXT", "DIAGRAM"],
       "Hızlanan/yavaşlayan araçta asılı cismin düşeyle yaptığı açı ile aracın ivmesi ilişkilendirilir.",
       ["açı ya da ivme"], ["ivme / açı / ip gerilmesi"],
       [V("daily_life", "Araç aynasına asılı araba kokusu (kitap s. 63)"), V("daily_life", "Vagon tavanına asılı cisim (kitap 25. Alıştırma)")],
       [D("Cisim ivme yönünde sapar", "Sapma yönünü yanlış belirleme"),
        D("Açı kütleye bağlıdır", "tanθ = a/g'de kütlenin sadeleştiğini görmeme")],
       [E("tanθ yerine sinθ kullanmak", "FORMULA_APPLICATION_ERROR")],
       ["Bileşen denklemlerinin oranı"],
       {"range": ["orta", "zor"], "drivers": []},
       [("tb", 63, "Örnek", "araba kokusu"), ("tb", 64, "25. Alıştırma", "vagon")]),
    QF("apparent-weight-elevator", "İvmeli sistemde görünür ağırlık (asansör, g-kuvveti)",
       ["FİZ.11.1.5:c"], ["normal-kuvvet", "agirlik", "newton-ikinci-yasa", "serbest-cisim-diyagrami"], ["newton-second-law", "weight"],
       ["DAILY_LIFE_CONTEXT", "TEXT", "GRAPH"],
       "İvmeli hareket eden asansörde tartının gösterdiği değer ya da pilotun hissettiği 'g-kuvveti' sorulur.",
       ["ivme büyüklüğü ve yönü", "kütle"], ["normal kuvvet / görünür ağırlık"],
       [V("daily_life", "Pilotlarda g-kuvveti (kitap ÖD-38)"), V("common", "Yukarı hızlanan / yavaşlayan asansörde tartı"),
        V("graph", "Asansörün ϑ-t grafiğinden her aralıkta tartı değerini bulma")],
       [D("Sabit hızla yukarı çıkan asansörde tartı daha büyük gösterir", "Hız ile ivmeyi karıştırma"),
        D("Tartı her zaman ağırlığı gösterir", "Tartının normal kuvveti ölçtüğünü bilmeme")],
       [E("İvme yönünü hareket yönü sanmak", "CONCEPTUAL_ERROR")],
       ["N − mg = m·a (yukarı pozitif)"],
       {"range": ["orta"], "drivers": []},
       [("tb", 148, "ÖD-38", "g k")]),

    # ======================= FİZ.11.1.6 =======================
    QF("friction-type-identification", "Sürtünme türünün belirlenmesi (statik / kinetik)",
       ["FİZ.11.1.6:a"], ["statik-surtunme", "kinetik-surtunme", "kayarak-oteleme", "donerek-oteleme"], [],
       ["DAILY_LIFE_CONTEXT", "DIAGRAM", "EXPERIMENT"],
       "Durgun ama harekete zorlanan, kayan ve kaymadan dönen cisimlerde sürtünmenin türü belirlenir.",
       ["durum"], ["sürtünme türü"],
       [V("daily_life", "Kaymadan dönen tekerlek (statik), kilitlenmiş tekerlekle kayan araç (kinetik)"),
        V("daily_life", "ABS fren sistemi (statik sürtünmenin kinetikten büyük olması) — zenginleştirme"),
        V("experimental", "Etkileşimli simülasyonda harekete zorlanan ve kayan cisimlerin gözlenmesi (kitap 6. Etkinlik)")],
       [D("Hareket eden her cisme kinetik sürtünme etki eder", "Dönerek ötelemede sürtünmenin statik olduğunu bilmeme")],
       [E("Hareketi kaymayla özdeşleştirmek", "CONCEPTUAL_ERROR")],
       ["Temas noktası yüzeye göre kayıyor mu?"],
       {"range": ["kolay", "orta"], "drivers": []},
       [("tb", 65, "6. Etkinlik", "Statik"), ("prog", "dönerek öteleme hareketi yapmakta olan cisimlere etki eden sürtünme")]),
    QF("friction-direction", "Sürtünme kuvvetinin yönü",
       ["FİZ.11.1.6:a"], ["surtunme-kuvveti", "statik-surtunme", "donerek-oteleme"], [],
       ["DAILY_LIFE_CONTEXT", "DIAGRAM"],
       "Yürüyen insan, hızlanan araç tekerleği, duvara bastırılan kitap, bant üzerindeki kutu gibi durumlarda sürtünmenin yönü sorulur.",
       ["durum"], ["sürtünme yönü"],
       [V("daily_life", "Yürürken ayağa etki eden sürtünmenin ileri yönlü olması"),
        V("daily_life", "Duvara bastırılan kitapta sürtünmenin yukarı yönlü olması (kitap ÖD-23)")],
       [D("Sürtünme her zaman hareket yönüne zıttır", "Sürtünmenin bağıl harekete/eğilime zıt olduğunu bilmeme")],
       [E("Hareket yönüne göre değil kayma eğilimine göre yön belirlememek", "CONCEPTUAL_ERROR")],
       ["Kayma eğiliminin yönünü bul, sürtünme ona zıt"],
       {"range": ["orta"], "drivers": []},
       [("tb", 138, "ÖD-23", "duvar")]),
    QF("static-vs-kinetic-compare", "Statik ve kinetik sürtünmenin karşılaştırılması",
       ["FİZ.11.1.6:b", "FİZ.11.1.6:c"], ["statik-surtunme", "kinetik-surtunme", "maksimum-statik-surtunme"], [],
       ["TEXT", "TABLE"],
       "Statik ve kinetik sürtünmenin benzer ve farklı özellikleri (bağlı oldukları değişkenler, büyüklük ilişkisi) yargılarla sorulur.",
       ["yargılar"], ["doğru yargılar"],
       [V("table", "Yapılandırılmış grid / doğru-yanlış tablosu")],
       [D("Statik sürtünme her zaman sabittir", "Statik sürtünmenin uygulanan kuvvetle değiştiğini bilmeme"),
        D("Kinetik sürtünme maksimum statikten büyüktür", "Büyüklük ilişkisini ters bilme")],
       [E("Maksimum statik ile anlık statik sürtünmeyi karıştırmak", "CONCEPTUAL_ERROR")],
       ["Özellik tablosu"],
       {"range": ["kolay"], "drivers": []},
       [("prog", "statik ve kinetik sürtünme kuvvetinin benzerliklerini ve farklılıklarını")]),

    # ======================= FİZ.11.1.7 =======================
    QF("friction-applied-force-graph", "Sürtünme kuvveti – uygulanan kuvvet grafiği",
       ["FİZ.11.1.7:a", "FİZ.11.1.7:b"], ["statik-surtunme", "kinetik-surtunme", "maksimum-statik-surtunme"], ["friction-model"],
       ["GRAPH"],
       "f–F grafiğinde statik bölge, harekete geçme eşiği ve kinetik bölge yorumlanır; katsayılar ya da cismin durumu sorulur.",
       ["f–F grafiği"], ["eşik değeri / katsayı / hareket durumu"],
       [V("graph", "Statik ve kinetik bölgeli grafik üzerinde A, B noktaları (kitap ÖD-25)")],
       [D("Statik bölgede sürtünme sabittir", "Grafiğin eğimli kısmını yanlış okuma"),
        D("Cisim harekete geçince sürtünme artar", "Kinetik değerin maksimum statikten küçük olduğunu bilmeme")],
       [E("Eşik noktası ile kinetik değeri karıştırmak", "GRAPH_READING_ERROR")],
       ["Bölge analizi; k = f/N"],
       {"range": ["kolay", "orta"], "drivers": []},
       [("tb", 139, "ÖD-25", "Statik bölge"), ("tb", 85, "Kontrol Noktası", "Kinetik bölge"), ("prog", "sürtünme kuvveti-uygulanan kuvvet grafiğini")]),
    QF("friction-threshold", "Uygulanan kuvvete göre hareket durumu ve sürtünmenin değeri",
       ["FİZ.11.1.7:b"], ["statik-surtunme", "kinetik-surtunme", "maksimum-statik-surtunme"], ["friction-model", "newton-second-law"],
       ["TABLE", "TEXT"],
       "Maksimum statik ve kinetik sürtünme değerleri bilinen cisme farklı kuvvetler uygulanır; her durumda sürtünmenin değeri ve ivme sorulur.",
       ["f_s,max, f_k", "uygulanan kuvvetler"], ["sürtünme değeri / ivme"],
       [V("table", "Kinetik 12 N, maksimum statik 16 N olan cisme farklı kuvvetler (kitap ÖD-22)")],
       [D("Cisim durgunken sürtünme her zaman maksimum statik değerdedir", "f_s = f_s,max sanma"),
        D("Uygulanan kuvvet kinetik değeri aşınca cisim harekete geçer", "Eşiğin maksimum statik olduğunu bilmeme")],
       [E("Durgun cisimde ivmeyi F − f_s,max ile hesaplayıp negatif bulmak", "CONCEPTUAL_ERROR")],
       ["Önce F ile f_s,max karşılaştır; F ≤ f_s,max ise f = F, değilse f = f_k"],
       {"range": ["orta"], "drivers": []},
       [("tb", 138, "ÖD-22", "statik sürtünme")],
       shortcuts=["önce eşik kontrolü"]),
    QF("friction-horizontal-dynamics", "Yatay zeminde sürtünmeli hareketin ivmesi",
       ["FİZ.11.1.7:b"], ["kinetik-surtunme", "newton-ikinci-yasa", "normal-kuvvet"], ["friction-model", "newton-second-law"],
       ["TEXT", "DIAGRAM", "DAILY_LIFE_CONTEXT"],
       "Yatay kuvvetle çekilen/itilen ya da ilk hızla kaymaya bırakılan cismin ivmesi, durma süresi veya yolu sorulur.",
       ["kütle", "kuvvet", "katsayı"], ["ivme / durma yolu"],
       [V("daily_life", "Kızak çeken kurt köpekleri (kitap ÖD-16)"),
        V("common", "İlk hızla buz üzerinde kayan disk")],
       [D("Cisim durana kadar sürtünme uygulanan kuvvete eşittir", "Kinetik sürtünmenin sabit olduğunu bilmeme")],
       [E("Normal kuvveti yanlış almak", "FORMULA_APPLICATION_ERROR")],
       ["F_net = F − k·N"],
       {"range": ["kolay", "orta"], "drivers": []},
       [("tb", 135, "ÖD-16", "kızak")]),
    QF("friction-angled-force", "Açılı kuvvetin normal kuvvete ve sürtünmeye etkisi",
       ["FİZ.11.1.7:b"], ["normal-kuvvet", "kinetik-surtunme", "vektor-bilesenleri"], ["friction-model", "2d-velocity-components"],
       ["DIAGRAM", "DAILY_LIFE_CONTEXT"],
       "Yatayla açı yapan kuvvetle çekilen/itilen cisimde normal kuvvet ve sürtünmenin değişimi sorulur.",
       ["kuvvet ve açısı", "kütle", "katsayı"], ["normal kuvvet / sürtünme / ivme"],
       [V("daily_life", "Eşya taşırken 37° açılı kuvvet uygulanan kutu (kitap ÖD-20)"),
        V("daily_life", "Çekici halatıyla 37° eğimli çekilen otomobil (kitap ÖD-17)"),
        V("common", "İtme ile çekmenin karşılaştırılması (hangisi daha kolay)")],
       [D("Normal kuvvet her durumda mg'dir", "Kuvvetin düşey bileşenini hesaba katmama")],
       [E("Düşey bileşeni normal kuvvete eklemek yerine çıkarmak (ya da tersi)", "SIGN_ERROR")],
       ["Kuvveti bileşenlerine ayır, N'yi düşey dengeden bul"],
       {"range": ["orta", "zor"], "drivers": []},
       [("tb", 137, "ÖD-20", "14 kg"), ("tb", 135, "ÖD-17", "halat")],
       scope_note="Program destekleme önerisinde ek düşey kuvvet olmayan örnekler önerir; çekirdek kapsam ve ders kitabı açılı kuvveti içerir."),
    QF("friction-incline-coefficient", "Eğik düzlemde sürtünme katsayısının deneyle bulunması",
       ["FİZ.11.1.7:a", "FİZ.11.1.7:b"], ["surtunme-katsayisi", "egik-duzlem", "statik-surtunme", "kinetik-surtunme"],
       ["kinetic-coefficient-incline", "friction-model"], ["EXPERIMENT", "DIAGRAM", "TABLE"],
       "Eğimi ayarlanabilen düzlemde cismin kaymaya başladığı ya da sabit hızla kaydığı açıdan katsayı bulunur; farklı yüzeyler karşılaştırılır.",
       ["kayma açısı", "yüzey türü"], ["katsayı / karşılaştırma"],
       [V("experimental", "Tahta ve fayans yüzeyli ayarlanabilir düzenekler (kitap ÖD-18)"),
        V("common", "Sabit hızla kayma açısından kinetik katsayı (kitap s. 82)")],
       [D("Katsayı cismin kütlesine bağlıdır", "k'nın yüzey çiftine bağlı olduğunu bilmeme"),
        D("Kaymaya başlama açısı kinetik katsayıyı verir", "Statik ve kinetik eşiklerini karıştırma")],
       [E("tanθ yerine sinθ almak", "FORMULA_APPLICATION_ERROR")],
       ["k = tanθ (eşik ya da sabit hız)"],
       {"range": ["orta", "zor"], "drivers": []},
       [("tb", 136, "ÖD-18", "eğimi"), ("tb", 82, "Örnek", "kinetik")]),
    QF("friction-wall-press", "Duvara bastırılarak dengede tutulan cisim",
       ["FİZ.11.1.7:b"], ["statik-surtunme", "normal-kuvvet", "maksimum-statik-surtunme"], ["friction-model"],
       ["DIAGRAM", "DAILY_LIFE_CONTEXT"],
       "Düşey duvara yatay kuvvetle bastırılan cismin düşmemesi için gereken en küçük kuvvet ya da sürtünmenin değeri sorulur.",
       ["kütle", "statik katsayı"], ["en küçük bastırma kuvveti / sürtünme"],
       [V("daily_life", "Kitabı duvara bastırarak tutmak (kitap ÖD-23, 34. Alıştırma)")],
       [D("Bastırma kuvveti artınca sürtünme de artar (cisim dengedeyken)", "Statik sürtünmenin ağırlığa eşit kaldığını görmeme")],
       [E("Normal kuvveti ağırlık sanmak", "CONCEPTUAL_ERROR")],
       ["k_s·F ≥ m·g"],
       {"range": ["orta"], "drivers": []},
       [("tb", 84, "Örnek", "duvar"), ("tb", 138, "ÖD-23", "Alper")]),
    QF("friction-stacked-blocks-together", "Üst üste konmuş blokların birlikte hareketi",
       ["FİZ.11.1.7:b"], ["statik-surtunme", "bagli-cisim-sistemi", "newton-ikinci-yasa"], ["friction-model", "system-acceleration"],
       ["DIAGRAM"],
       "Üst üste konmuş bloklardan birine kuvvet uygulanır; blokların birlikte hareket edebileceği en büyük kuvvet ya da üst bloğa etki eden sürtünme sorulur.",
       ["kütleler", "bloklar arası statik katsayı"], ["en büyük kuvvet / sürtünme"],
       [V("common", "1 kg ve 4 kg'lık üst üste bloklar, aralarında k_s = 0,6 (kitap ÖD-24)")],
       [D("Üst bloğa etki eden sürtünme her zaman maksimum değerdedir", "Statik sürtünmenin gerektiği kadar olduğunu bilmeme")],
       [E("Ortak ivmeyi bulmadan üst blok için sürtünmeyi hesaplamak", "METHOD_SELECTION_ERROR")],
       ["Önce ortak ivme, sonra üst blok için gerekli sürtünme ≤ k_s·N kontrolü"],
       {"range": ["zor"], "drivers": []},
       [("tb", 139, "ÖD-24", "üs t")],
       scope_note="Bloklar birlikte (aynı ivmeyle) hareket ettiği sürece kapsamda; kayma sonrası farklı ivmeli hesap kapsam dışı."),
    QF("friction-variables-data", "Sürtünmenin bağlı olduğu değişkenlerin veriden bulunması",
       ["FİZ.11.1.7:a"], ["surtunme-kuvveti", "surtunme-katsayisi", "normal-kuvvet"], ["friction-model"],
       ["TABLE", "EXPERIMENT"],
       "Farklı kütle, yüzey alanı ve yüzey türleriyle yapılan deney verilerinden sürtünmenin hangi değişkenlere bağlı olduğu çıkarılır.",
       ["deney tablosu"], ["bağlı olunan / olunmayan değişkenler"],
       [V("experimental", "Simülasyonla toplanan f, N verileri (kitap 7. Etkinlik)"),
        V("table", "Aynı bloğun farklı yüzleri üzerinde ölçülen sürtünme değerleri")],
       [D("Temas yüzey alanı büyüdükçe sürtünme artar", "Alan-sürtünme yanılgısı")],
       [E("Birden fazla değişkenin değiştiği satırları karşılaştırmak", "TABLE_READING_ERROR")],
       ["Kontrol değişkeni ilkesiyle satır karşılaştırma"],
       {"range": ["kolay", "orta"], "drivers": []},
       [("tb", 70, "7. Etkinlik", "Sürtünme"), ("kil", 85)]),

    # ======================= FİZ.11.1.8 =======================
    QF("terminal-velocity-graph", "Limit hıza ulaşan cismin hız-zaman grafiği",
       ["FİZ.11.1.8:c"], ["limit-hiz", "hava-direnci", "newton-birinci-yasa"], [],
       ["GRAPH", "DAILY_LIFE_CONTEXT"],
       "Paraşütçü ya da yağmur damlasının ϑ-t grafiği verilir; ivmenin değişimi, paraşütün açıldığı an ve kuvvetlerin büyüklük ilişkisi yorumlanır.",
       ["ϑ-t grafiği"], ["kuvvet ilişkisi / ivme değişimi"],
       [V("daily_life", "Paraşüt açıldıktan sonra yeni (küçük) limit hıza iniş"),
        V("daily_life", "Aynı uçaktan atlayan iki paraşütçünün karşılaştırması (kitap ÖD-39)")],
       [D("Paraşüt açılınca paraşütçü yukarı doğru hareket eder", "Hız azalmasını yön değişimi sanma"),
        D("Limit hızda ivme g'dir", "Net kuvvetin sıfır olduğunu görmeme"),
        D("Limit hıza ulaşınca hava direnci ağırlıktan büyüktür", "Dengeyi yanlış kurma")],
       [E("Grafiğin eğiminin azalmasını hızın azalması sanmak", "GRAPH_READING_ERROR")],
       ["Eğim = ivme; yatay bölge → F_net = 0"],
       {"range": ["orta"], "drivers": []},
       [("tb", 149, "ÖD-39", "paraşüt"), ("prog", "Profesyonel bir paraşütçünün uçaktan atlama deneyimine")]),
    QF("terminal-velocity-variables", "Limit hızı etkileyen değişkenlerin karşılaştırılması",
       ["FİZ.11.1.8:a", "FİZ.11.1.8:c"], ["limit-hiz", "kesit-alani", "kutle", "hava-direnci"], ["terminal-velocity", "drag-force"],
       ["DIAGRAM", "TABLE", "DAILY_LIFE_CONTEXT"],
       "Farklı kütle, boyut ve şekildeki cisimlerin limit hızları sıralanır ya da oranlanır.",
       ["kütle / kesit alanı / şekil"], ["sıralama / oran"],
       [V("common", "Eşit kütleli, farklı boyutlu K, L, M, N cisimlerinin limit hızları (kitap ÖD-31)"),
        V("daily_life", "Yatay ve buruşturulmuş özdeş kâğıtlar")],
       [D("Kütlesi büyük olanın limit hızı küçüktür", "Ağırlık arttıkça daha büyük direnç gerektiğini görmeme"),
        D("Limit hız yükseklikle artar", "Limit hızın yükseklikten bağımsız olduğunu bilmeme")],
       [E("ϑ ∝ √(m/A) yerine ϑ ∝ m/A almak", "FORMULA_APPLICATION_ERROR")],
       ["Kavramsal orantı; (kitapta) ϑ = √(mg/kA)"],
       {"range": ["orta", "zor"], "drivers": ["Sayısal oran istenirse zor"]},
       [("tb", 144, "ÖD-31", "limit hıza")],
       scope_note="Program: yorumlamalarla sınırlı (CALC_EXCLUDED). Ders kitabı oran içeren ölçme sorusu kullanıyor; sayısal oran program–kitap çelişkisi kapsamında."),
    QF("terminal-velocity-daily-life", "Limit hızın günlük hayat ve doğadaki örnekleri",
       ["FİZ.11.1.8:a", "FİZ.11.1.8:c"], ["limit-hiz", "hava-direnci"], [],
       ["DAILY_LIFE_CONTEXT", "TEXT"],
       "Yağmur damlası, karahindiba tohumu, tohum topu, bisikletçi gibi bağlamlarda limit hızın rolü ve değişkenleri yorumlanır.",
       ["bağlam metni"], ["doğru yorum"],
       [V("daily_life", "Karahindiba tohumlarının uzaklara taşınması (kitap ÖD-30)"),
        V("daily_life", "Helikopterden bırakılan tohum topları (kitap ÖD-33)"),
        V("daily_life", "Bisikletçinin hava direnci (kitap ÖD-40)")],
       [D("Hava direnci olmasaydı yağmur damlası yere aynı hızla ulaşırdı", "Limit hızın koruyucu rolünü görmeme")],
       [E("Bağlamdaki değişkeni (kesit alanı, şekil) fiziksel niceliğe bağlayamamak", "QUESTION_INTERPRETATION_ERROR")],
       ["Kavramsal değişken analizi"],
       {"range": ["kolay", "orta"], "drivers": []},
       [("tb", 143, "ÖD-30", "Karahindiba"), ("tb", 145, "ÖD-33", "tohum"), ("tb", 149, "ÖD-40", "Bisikle")]),
    QF("drag-variables-data", "Direnç kuvvetinin değişkenlerinin veri setinden çıkarılması",
       ["FİZ.11.1.8:b", "FİZ.11.1.8:c"], ["hava-direnci", "kesit-alani", "limit-hiz"], ["drag-force"],
       ["TABLE", "EXPERIMENT", "DATA_SET"],
       "Simülasyon ya da deneyden elde edilen kesit alanı–hız–direnç verilerinden ilişki kurulur.",
       ["veri tablosu"], ["ilişki / eksik değer"],
       [V("experimental", "Simülasyonda limit hız değişkenlerinin değiştirilmesi"),
        V("table", "Hız iki katına çıkınca direncin dört katına çıktığını tablodan bulma")],
       [D("Direnç hızla doğru orantılı artar", "Karesel ilişkiyi doğrusal sanma")],
       [E("Kontrol değişkenini sabit tutmadan karşılaştırma", "TABLE_READING_ERROR")],
       ["Veri tablosunda tek değişken karşılaştırması"],
       {"range": ["orta"], "drivers": []},
       [("prog", "limit hıza etki eden değişkenlerle ilgili veri toplamaya"), ("tb", 90, "Tablo 1.2", "Direnç"), ("kil", 115)],
       scope_note="Sayısal model yerine veri tablosu üzerinden orantı — kılavuzun 'veriden çıkarım' yaklaşımıyla programın hesap sınırına uygun."),

    # ======================= FİZ.11.1.9 =======================
    QF("circular-velocity-direction", "Düzgün çembersel harekette hız vektörünün yönü",
       ["FİZ.11.1.9:b", "FİZ.11.1.9:c"], ["cizgisel-hiz", "yaricap-vektoru", "duzgun-cembersel-hareket"], [],
       ["DIAGRAM"],
       "Çembersel yörüngenin farklı noktalarında hız vektörünün yönü ve yarıçap vektörüyle ilişkisi sorulur.",
       ["yörünge ve dönme yönü"], ["hız vektörü yönleri"],
       [V("common", "Saat yönünde dönen cismin dört noktadaki hız vektörleri"),
        V("common", "Hız vektörleri arasındaki açı ile taranan açının eşitliği")],
       [D("Hız vektörü merkeze doğrudur", "Hız ile ivme yönünü karıştırma"),
        D("Sürat sabit olduğundan hız da sabittir", "Hızın vektör olduğunu unutma")],
       [E("Dönme yönünü hesaba katmadan teğet yön çizmek", "VECTOR_ERROR")],
       ["Teğet ve yarıçapa dik"],
       {"range": ["kolay"], "drivers": []},
       [("tb", 95, "9. Etkinlik", "Düzgün Çembersel"), ("tb", 119, "Kontrol Noktası", "yarıçap vektörüne dik")]),
    QF("string-cut-trajectory", "İp koptuğunda cismin yörüngesi",
       ["FİZ.11.1.9:c"], ["cizgisel-hiz", "newton-birinci-yasa", "merkezcil-kuvvet"], [],
       ["DIAGRAM", "DAILY_LIFE_CONTEXT"],
       "Çembersel dönen cismin ipi (ya da bağlantısı) koptuğunda izleyeceği yol sorulur.",
       ["kopma noktası"], ["yörünge"],
       [V("common", "Yatay masada dönen cismin ipi koptuğunda (doğrusal, teğet)"),
        V("common", "Düşey düzlemde ip koptuğunda (iki boyutlu hareket — FİZ.11.1.3 ile birleşik; kitap 12. Alıştırma)")],
       [D("Cisim merkezden dışa doğru (radyal) uçar", "Merkezkaç kuvvet yanılgısı"),
        D("Cisim kopma anından sonra eğri yol izlemeye devam eder", "Eylemsizliği bilmeme")],
       [E("Merkezkaç kuvvetini gerçek kuvvet sanmak", "CONCEPTUAL_ERROR")],
       ["Kopma anındaki hız teğet; sonrası ağırlığa göre doğrusal ya da iki boyutlu hareket"],
       {"range": ["kolay", "orta"], "drivers": ["Düşey düzlemde kopma orta"]},
       [("tb", 108, "Alıştırma", "koptuğu"), ("tb", 38, "12. Alıştırma", "ipin ucunu")]),
    QF("circular-analogies", "Farklı düzgün çembersel hareketlerin ortak özellikleri",
       ["FİZ.11.1.9:a", "FİZ.11.1.9:b", "FİZ.11.1.9:c"], ["duzgun-cembersel-hareket", "cizgisel-hiz", "yaricap-vektoru"], [],
       ["DAILY_LIFE_CONTEXT", "TEXT"],
       "Uydu, dönme dolap, saat akrebi gibi farklı hareketlerin ortak özelliklerinden düzgün çembersel hareket hakkında genelleme yapılır.",
       ["örnek hareketler"], ["ortak özellik / doğru genelleme"],
       [V("daily_life", "Türksat uydusu ve dönme dolap karşılaştırması")],
       [D("Düzgün çembersel harekette ivme yoktur", "Sabit süratle ivmesizliği özdeşleştirme")],
       [E("Sürat ile hızı karıştırmak", "CONCEPTUAL_ERROR")],
       ["Analojik akıl yürütme: yörünge, merkez, hız yönü"],
       {"range": ["kolay"], "drivers": []},
       [("prog", "Türksat uydularının Dünya etrafındaki dolanımı")]),

    # ======================= FİZ.11.1.10 =======================
    QF("circular-kinematics", "Periyot, frekans, çizgisel ve açısal hız hesabı",
       ["FİZ.11.1.10:a", "FİZ.11.1.10:b"], ["periyot", "frekans", "cizgisel-surat", "acisal-hiz"],
       ["period-frequency", "linear-speed-circular", "angular-speed", "v-omega-r"], ["TEXT", "DAILY_LIFE_CONTEXT"],
       "Dönen sistemin periyot/frekansı ile çizgisel ve açısal hızları arasında hesap yapılır.",
       ["r, T ya da f"], ["ϑ, ω, T, f"],
       [V("daily_life", "Geostatik uydunun çizgisel ve açısal hızı (kitap s. 104)"),
        V("daily_life", "Saat ibreleri"), V("common", "Aynı diskin farklı yarıçaplı noktaları")],
       [D("Merkeze yakın noktanın açısal hızı daha küçüktür", "Aynı cisimde ω'nin aynı olduğunu bilmeme"),
        D("Frekans iki katına çıkınca periyot da iki kat olur", "Ters orantıyı bilmeme")],
       [E("Dakikadaki devri saniyeye çevirmemek", "UNIT_ERROR"), E("Çap ile yarıçapı karıştırmak", "CARELESS_ERROR")],
       ["ϑ = 2πr/T, ω = 2π/T, ϑ = ωr"],
       {"range": ["kolay"], "drivers": []},
       [("tb", 104, "Örnek", "geostatik")]),
    QF("coupled-wheels", "Kayış, dişli ya da ortak milli tekerleklerde hız ilişkisi",
       ["FİZ.11.1.10:b"], ["cizgisel-surat", "acisal-hiz", "periyot"], ["v-omega-r", "linear-speed-circular"],
       ["DIAGRAM", "DAILY_LIFE_CONTEXT"],
       "Kayışla ya da dişliyle bağlı (çizgisel süratler eşit) veya ortak mile bağlı (açısal hızlar eşit) tekerlerde frekans, periyot ya da hız oranı sorulur.",
       ["yarıçaplar", "bağlantı türü"], ["frekans / periyot / hız oranı"],
       [V("daily_life", "Tekerlekli sandalyenin büyük ve küçük tekerlekleri (kitap 39. Alıştırma)"),
        V("daily_life", "Bisiklet dişlisi ve zinciri")],
       [D("Kayışla bağlı tekerlerin açısal hızları eşittir", "Bağlantı türüne göre eşit niceliği karıştırma"),
        D("Büyük tekerleğin frekansı büyüktür", "f ∝ 1/r ilişkisini ters kurma")],
       [E("Eşit olan niceliği yanlış seçmek", "METHOD_SELECTION_ERROR")],
       ["Kayış/dişli: ϑ eşit; ortak mil: ω eşit"],
       {"range": ["orta"], "drivers": []},
       [("tb", 105, "39. Alıştırma", "tekerlek")],
       shortcuts=["kayış/temas: çizgisel sürat eşit; aynı mil: açısal hız eşit"]),
    QF("horizontal-circle", "Yatay düzlemde düzgün çembersel hareket (ip, yay, normal)",
       ["FİZ.11.1.10:a", "FİZ.11.1.10:b"], ["yatay-duzlemde-cembersel", "merkezcil-kuvvet", "merkezcil-ivme", "gerilme-kuvveti"],
       ["centripetal-acceleration", "centripetal-force"], ["DIAGRAM", "DAILY_LIFE_CONTEXT"],
       "Yatay sürtünmesiz düzlemde ipe/yaya bağlı dönen cismin merkezcil ivmesi, ip gerilmesi ya da hızı sorulur.",
       ["kütle", "yarıçap", "hız ya da periyot"], ["merkezcil ivme / gerilme / sürat"],
       [V("common", "Döner platformda yaya bağlı model araba (kitap s. 109)"),
        V("common", "Aynı ipe bağlı iki cisimde gerilmelerin oranı")],
       [D("İp gerilmesi ağırlığa eşittir", "Yatay düzlemde ağırlığın merkezcil kuvvete katılmadığını görmeme"),
        D("Yarıçap iki katına çıkınca (aynı hızda) kuvvet iki katına çıkar", "1/r ilişkisini bilmeme")],
       [E("ϑ ve ω ile yazılan bağıntılarda r'nin üssünü karıştırmak", "FORMULA_APPLICATION_ERROR")],
       ["F_m = mϑ²/r = mω²r"],
       {"range": ["kolay", "orta"], "drivers": []},
       [("tb", 108, "Yatay Düzlemde", "Yatay"), ("tb", 109, "Örnek", "400 g")]),
    QF("rotating-platform-friction", "Dönen platformda kaymadan durma",
       ["FİZ.11.1.10:b"], ["statik-surtunme", "merkezcil-kuvvet", "acisal-hiz"], ["centripetal-force", "friction-model"],
       ["DAILY_LIFE_CONTEXT", "DIAGRAM"],
       "Dönen platformdaki cismin kaymadan dönebileceği en büyük açısal hız ya da en uzak konum sorulur.",
       ["statik katsayı", "konum"], ["ω_max / r_max"],
       [V("daily_life", "Pikap üzerindeki telefon (kitap 41. Alıştırma)"),
        V("daily_life", "Atlıkarıncada merkeze yakın/uzak çocuklar")],
       [D("Cisim kütlesi büyükse daha erken kayar", "Kütlenin sadeleştiğini görmeme"),
        D("Merkeze yakın cisim önce kayar", "a = ω²r'de r etkisini ters kurma")],
       [E("Kinetik katsayıyı kullanmak", "CONCEPTUAL_ERROR")],
       ["k_s·m·g = m·ω²·r"],
       {"range": ["orta"], "drivers": []},
       [("tb", 109, "41. Alıştırma", "pikap")]),
    QF("vertical-circle-tension", "Düşey düzlemde çembersel harekette ip gerilmesi",
       ["FİZ.11.1.10:a", "FİZ.11.1.10:b"], ["dusey-duzlemde-cembersel", "gerilme-kuvveti", "agirlik", "merkezcil-kuvvet"],
       ["vertical-circle-forces", "centripetal-force"], ["DIAGRAM", "DAILY_LIFE_CONTEXT"],
       "İpe bağlı cismin tepe, dip ve yan noktalarında ip gerilmesi ya da ipin kopacağı nokta sorulur.",
       ["kütle", "yarıçap", "hız", "(varsa) ipin dayanma sınırı"], ["gerilmeler / kopma noktası"],
       [V("daily_life", "Çekiç atma (kitap 42. Alıştırma)"),
        V("common", "En büyük gerilmenin dipte olduğu, ipin dipte koptuğu durum")],
       [D("Tepe noktasında gerilme en büyüktür", "Ağırlığın tepede merkeze yönelik olduğunu yanlış yorumlama"),
        D("Tüm noktalarda gerilme eşittir", "Ağırlığın katkısını hesaba katmama")],
       [E("Tepede ağırlığın yönünü yanlış almak", "SIGN_ERROR")],
       ["Her noktada F_m = merkeze yönelik bileşke"],
       {"range": ["orta", "zor"], "drivers": ["Kopma ve ardından iki boyutlu hareket birleşik soru zor"]},
       [("tb", 110, "Tablo 1.3", "Merkezcil Kuvvet"), ("tb", 111, "42. Alıştırma", "çekiç")]),
    QF("vertical-circle-min-speed", "Düşey çemberin tepesinden geçebilme koşulu",
       ["FİZ.11.1.10:b"], ["dusey-duzlemde-cembersel", "merkezcil-kuvvet", "agirlik"], ["vertical-circle-min-speed"],
       ["DAILY_LIFE_CONTEXT", "DIAGRAM"],
       "Kovadaki suyun dökülmemesi ya da ipe bağlı cismin tepeden geçebilmesi için gereken en küçük hız sorulur.",
       ["yarıçap", "g"], ["ϑ_min / koşul"],
       [V("daily_life", "Su dolu kovanın döndürülmesi (kitap s. 110-111)")],
       [D("Su, merkezkaç kuvveti nedeniyle dökülmez", "Merkezkaç kuvvet yanılgısı"),
        D("En küçük hız kovadaki suyun kütlesine bağlıdır", "Kütlenin sadeleştiğini görmeme")],
       [E("Koşulu T = 0 yerine T = mg kurmak", "CONCEPTUAL_ERROR")],
       ["Tepede T = 0 → mg = mϑ²/r"],
       {"range": ["orta"], "drivers": []},
       [("tb", 111, "Cevap", "dökülmeden")],
       shortcuts=["ϑ_min = √(g·r)"]),
    QF("hump-bridge", "Tümsek ya da çukur yolun tepesinde/dibinde normal kuvvet",
       ["FİZ.11.1.10:b"], ["dusey-duzlemde-cembersel", "normal-kuvvet", "merkezcil-kuvvet"], ["centripetal-force", "weight"],
       ["DAILY_LIFE_CONTEXT", "DIAGRAM"],
       "Tümsek köprünün tepesinden ya da çukurun dibinden geçen aracın zemine uyguladığı kuvvet ya da yolu terk etme hızı sorulur.",
       ["kütle", "yarıçap", "hız"], ["normal kuvvet / en büyük hız"],
       [V("daily_life", "Tümsek köprüden geçen minibüs (kitap ÖD-34)")],
       [D("Tümsek tepesinde normal kuvvet ağırlıktan büyüktür", "Merkezcil ivmenin yönünü (aşağı) bilmeme")],
       [E("mg − N yerine N − mg yazmak", "SIGN_ERROR")],
       ["Tepede mg − N = mϑ²/r; dipte N − mg = mϑ²/r"],
       {"range": ["orta"], "drivers": []},
       [("tb", 145, "ÖD-34", "tümsek")]),
    QF("flat-curve", "Yatay virajda kaymadan dönme",
       ["FİZ.11.1.10:b"], ["yatay-viraj", "statik-surtunme", "merkezcil-kuvvet"], ["flat-curve-max-speed", "centripetal-force"],
       ["DAILY_LIFE_CONTEXT", "DIAGRAM"],
       "Yatay virajda merkezcil kuvveti statik sürtünmenin sağladığı aracın kaymadan dönebileceği en büyük hız sorulur.",
       ["yarıçap", "statik katsayı"], ["en büyük hız / karşılaştırma"],
       [V("daily_life", "Yağışlı havada virajda güvenli hız (kitap 45. Alıştırma)"),
        V("common", "Yatay viraj ile sürtünmesiz eğimli virajın karşılaştırılması")],
       [D("Ağır araç daha düşük hızda kayar", "Kütlenin sadeleştiğini görmeme"),
        D("Virajda araca dışa doğru kuvvet etki eder", "Merkezkaç kuvvet yanılgısı")],
       [E("Kinetik katsayı kullanmak", "CONCEPTUAL_ERROR")],
       ["k_s·m·g = m·ϑ²/r"],
       {"range": ["orta"], "drivers": []},
       [("tb", 117, "45. Alıştırma", "yatay viraj")]),
    QF("banked-curve", "Eğimli virajda güvenli dönme",
       ["FİZ.11.1.10:b"], ["egimli-viraj", "normal-kuvvet", "merkezcil-kuvvet", "vektor-bilesenleri"], ["banked-curve-speed"],
       ["DAILY_LIFE_CONTEXT", "DIAGRAM"],
       "Sürtünmesiz eğimli virajda güvenli hız, eğim açısı ya da yarıçap sorulur.",
       ["eğim açısı", "yarıçap"], ["güvenli hız / açı"],
       [V("daily_life", "Velodrom pistinde bisikletçi (kitap s. 116)"), V("daily_life", "Formula 1 pist virajları (kitap ÖD-36)"),
        V("daily_life", "Bolu Dağı tüneli çıkışındaki eğimli viraj (kitap 45. Alıştırma)")],
       [D("Güvenli hız aracın kütlesine bağlıdır", "Kütlenin sadeleştiğini görmeme"),
        D("Merkezcil kuvveti normal kuvvetin düşey bileşeni sağlar", "Bileşenleri karıştırma")],
       [E("tanθ yerine sinθ almak", "VECTOR_ERROR")],
       ["N·sinθ = mϑ²/r ve N·cosθ = mg oranı"],
       {"range": ["orta", "zor"], "drivers": []},
       [("tb", 116, "Eğimli Virajda", "Eğimli"), ("tb", 146, "ÖD-36", "Formula")]),
    QF("rotor-and-regulator", "Dönen silindir ve düzeneklerde merkezcil kuvvet kaynağının belirlenmesi",
       ["FİZ.11.1.10:a"], ["merkezcil-kuvvet", "normal-kuvvet", "statik-surtunme", "gerilme-kuvveti"], ["centripetal-force"],
       ["DAILY_LIFE_CONTEXT", "DIAGRAM"],
       "Dönen silindir (rotor), asansör hız düzenleyici gibi düzeneklerde merkezcil kuvveti hangi kuvvetin sağladığı ve koşullar sorulur.",
       ["düzenek tarifi"], ["merkezcil kuvvet kaynağı / koşul"],
       [V("daily_life", "Asansörün hız düzenleyicisinde dönen kütleler (kitap ÖD-29)"),
        V("daily_life", "Dönen silindir içindeki kişi (kitap ÖD-35)")],
       [D("Merkezcil kuvvet ayrı bir kuvvettir", "Merkezcil kuvveti ayrı kuvvet sanma")],
       [E("Merkezcil kuvveti sağlayan kuvveti yanlış belirlemek", "CONCEPTUAL_ERROR")],
       ["Merkeze yönelik bileşkeyi bul"],
       {"range": ["orta", "zor"], "drivers": []},
       [("tb", 143, "ÖD-29", "hız düz"), ("tb", 146, "ÖD-35", "silindir")]),
    QF("circular-variables-data", "Düzgün çembersel hareket değişkenlerinin veri setinden modellenmesi",
       ["FİZ.11.1.10:a", "FİZ.11.1.10:b"], ["merkezcil-kuvvet", "cizgisel-surat", "kutle", "oran-oranti"],
       ["centripetal-force", "centripetal-acceleration"], ["TABLE", "GRAPH", "EXPERIMENT", "DATA_SET"],
       "Merkezcil kuvvetin kütle, sürat ve yarıçapla değişimini gösteren deney verisi ya da grafiği verilir; ilişki kurulur, eksik değer bulunur ya da hangi grafiğin doğrusal olacağı sorulur.",
       ["F_m, m, ϑ, r ölçüm tablosu ya da grafiği"], ["ilişki türü / eksik değer / doğrusal grafik"],
       [V("table", "Sabit r ve m'de ϑ iki katına çıkınca F_m'nin dört katına çıktığı tablo"),
        V("graph", "F_m–ϑ² grafiğinin doğrusal, F_m–ϑ grafiğinin eğrisel olması"),
        V("experimental", "İpe bağlı cismi döndürürken dinamometre ile kuvvet ölçümü")],
       [D("F_m sürat ile doğru orantılıdır", "Karesel ilişkiyi doğrusal sanma"),
        D("F_m yarıçapla doğru orantılıdır (sabit süratte)", "1/r ilişkisini ters kurma")],
       [E("İki değişkenin birlikte değiştiği satırları karşılaştırmak", "TABLE_READING_ERROR"),
        E("Doğrusallaştırılmış grafikte ekseni yanlış okumak", "GRAPH_READING_ERROR")],
       ["Kontrol değişkeni ile satır karşılaştırması", "Doğrusallaştırma"],
       {"range": ["orta", "zor"], "drivers": []},
       [("prog", "Farklı veri setleri ile hesaplamalar yaparak düzgün çembersel hareketin"), ("kil", 115)]),
    QF("rail-system-circular", "Ray sisteminde çembersel hareket (lunapark rayı, viraj rayı)",
       ["FİZ.11.1.10:b"], ["dusey-duzlemde-cembersel", "normal-kuvvet", "merkezcil-kuvvet"], ["centripetal-force"],
       ["DIAGRAM", "DAILY_LIFE_CONTEXT"],
       "Ray üzerinde düşey çemberde dönen vagonun normal kuvveti ya da gerekli hızı hesaplanır.",
       ["yarıçap", "hız"], ["normal kuvvet / en küçük hız"],
       [V("daily_life", "Lunapark hız treni ilmeği")],
       [D("Vagon merkezkaç kuvveti sayesinde düşmez", "Merkezkaç kuvvet yanılgısı")],
       [E("Raydan normal kuvvetin yönünü yanlış almak", "SIGN_ERROR")],
       ["Tepede mg + N = mϑ²/r"],
       {"range": ["zor"], "drivers": []},
       [("prog", "Ray sisteminde çembersel hareketle ilgili matematiksel işlemlerden kaçınılır")],
       scope="OUT_OF_SCOPE_CALC", scope_note="Program ray sistemlerinde matematiksel işlemi açıkça dışlıyor; yalnız nitel yorum kapsamda. Eski kaynaklarda sık görülür."),
]
