"""ÖSYM yayımlanmış fizik sorularının yapısal analizi (STEP 10).

Kaynak: osym.gov.tr "Temel Soru Kitapçıkları ve Cevap Anahtarları" duyurularındaki resmî PDF'ler
(dokuman.osym.gov.tr). Sorular PDF'den görsel olarak okunmuş; soru metni KOPYALANMAMIŞTIR, yalnız yapısal özet.
question_no = AYT Fen Bilimleri testinin Fizik bölümündeki sıra (1-14); TYT için Fizik bölümü sırası (1-7).
"""

_D = "https://dokuman.osym.gov.tr/pdfdokuman"
URLS = {
    ("AYT", 2018): f"{_D}/2018/YKS/AYT_01072018.pdf",
    ("TYT", 2018): f"{_D}/2018/YKS/TYT_01072018.pdf",
    ("AYT", 2019): f"{_D}/2019/YKS/TSK/ayt_yks_2019_web.pdf",
    ("TYT", 2019): f"{_D}/2019/YKS/TSK/tyt_yks_2019_web.pdf",
    ("AYT", 2020): f"{_D}/2020/YKS/TSK/ayt_yks_2020.pdf",
    ("TYT", 2020): f"{_D}/2020/YKS/TSK/tyt_yks_2020.pdf",
    ("AYT", 2021): f"{_D}/2021/YKS/TSK/ayt_yks_2021.pdf",
    ("TYT", 2021): f"{_D}/2021/YKS/TSK/tyt_yks_2021.pdf",
    ("AYT", 2022): f"{_D}/2022/YKS/TSK/yks_2022_ayt.pdf",
    ("TYT", 2022): f"{_D}/2022/YKS/TSK/yks_2022_tyt.pdf",
    ("AYT", 2023): f"{_D}/2023/YKS/TSK/yks_ayt_2023_kitapcik_g5A2H.pdf",
    ("TYT", 2023): f"{_D}/2023/YKS/TSK/yks_tyt_2023_kitapcik_T23ky.pdf",
    ("AYT", 2024): f"{_D}/2024/YKS/TSK/yks_ayt_2024_kitapcik_ts85k.pdf",
    ("TYT", 2024): f"{_D}/2024/YKS/TSK/yks_tyt_2024_kitapcik_T24kt.pdf",
    ("AYT", 2025): f"{_D}/2025/YKS/TSK/yks_ayt_2025_kitapcik_st12.pdf",
    ("TYT", 2025): f"{_D}/2025/YKS/TSK/yks_tyt_2025_kitapcik_d250.pdf",
}

ANNOUNCEMENTS = [
    {"id": "ann-osym-2028-not-found", "title": "ÖSYM'nin 2028 YKS / Maarif Modeli için resmî açıklaması: osym.gov.tr'de bulunamadı",
     "organization": "ÖSYM (osym.gov.tr)", "url": "https://www.osym.gov.tr/SinavGrubu/Index/2", "date": "2026-10-02",
     "summary": "YKS duyuru listesi ve 2026-YKS Kılavuzu PDF'i tarandı; 2028 sınavı, Maarif Modeli veya beceri temelli soru modeline dair ÖSYM kaynaklı resmî açıklama bulunamadı. Blog iddiaları duyuru olarak kaydedilmedi.",
     "relevance": "2028 YKS biçimi hakkında ÖSYM tarafından yayımlanmış bağlayıcı bir belge yok; analiz 2018-2025 gerçek sorularına ve 11. sınıf program sınırlarına dayanır.",
     "verified_read": True},
    {"id": "ann-meb-2025-12-yks-lgs-2028", "title": "YKS ve LGS'de yeni müfredata uyumlu soru modeli 2028'de hayata geçecek",
     "organization": "MEB (ÖSYM ile iş birliği)", "url": "https://www.meb.gov.tr/yks-ve-lgsde-yeni-mufredata-uyumlu-soru-modeli-2028de-hayata-gececek/haber/39265/tr",
     "date": "2025-12-15",
     "summary": "MEB Bakan Yardımcısı: yeni müfredata uyumlu, beceri ve bağlam temelli soru modeli 2028'de YKS ve LGS'de kullanılacak; soru modelleme ÖSYM ile sürüyor; çoktan seçmeli biçim korunacak; örnek sorular MEB platformlarından paylaşılacak.",
     "relevance": "Soru biçiminin bilgi hatırlamadan bağlam içinde bilgi kullanımına kayacağını resmî düzeyde bildirir; sınav sistemi (TYT-AYT) değişikliği değil.",
     "verified_read": True},
    {"id": "ann-meb-2024-11-osym-ziyaret", "title": "Bakan Tekin, ÖSYM Başkanı Ersoy'u kabul etti",
     "organization": "MEB", "url": "https://meb.gov.tr/bakan-tekin-osym-baskani-ersoyu-kabul-etti/haber/35320/tr", "date": "2024-11-04",
     "summary": "9. sınıfta Maarif Modeli ile başlayan öğrencilerin YKS'ye 2028'de gireceği, 10-12. sınıfların eski müfredatla sınava gireceği; TYT ve AYT için MEB-ÖSYM uzman çalıştayları yapıldığı belirtildi.",
     "relevance": "2028 YKS'nin Maarif müfredatına uyumlu olacağını ve geçiş takvimini doğrular.",
     "verified_read": True},
]

ITEMS = []


def Q(year, exam, no, topic, los, out, fam, fm, skills, c, i, m, flags, distractor, strategy, summary, fit, fit_reason, conf, rm="official_pdf"):
    """Kompakt kayıt üretici. flags: boşlukla ayrılmış {ms gr tb ex dl} (multi_step, graph, table, experimental, daily_life)."""
    f = set(flags.split())
    assert f <= {"ms", "gr", "tb", "ex", "dl"}, flags
    return {"year": year, "exam": exam, "question_no": no, "source_url": URLS[(exam, year)], "read_method": rm, "topic": topic,
            "learning_outcomes": los, "out_of_11_scope": out, "question_family": fam, "family_match": fm, "skills": skills,
            "conceptual_load": c, "interpretation_load": i, "mathematical_load": m, "multi_step": "ms" in f, "graph_based": "gr" in f,
            "table_based": "tb" in f, "experimental_context": "ex" in f, "daily_life_context": "dl" in f, "distractor_structure": distractor,
            "solution_strategy": strategy, "summary": summary, "fit_2028": fit, "fit_reason": fit_reason, "confidence": conf}


# Ortak çeldirici yapısı etiketleri
ROMAN = "I-II-III öncülleri; şıklar öncül kombinasyonları (Yalnız I … I, II ve III)"
NUM = "sayısal şıklar (A–E artan değerler)"


# ============================ 2018 AYT (14/14 okundu) ============================
ITEMS += [
    Q(2018, "AYT", 1, "Makara düzeneğinde bağlı cisimlerin ivmesi (Newton II)", ["FİZ.11.1.5"], "", "connected-bodies-same-acceleration", "exact", ["KB2.14"],
      2, 2, 2, "ms", NUM, "Her sistemde net kuvvet / toplam kütle; birinden kütle bulunup diğerinin ivmesine geçilir",
      "Biri doğrudan çekilen, biri asılı ağırlıklarla çekilen iki özdeş sandıktan birinin ivmesi verilip diğerinin ivmesi isteniyor.",
      "yes", "Aynı ivmeyle hareket eden bağlı cisimler programda var; tek sistemde farklı ivmeli cisim yok.", "HIGH"),
    Q(2018, "AYT", 2, "Çembersel yörüngeden kopan taşın hız-ivme vektörleri", ["FİZ.11.1.9", "FİZ.11.1.3"], "", "string-cut-trajectory", "exact", ["KB2.16.3"],
      2, 2, 0, "ms dl", "nokta kümeleri (Yalnız II, I ve IV, …)", "Kopma anındaki hız teğettir; sonra ivme düşey g olduğundan hız düşey olan noktalar seçilir",
      "Düşey çemberde döndürülen taş serbest kalınca hız ve ivmenin birbirine paralel olduğu kopma noktaları isteniyor.",
      "yes", "Çembersel hareketin hız vektörü ve iki boyutlu hareketin ivmesi (yalnız g) doğrudan kapsamda.", "HIGH"),
    Q(2018, "AYT", 3, "Buz pateni: karşılıklı itme, momentum ve itme", [], "12. sınıf FİZ.12.1.3", None, "none", [],
      2, 1, 0, "dl", ROMAN, "Momentum korunumu: eşit büyüklükte momentum, kütle farkından hız karşılaştırması",
      "İki patenci birbirini iterek zıt yönlere kayıyor; hız, momentum ve itme büyüklüklerinin hangisinin öğrencide daha büyük olduğu soruluyor.",
      "no", "İtme-momentum 12. sınıfa (FİZ.12.1.3-4) taşındı; 11. sınıf programında yok.", "HIGH"),
    Q(2018, "AYT", 4, "Çubuğun dengesi ve tork oranı", [], "12. sınıf FİZ.12.1.1", None, "none", [],
      2, 2, 2, "", "kesirli şıklar (1/3, 2/3, 3/2, 3, 1)", "Mil noktasına göre tork dengesi; kuvvet kolu oranı",
      "Eşit bölmeli çubuk iki kuvvetle dengede; birinin torku verilmişken diğerinin torkunun oranı bulunuyor.",
      "no", "Tork ve denge 12. sınıf (FİZ.12.1.1-2) konusudur.", "HIGH"),
    Q(2018, "AYT", 5, "Düzgün elektrik alanda asılı yüklü cismin sapma açısı", ["FİZ.11.2.2", "FİZ.11.1.5"], "", "efield-force-balance-droplet", "partial", ["KB2.14"],
      2, 2, 0, "ms", ROMAN, "Denge: tanα = qE/mg; hangi niceliğin artınca açının arttığına nitel karar",
      "Elektrik alanda ipe asılı yüklü cisim dengede; ip uzunluğu, kütle ve alan artırılınca sapma açısının değişimi soruluyor.",
      "yes", "Alan–kuvvet oran/yön yorumu ve serbest cisim diyagramı; hesap gerekmiyor.", "HIGH"),
    Q(2018, "AYT", 6, "Manyetik alandaki akım taşıyan çubuğun harekete geçmesi", ["FİZ.11.2.8"], "", "wire-force-direction-rhr", "exact", ["FBAB10"],
      2, 2, 0, "ex", "hareket durumu seçenekleri (hareketsiz / I ya da II yönünde hızlanır / sabit hızlı)", "Sağ el kuralıyla kuvvet yönü; sürtünmesiz rayda ivmeli hareket",
      "Mıknatıs içinde ray üstünde duran çubuk, anahtar kapanınca akım taşır; çubuğun ilk hareketinin yönü ve türü soruluyor.",
      "yes", "Akımlı tele etki eden kuvvetin yönü ve F=BIL mantığı doğrudan kapsamda.", "HIGH"),
    Q(2018, "AYT", 7, "Transformatörde doğru ve alternatif akımla sekonder gerilimi", ["FİZ.11.2.13", "FİZ.11.2.12"], "", "transformer-turns-voltage-current-ratio", "partial", ["FBAB8"],
      3, 2, 0, "ms", "iki sütunlu şıklar (Sıfırdır / primerden büyük / küçük)", "DC primerde akı değişimi yok → sekonder sıfır; AA'da sarım oranına göre karşılaştırma",
      "Biri doğru akım, biri alternatif akım kaynağına bağlı iki transformatörün sekonder gerilimlerinin primere göre durumu soruluyor.",
      "yes", "Transformatör nitelikleri yalnız yorumlanıyor; sayısal sarım hesabı yok, program ile uyumlu.", "HIGH"),
    Q(2018, "AYT", 8, "Sarkacın en alt noktasında net kuvvet, ivme ve hız yönleri", ["FİZ.11.1.5", "FİZ.11.1.9"], "", "net-force-motion-state", "partial", ["KB2.14"],
      2, 3, 0, "", "vektör çizimi seçenekleri (üç vektörün yön kombinasyonları)", "Merkezcil ivme merkeze, net kuvvet ivmeyle aynı yön; hız teğet",
      "Salınan bilyenin en alt noktasından geçerken net kuvvet, merkezcil ivme ve hız vektörlerinin yönlerini gösteren doğru çizim seçiliyor.",
      "yes", "Net kuvvet-ivme ilişkisi ve çembersel hareketin merkezcil ivmesi kapsamda; sarkaç yalnız bağlam.", "MEDIUM"),
    Q(2018, "AYT", 9, "Dünya'nın yörüngesinde günberi: hız, açısal momentum, çekim kuvveti", [], "programda yok (kütle çekim/Kepler; açısal momentum yalnız 12. sınıf FİZ.12.1.6 dönme bağlamında)", None, "none", [],
      3, 2, 0, "", ROMAN, "Günberide hız ve çekim büyük; açısal momentum korunur (eşit)",
      "Dünya'nın Güneş'e en yakın olduğu günle uzak olduğu günün çizgisel hız, açısal momentum ve çekim kuvveti büyüklükleri karşılaştırılıyor.",
      "no", "Kütle çekim ve Kepler yasaları 9-12. sınıf programında yer almıyor.", "MEDIUM"),
    Q(2018, "AYT", 10, "Yay-kütle ve basit sarkaç periyotlarının eşitlenmesi", [], "programda yok (BHH periyot hesabı; 10. sınıf FİZ.10.4.1 yalnız kavramsal)", None, "none", [],
      2, 2, 3, "ms", NUM, "T=2π√(l/g) ile T=2π√(m/k) eşitlenir; k=mg/l",
      "Düşey yaya asılı kütlenin periyodu, belirli uzunluktaki basit sarkaçla eşit olacak şekilde yay sabiti soruluyor.",
      "no", "Basit harmonik hareket hesabı yeni programda yok.", "HIGH"),
    Q(2018, "AYT", 11, "Radyo dalgalarının doğası", [], "12. sınıf FİZ.12.3.5", None, "none", [],
      1, 1, 0, "dl", ROMAN, "Elektromanyetik dalga: enine, boşlukta yayılır, ses değildir",
      "Radyo vericisinden alıcıya gelen dalganın ses mi, enine mi, maddesel ortam gerektirir mi olduğu öncüllerle yargılanıyor.",
      "no", "Elektromanyetik dalgalar 12. sınıf (FİZ.12.3.5) konusu.", "HIGH"),
    Q(2018, "AYT", 12, "Döteryum-trityum füzyonu ve çekirdek kararlılığı", [], "12. sınıf FİZ.12.4.8", None, "none", [],
      3, 2, 0, "", ROMAN, "Enerji açığa çıkması: ürün çekirdek bağlanma enerjisi başına daha kararlı",
      "Füzyon tepkimesi enerji verdiğine göre hangi çekirdeklerin birbirine göre daha kararlı olması gerektiği öncüllerle soruluyor.",
      "no", "Nükleer enerji 12. sınıf (FİZ.12.4.8) konusu.", "MEDIUM"),
    Q(2018, "AYT", 13, "Fotoelektrik olay: Ek–f grafiği", [], "12. sınıf FİZ.12.4.2", None, "none", [],
      3, 2, 0, "gr", ROMAN, "Eğim h evrensel; eşik frekansı üstündeki f için elektron çıkar",
      "Maksimum kinetik enerji–frekans grafiğinden eğimin, eşik frekansının ve dalga boyunun yorumlanmasına dair öncüller değerlendiriliyor.",
      "no", "Fotoelektrik olay 12. sınıf (FİZ.12.4.2) konusu.", "HIGH"),
    Q(2018, "AYT", 14, "X ışınlarının görünür ışığa göre büyüklükleri", [], "12. sınıf FİZ.12.3.5", None, "none", [],
      2, 1, 0, "dl", ROMAN, "Elektromanyetik tayf sırası: X ışını frekansı büyük, dalga boyu küçük, hız aynı",
      "X ışınlarının canlılara zarar verebilmesinin hız, dalga boyu ve frekanstan hangisinin görünür ışıktan kesinlikle büyük olmasından kaynaklandığı soruluyor.",
      "no", "Elektromanyetik tayf 12. sınıf (FİZ.12.3.5) konusu.", "HIGH"),
]

# ============================ 2019 AYT (14/14 okundu) ============================
ITEMS += [
    Q(2019, "AYT", 1, "Göreli hız: iki aracın hız vektörlerinden gözlemciye göre hız", [], "9. sınıf FİZ.9.2.4 (vektör toplama); hareketli referans yalnız 11. sınıf zenginleştirmede", None, "none", [],
      2, 2, 2, "ms dl", "büyüklük+yön çiftleri (15√2 güneybatı …)", "Referans değişimi: vektör farkı; dik bileşenlerden Pisagor",
      "Batıya ve kuzeye sabit hızla giden iki araçtan birinin sürücüsüne göre diğerinin hızının büyüklüğü ve yönü isteniyor.",
      "no", "Vektör toplama 9. sınıf konusu; hareketli referanstan bakış 11. sınıf programında yalnız zenginleştirme düzeyinde.", "MEDIUM"),
    Q(2019, "AYT", 2, "Farklı yüksekliklerden yatay fırlatılan cisimlerin ilk hız oranı", ["FİZ.11.1.3"], "", "2d-horizontal-launch", "exact", ["FBAB10"],
      2, 2, 2, "ms gr", "kesirli/köklü oran şıkları (1/4, 1/√2, 1/2, 1, √2)", "Düşme süresi √h ile orantılı; aynı menzilde v ∝ 1/t",
      "Aynı noktaya düşen ve farklı yüksekliklerden yatay atılan iki cismin ilk hızlarının oranı soruluyor; yol şekille veriliyor.",
      "yes", "İki boyutta sabit ivmeli hareket için sayısal hesap programda kapsam içinde (CALC_INCLUDED).", "HIGH"),
    Q(2019, "AYT", 3, "Çarpışma testi: ortalama itme kuvveti", [], "12. sınıf FİZ.12.1.3", None, "none", [],
      2, 1, 2, "dl", NUM, "İtme = momentum değişimi; F = m·Δv/Δt",
      "Hareketli arabadan duran mankenin durması için gereken en az ortalama kuvvet, kütle, hız ve çarpışma süresiyle hesaplatılıyor.",
      "no", "İtme-momentum 12. sınıfa taşındı.", "HIGH"),
    Q(2019, "AYT", 4, "Dengedeki sandıkta net kuvvet sıfırken ivme, tork ve momentum", ["FİZ.11.1.4"], "tork ve momentum öncülleri 12. sınıf FİZ.12.1.1-3", None, "none", [],
      2, 2, 0, "dl", ROMAN, "Net kuvvet sıfır → ivme sıfır; tork ve momentum için 'kesinlikle' ayrımı",
      "Birkaç kişinin taşıdığı sandığa etkiyen bileşke kuvvet sıfırken kütle merkezi ivmesi, toplam tork ve çizgisel momentumun kesinlikle sıfır olup olmadığı yargılanıyor.",
      "form_changes", "Yalnız net kuvvet–ivme öncülü 11. sınıfta; tork ve momentum öncülleri 12. sınıf, biçim değişmeli.", "MEDIUM"),
    Q(2019, "AYT", 5, "Farklı yarıçaplı iletken bilyelerde yük aktarımı sonrası yük ve potansiyel", [], "programda yok (iletkenlerde yük paylaşımı, elektriksel potansiyel; 8. sınıf elektriklenme temel kabul)", None, "none", [],
      3, 2, 0, "ex", ROMAN, "Dokundurma sonrası potansiyeller eşit; yük miktarı yarıçapa bağlı, aynı işaretli",
      "İki farklı boyutta metal bilye yüklenip dokundurulduktan sonra net yük, potansiyel ve yük cinsi ile ilgili öncüller değerlendiriliyor.",
      "no", "Elektriksel potansiyel ve iletkende yük dağılımı yeni 9-12. sınıf programında yok.", "MEDIUM"),
    Q(2019, "AYT", 6, "Mıknatıs ve silginin halkadan düşerken Lenz etkisi", ["FİZ.11.2.10", "FİZ.11.2.11"], "", "magnet-falling-through-ring", "exact", ["KB2.4", "FBAB10"],
      3, 3, 0, "ex", "beş durum önermesi (yükseklik karşılaştırması, kutup/kütle bağımlılığı)", "Mıknatıs akı değişimi nedeniyle frenlenir; silgi serbest düşer; kontrol değişkeni mantığı",
      "Mıknatıs ile silgi alüminyum halkadan düşerken halkada akım oluşmasının mıknatısı geciktirmesi nedeniyle bunların halkayı geçtikten sonraki yükseklikleri karşılaştırılıyor.",
      "yes", "Akı değişimi ve indüksiyon akımının yönü/etkisi nitel; programda hesapsız kapsam uygun.", "HIGH"),
    Q(2019, "AYT", 7, "Müzik çalar devresinde frekansa göre direnç gösteren eleman", [], "programda yok (bobin/kondansatör reaktansı, AA devre elemanları)", None, "none", [],
      3, 2, 0, "dl", ROMAN, "Kondansatör düşük frekansa büyük direnç; bobin yüksek frekansa büyük direnç; reosta frekanstan bağımsız",
      "Düşük frekanslı sinyallere daha büyük direnç gösterecek devre elemanının bobin, reosta ve kondansatörden hangileri olabileceği soruluyor.",
      "no", "Bobin ve kondansatörün AA'daki davranışı programda yok.", "HIGH"),
    Q(2019, "AYT", 8, "Otoyol virajlarını güvenli kılan önlemler", ["FİZ.11.1.10"], "", "banked-curve", "exact", ["FBAB10"],
      2, 1, 0, "dl", ROMAN, "Eğimli viraj ve sürtünme kuvveti merkezcil kuvvete katkı; yarıçap küçültmek tehlikeli",
      "Araçların virajda güvenli dönmesi için yol-lastik sürtünmesi, virajın eğimi ve yarıçapına ilişkin önlemlerden hangilerinin uygulanması gerektiği öncüllerle soruluyor.",
      "yes", "Yatay ve eğimli viraj ile viraj güvenliği programda doğrudan var.", "HIGH"),
    Q(2019, "AYT", 9, "Kollarını gövdesine yaklaştıran patencide açısal momentum ve eylemsizlik momenti", [], "12. sınıf FİZ.12.1.5-6", None, "none", [],
      2, 2, 0, "dl", "iki sütunlu şıklar (artar / azalır / değişmez)", "Dış tork yok → açısal momentum korunur; kütle merkeze yaklaşınca eylemsizlik momenti azalır",
      "Buz pistinde dönen kişi kollarını gövdesine yaklaştırınca açısal momentum ve eylemsizlik momentinin nasıl değiştiği soruluyor.",
      "no", "Eylemsizlik momenti ve açısal momentum korunumu 12. sınıf konusu.", "HIGH"),
    Q(2019, "AYT", 10, "Yay-kütle sistemlerinde titreşim frekansları karşılaştırması", [], "programda yok (basit harmonik hareket frekansı, yay bağlama; 12. sınıf FİZ.12.2.1-2 yalnız Hooke)", None, "none", [],
      3, 3, 0, "ms", "frekans sıralaması şıkları (fX < fY = fZ …)", "f ∝ √(k_eş/m); eğik düzlem frekansı değiştirmez; seri yay k_eş küçük",
      "Düşeyde asılı, eğik düzlemde ve iki yaya seri asılı üç özdeş kütlenin titreşim frekansları arasındaki sıralama soruluyor.",
      "no", "Basit harmonik hareket ve yay sabitlerinin eşdeğeri yeni programda yok.", "MEDIUM"),
    Q(2019, "AYT", 11, "Elektromanyetik tayfta hız, frekans ve dalga boyu karşılaştırması", [], "12. sınıf FİZ.12.3.5", None, "none", [],
      2, 1, 0, "", ROMAN, "Aynı ortamda sürat aynı değil (boşlukta eşit); frekans: X > mikrodalga; dalga boyu: kırmızı > mavi",
      "Gama, X, mikrodalga, radyo ve görünür ışık dalgalarının sürat, frekans ve dalga boyu bakımından birbirine göre durumu öncüllerle sınanıyor.",
      "no", "Elektromanyetik dalga sınıflandırması 12. sınıf (FİZ.12.3.5-6).", "HIGH"),
    Q(2019, "AYT", 12, "Radyoaktif bozunma zincirinde yayınlanan parçacıklar", [], "12. sınıf FİZ.12.4.8 (yalnız sorgulama düzeyi; bozunma türleri programda açık değil)", None, "none", [],
      3, 2, 1, "ms", "iki sütunlu şıklar (β⁻/β⁺/α kombinasyonları)", "Kütle ve atom numarası değişimini izleyerek bozunma türünü bulma",
      "Bizmut çekirdeğinin iki ardışık bozunmayla kurşuna dönüşmesinde her adımda yayınlanan parçacığın türü kütle ve proton sayısı değişiminden bulunuyor.",
      "no", "Radyoaktif bozunma 12. sınıfta yalnız nükleer enerji sorgulaması kapsamında.", "MEDIUM"),
    Q(2019, "AYT", 13, "Fotoelektrik düzenekte kullanılabilecek eşik enerjisi sınırı", [], "12. sınıf FİZ.12.4.2", None, "none", [],
      3, 2, 3, "ms", NUM, "E = hc/λ ile ışık enerji aralığı; eşik ≤ foton enerjisi koşulu",
      "Dalga boyu aralığı ve hc değeri verilen ışıkla fotoelektron koparabilmek için metalin eşik enerjisinin en çok ne olabileceği hesaplatılıyor.",
      "no", "Fotoelektrik olay 12. sınıf konusu.", "HIGH"),
    Q(2019, "AYT", 14, "Termal kamera, PET ve sonarın görüntü oluşturma prensipleri", [], "12. sınıf FİZ.12.3.7", None, "none", [],
      2, 2, 0, "dl", "üçlü eşleştirme şıkları (cihaz sıralamaları)", "Cihaz–dalga türü eşleştirme (kızılötesi, ses, antiparçacık)",
      "Üç görüntüleme cihazının hangi fiziksel ilkeyle (kızılötesi yayım, ses yansıması, antiparçacık yok oluşu) görüntü oluşturduğu eşleştiriliyor.",
      "no", "Dalga kullanan cihazlar 12. sınıf (FİZ.12.3.7); PET kapsam dışı.", "MEDIUM"),
]

# ============================ 2020 AYT (14/14 okundu) ============================
ITEMS += [
    Q(2020, "AYT", 1, "Hareketli vagonda düşey atılan topun yere göre görülen yörüngesi", ["FİZ.11.1.3"], "", "2d-moving-reference-launch", "exact", ["FBAB10"],
      2, 2, 0, "dl", "yörünge çizimi seçenekleri (düşey doğru, eğri ve yatay-eğri kombinasyonları)", "Yatay bileşen vagonla aynı sabit hız, düşey bileşen sabit ivmeli; bileşke yörünge parabol",
      "Sabit hızla giden vagonda yukarı doğru atılan topun, yerde duran gözlemciye göre tepe noktasına kadar izlediği yolun şekli seçiliyor.",
      "form_changes", "Hareketli referanstan bakış programda yalnız zenginleştirme önerisidir; bileşenlerin bağımsızlığı kapsamda, soru nitel biçimde korunabilir.", "MEDIUM"),
    Q(2020, "AYT", 2, "Duvara yatay kuvvetle bastırılan tuğlalarda statik sürtünme kuvvetleri", ["FİZ.11.1.7", "FİZ.11.1.6", "FİZ.11.1.5"], "", "friction-wall-press", "exact", ["FBAB10"],
      2, 2, 1, "", "sıralama şıkları (fK > fL = fN … fK = fL = fN)", "Düşey denge: statik sürtünme ağırlığa eşittir; bastırma kuvveti sürtünmeyi belirlemez, yalnız kütle önemlidir",
      "Farklı kütleli ve farklı yatay kuvvetle duvara bastırılıp hareketsiz kalan üç tuğlanın duvara uyguladığı statik sürtünme kuvvetlerinin büyüklük sıralaması isteniyor.",
      "yes", "Statik sürtünmenin uygulanan kuvvete değil dengeye bağlı olması ve FCD yorumu programda doğrudan var.", "HIGH"),
    Q(2020, "AYT", 3, "Yukarı fırlatılan cismin hareketinde ivme yönü, hız bileşenleri ve mekanik enerji tablosu", ["FİZ.11.1.3"], "mekanik enerji öncülü 10. sınıf FİZ.10.2.4 ön bilgisi", "2d-angled-launch", "exact", ["FBAB10"],
      2, 2, 0, "tb", ROMAN, "Yatay bileşen sabit, ivme hep aşağı, düşey hız yükselirken azalır alçalırken artar, mekanik enerji korunur; her satır ayrı sınanır",
      "Hava direnci yokken yukarıya açılı fırlatılan cismin çıkış ve iniş evrelerinde ivme yönü, hız bileşenleri ve mekanik enerjisi için hazırlanmış tablonun doğru satırları seçiliyor.",
      "yes", "İki boyutlu hareketin bileşen yorumu ve yalnız g ivmesi doğrudan kapsamda; hesap gerekmiyor.", "HIGH"),
    Q(2020, "AYT", 4, "Çembersel ray (loop) ve yükseklikteki hedefe ulaşan oyuncak arabanın en küçük ilk hızı", ["FİZ.11.1.10"], "", "rail-system-circular", "exact", ["FBAB10"],
      3, 2, 3, "ms dl", NUM, "İki koşulun büyüğü alınır: çemberin tepesinde geçiş hızı koşulu ve hedef yüksekliğe çıkma; mekanik enerji korunumuyla ilk hıza geçilir",
      "Sürtünmesiz rayda önce küçük bir çember sonra yükselen yolu izleyen oyuncak arabanın, yüksekteki balona ulaşması için gereken en küçük ilk hız hesaplatılıyor.",
      "form_changes", "Düşey çember geçiş koşulu kapsamda ancak programda ray sistemlerinde matematiksel işlem açıkça dışlanır; ray bağlamı ve enerji hesabı çıkarılmalı.", "HIGH"),
    Q(2020, "AYT", 5, "Eşit kütleli iki arabanın esnek çarpışmasında hız ve momentum değişimi", [], "12. sınıf FİZ.12.1.4", None, "none", [],
      2, 3, 0, "", ROMAN, "Eşit kütleli esnek çarpışmada hız vektörleri takas edilir; yön ve momentum değişimi vektör olarak okunur",
      "Birimkareli zeminde hız vektörleri verilen eşit kütleli iki arabanın merkezî esnek çarpışmasından sonra hızlarının yönü ve momentumlarının değişip değişmediği yargılanıyor.",
      "no", "Momentum korunumu ve çarpışmalar 12. sınıfa (FİZ.12.1.3-4) taşındı; 11. sınıfta yok.", "HIGH"),
    Q(2020, "AYT", 6, "Yatay kuvvetle duvara dayalı sürtünmesiz bloklar dizisinde temas kuvvetleri", ["FİZ.11.1.5", "FİZ.11.1.4"], "", "newton3-action-reaction", "partial", ["KB2.14"],
      2, 2, 0, "", "kesirli şıklar (1/4, 1/2, 1, 3/2, 2)", "Her blok dengede: temas kuvvetleri zincirde birbirine eşit aktarılır; kütleler çeldiricidir",
      "Yatay kuvvetle itilen ve duvara dayanan üç farklı kütleli sürtünmesiz bloktan ilkinin ikinciye uyguladığı kuvvet verilip duvarın sonuncuya uyguladığı kuvvet isteniyor.",
      "yes", "Newton yasaları ve dengede serbest cisim diyagramı kapsamda; ivmesiz sistem olduğundan hesap kısıtı da sorun çıkarmıyor.", "MEDIUM"),
    Q(2020, "AYT", 7, "Düzgün elektrik alana dik fırlatılan zıt yüklü parçacıkların yörüngesi", ["FİZ.11.2.2", "FİZ.11.1.5"], "", "efield-charged-particle-deflection", "exact", ["KB2.14"],
      2, 3, 0, "dl", "yörünge çizimi çiftleri (sapma yönü ve yörünge biçimi kombinasyonları)", "Pozitif yük alan yönünde, negatif yük ters yönde kuvvet alır; başlangıç hızına dik sabit kuvvet eğri yörünge verir",
      "Yer çekimi yokken sağa yönlü düzgün alana dik hızla gönderilen pozitif ve negatif yüklü iki parçacığın alan içindeki yörüngelerini gösteren doğru çizim seçiliyor.",
      "yes", "Alan yönü ile yük işareti ilişkisi ve kuvvetin hareket yörüngesine etkisi nitel düzeyde kapsamda.", "HIGH"),
    Q(2020, "AYT", 8, "Manyetik alanda hareket eden iletken çubuğun uçlarında yük ayrışması", ["FİZ.11.2.8", "FİZ.11.2.11"], "hareketli yüke etki eden kuvvetin yönü programda ayrı çıktı değil (yalnız FİZ.11.2.8 notu)", None, "none", [],
      3, 3, 0, "", "işaret çiftleri (+/−, nötr kombinasyonları)", "Hareketli yüklere kuvvet yönü sağ el kuralıyla bulunur; pozitif yük bir uca toplanır, öbür uç negatif kalır",
      "Sayfa düzlemine dik alanda sabit hızla ilerleyen nötr metal çubuğun iki ucunda oluşan elektrik yük dağılımının işaretleri soruluyor.",
      "form_changes", "Hareket eden iletkende yük ayrışması indüksiyon gerilimi ile ilişkili ama serbest yüke etki eden kuvvet ayrı çıktı değil; bağlam ve yön kuralı açıkça verilmeli.", "MEDIUM"),
    Q(2020, "AYT", 9, "Elektriğin yüksek gerilimde taşınmasının temel nedeni", ["FİZ.11.2.13"], "", "transformer-transmission-loss", "exact", ["FBAB8"],
      1, 1, 0, "dl", "gerekçe ifadeleri (enerji kaybı, gerilim düşmesi, süre, depolama, talep)", "Yüksek gerilimde akım küçülür, iletim hattında ısı kaybı azalır; yanlış gerekçeler elenir",
      "Enerjinin santrallerden uzaktaki tüketim bölgelerine yüksek gerilimde taşınmasının temel gerekçesi seçeneklerden bulunuyor.",
      "yes", "Transformatörlerin kullanım alanı ve iletimde enerji kaybı nitel olarak doğrudan programdadır.", "HIGH"),
    Q(2020, "AYT", 10, "Dönme dolabın kabinlerinde farklı noktalardaki merkezcil kuvvet", ["FİZ.11.1.10", "FİZ.11.1.9"], "", "circular-analogies", "partial", ["FBAB10"],
      2, 2, 1, "dl", "sıralama şıkları (FA = FB = FC = FD … FC > FA > FB = FD)", "Sabit açısal hız ve sabit yarıçapta F = mω²r aynıdır; konum merkezcil kuvvetin büyüklüğünü değiştirmez",
      "Sabit açısal hızla dönen dönme dolapta kütle merkezinin eksene uzaklığı sabit olan bir kişiye A, B, C, D noktalarında etkiyen merkezcil kuvvet büyüklükleri karşılaştırılıyor.",
      "yes", "Düzgün çembersel harekette merkezcil kuvvet modeli ve düşey düzlem bağlamı programda doğrudan var.", "HIGH"),
    Q(2020, "AYT", 11, "Momentumu değişen ama kütlesi ve kinetik enerjisi sabit hareketin yorumu", ["FİZ.11.1.4", "FİZ.11.1.9"], "çizgisel momentum 12. sınıf FİZ.12.1.3; iş-enerji 10. sınıf FİZ.10.2.1-2 ön bilgisi", "net-force-motion-state", "partial", ["KB2.14"],
      3, 3, 0, "", ROMAN, "Hız büyüklüğü sabit, yönü değişen hareket tanınır (düzgün çembersel); net kuvvet ve ivme var, kuvvet iş yapmaz",
      "Çizgisel momentumu değişen fakat kütle ve kinetik enerjisi sabit kalan cisim için net kuvvet, yapılan iş ve ivmenin sıfır olup olmadığı kesin yargılarla sınanıyor.",
      "form_changes", "'Momentum' dili 12. sınıfa ait; hızın yönü değişen sabit sürat bağlamıyla yeniden yazılırsa çembersel hareket çıktısına uyar.", "MEDIUM"),
    Q(2020, "AYT", 12, "Eylemsizlik momentinin bağlı olduğu nicelikler", [], "12. sınıf FİZ.12.1.5", None, "none", [],
      2, 1, 0, "", ROMAN, "Eylemsizlik momenti dönmeye direncin ölçüsüdür, kütleye ve eksene uzaklığa bağlıdır, dönüş yönüne bağlı değildir",
      "Bir cismin belirli bir eksene göre eylemsizlik momentine dair üç yargıdan (direncin ölçüsü, kütle, dönüş yönü) hangilerinin doğru olduğu soruluyor.",
      "no", "Eylemsizlik momenti 12. sınıf (FİZ.12.1.5) konusu.", "HIGH"),
    Q(2020, "AYT", 13, "İki dairesel su dalgası kaynağında girişim noktaları", [], "12. sınıf FİZ.12.3.2", None, "none", [],
      2, 3, 0, "dl", "nokta kümeleri (Yalnız A, B ve C, …)", "Tepe-tepe ve çukur-çukur kesişim noktalarında yapıcı, tepe-çukur kesişiminde yıkıcı girişim; hareketsiz kalanlar yıkıcı düğüm noktalarıdır",
      "Aynı fazlı iki dairesel su dalgası kaynağının çizilen dalga tepelerinde A, B, C noktalarından hangilerinde hafif cisimlerin hareketsiz kalabileceği soruluyor.",
      "no", "Dairesel su dalgalarında girişim 12. sınıf (FİZ.12.3.2) konusu.", "HIGH"),
    Q(2020, "AYT", 14, "Ay yüzeyinde basit sarkaç ve yay-kütle periyotlarının değişimi", [], "programda yok (sarkaç ve yay periyodu; 10. sınıf FİZ.10.4.1 yalnız deneyim düzeyi, farklı g yalnız 11. sınıf zenginleştirme)", None, "none", [],
      3, 2, 0, "ex dl", "iki sütunlu şıklar (artar / azalır / değişmez)", "Sarkaç periyodu g'ye bağlı, yay-kütle periyodu g'den bağımsız; Ay'da g küçük olduğundan sarkaç periyodu artar",
      "Basit sarkaç ve düşey yay-kütle düzeneği aynı koşullarla Ay'a taşınsaydı iki periyodun nasıl değişeceği sorulan simülasyon bağlamlı bir deney senaryosu.",
      "no", "Salınım periyotlarının bağlı olduğu değişkenler yeni programda yok; farklı gezegen g'si yalnız serbest düşme zenginleştirmesinde geçer.", "MEDIUM"),
]

# ============================ 2021 AYT (14/14 okundu) ============================
ITEMS += [
    Q(2021, "AYT", 1, "Birimkareli düzlemde üç yük: bileşke elektriksel kuvvetin yönü", ["FİZ.11.2.1"], "", "coulomb-direction-newton3", "partial", ["FBAB10"],
      2, 3, 0, "", "vektör yönü okları (A–E sekiz yönden beşi)", "Verilen bileşkeden yük işaretleri çıkarılır; sonra aynı yüklerin Y üzerindeki kuvvetleri vektör olarak toplanır; çekme-itme yönleri belirlenir",
      "Karelerden oluşan zeminde X üzerindeki bileşke kuvvet verilmişken, aynı X ve Z yüklerinin Y'ye uygulayacağı bileşkenin olabilecek yönü soruluyor.",
      "yes", "Coulomb kuvvetinin yönü ve vektörel toplama programda hesapsız (yön) düzeyde var; işaret çıkarımı beceriye uygun.", "MEDIUM"),
    Q(2021, "AYT", 2, "Atılıp aynı yükseklikte tutulan topta sporcunun ortalama hızı", ["FİZ.11.1.3"], "", "2d-angled-launch", "exact", ["FBAB10"],
      2, 2, 2, "ms dl", NUM, "Yatay bileşen sabit; aynı seviyede yakalanan topun yer değiştirmesi yataydır, ortalama hız yatay hız bileşenine eşittir (v·cos53)",
      "Yatayla belirli açıyla atılıp aynı yükseklikte yakalanan topun atış ile tutuş arasında sporcunun ortalama hızının büyüklüğü hesaplatılıyor.",
      "yes", "İki boyutta sabit ivmeli hareketin bileşenleri ve trigonometrik hız bileşeni programda hesap düzeyinde var.", "HIGH"),
    Q(2021, "AYT", 3, "Basamak kenarından üç farklı yönde aynı hızla vurulan topun yere çarpma sürati", ["FİZ.11.1.3"], "", "2d-velocity-at-point", "exact", ["FBAB10"],
      2, 2, 0, "ms", "sıralama şıkları (vK > vL > vM … vK = vL = vM)", "Aynı ilk sürat ve aynı düşme yüksekliği: yatay bileşen sabit, v² = v0² + 2gh; açıdan bağımsız eşit sürat",
      "Hava direnci yokken basamak kenarından eşit büyüklükte ilk hızla, üç farklı eğimle fırlatılan topun yere çarpma anındaki süratlerinin birbirine göre durumu soruluyor.",
      "yes", "İki boyutlu harekette bir noktadaki hız ve bileşen mantığı kapsamda; enerji korunumu yerine kinematikle de çözülebilir.", "HIGH"),
    Q(2021, "AYT", 4, "El arabasının iki dengesinde kuvvet, tork ve net kuvvet değişimi", [], "12. sınıf FİZ.12.1.1-2", None, "none", [],
      3, 3, 0, "dl", ROMAN, "O noktasına göre tork dengesi: ağırlığın kolu sıfırlanınca uygulanan kuvvet ve torku azalır; net kuvvet iki durumda da sıfırdır",
      "Karpuzlu el arabası, yük merkezi tekerlek ekseniyle aynı düşeye getirilerek dengede tutulunca el kuvvetinin, onun torkunun ve net kuvvetin ilk duruma göre azalıp azalmadığı soruluyor.",
      "no", "Tork ve denge 12. sınıf (FİZ.12.1.1-2) konusudur.", "HIGH"),
    Q(2021, "AYT", 5, "İki noktasal yükün çevresinde noktalar arası elektriksel potansiyel farkı", [], "programda yok (elektriksel potansiyel ve potansiyel farkı; Coulomb ve alan yalnız oran/yön düzeyinde)", None, "none", [],
      3, 3, 2, "ms", ROMAN, "V = kq/d ile her noktanın toplam potansiyeli bulunur; uzaklık aralıkları verilince hangi çiftte fark sıfır olabilir sınanır",
      "+q ve +2q yükleri çevresinde çizilen eş merkezli çemberler üzerindeki K, L, M noktalarından hangi çiftlerin arasındaki potansiyel farkının sıfır olabileceği soruluyor.",
      "no", "Elektriksel potansiyel yeni programda yok; yalnız kuvvet ve alan oran/yön düzeyinde (FİZ.11.2.1-2).", "HIGH"),
    Q(2021, "AYT", 6, "Bobin, demir bilye ve bakır yuvalı devrede bilyenin hareketi", ["FİZ.11.2.7", "FİZ.11.2.6"], "", "emag-verify-and-apply", "partial", ["KB2.6"],
      2, 3, 0, "ex", "hareket senaryoları (periyodik yukarı-aşağı, hareketsiz, yapışık, sabit, asılı kalma)", "Devre kapanınca bobin bilyeyi çeker; bilye yuvadan ayrılınca akım kesilir, alan kalkar ve düşer; bu döngü yineler",
      "Bilyenin devreyi tamamladığı bir elektromıknatıslı kapalı kutuda anahtar kapatılınca demir bilyenin hareketine ilişkin olası yargı seçiliyor.",
      "yes", "Elektromıknatısın çalışma ilkesini yeni bir düzenekte yorumlama; hesapsız ve programdaki akım makarası alanı bilgisine uygun.", "MEDIUM"),
    Q(2021, "AYT", 7, "Enerji iletim hattında iki transformatörün sarım sayısı ilişkileri", ["FİZ.11.2.13"], "", "transformer-turns-voltage-current-ratio", "exact", ["FBAB8"],
      2, 2, 0, "dl", "sarım karşılaştırması çiftleri (N1p < N1s ve N2p > N2s …)", "İletimde akım küçük, gerilim büyük olmalı: ilk trafo yükseltici, ikinci alçaltıcı; sarım oranları buna göre sıralanır",
      "Santral çıkışında gerilimi yükselten ve evde 220 V'a indiren iki transformatörün primer ve sekonder sarım sayıları arasındaki doğru ilişki çifti seçiliyor.",
      "yes", "Yükseltici/alçaltıcı transformatör ve iletimde enerji kaybı programdaki yorum düzeyinde, hesapsız.", "HIGH"),
    Q(2021, "AYT", 8, "Düzgün çembersel hareketle ilgili tork, net kuvvet ve merkezcil ivme", ["FİZ.11.1.9", "FİZ.11.1.10"], "tork öncülü 12. sınıf FİZ.12.1.1", "horizontal-circle", "partial", ["KB2.14"],
      2, 3, 0, "", ROMAN, "Net kuvvet merkezcil ve sıfır değildir, merkezcil ivme sıfırdan farklıdır; kuvvet yarıçap doğrultusunda olduğundan merkeze göre tork sıfırdır",
      "Sürtünmesiz yatay düzlemde düzgün çembersel hareket yapan cisim için merkeze göre tork, net kuvvet ve merkezcil ivmeden hangilerinin sıfır olduğu soruluyor.",
      "form_changes", "Net kuvvet ve merkezcil ivme kapsamda; merkeze göre tork öncülü 12. sınıf konusu, çıkarılırsa soru uyar.", "MEDIUM"),
    Q(2021, "AYT", 9, "Yer sabit (jeosenkron) uydunun yörünge yarıçapı ve dönme koşulu", [], "programda yok (uydu hareketi, kütle çekim, yörünge periyodu; Astronomi yalnız disiplinler arası ilişki)", None, "none", [],
      3, 3, 0, "dl", "düzeltme önerileri (kütle azalt/artır, yarıçap büyüt/küçült, ters yön)", "Uydu doğuya hareket ediyorsa açısal hızı Dünya'dan büyük; periyot uzatmak için yarıçap büyütülür, kütle etkisizdir",
      "Yerden bakana göre sabit durması gereken televizyon uydusu doğuya kayıyorsa bu hatayı düzeltmek için kütle, yarıçap veya dönüş yönü seçeneklerinden hangisinin değiştirileceği soruluyor.",
      "no", "Kütle çekim, uydu yörüngeleri ve Kepler ilişkileri 9-12. sınıf programında yok.", "MEDIUM"),
    Q(2021, "AYT", 10, "Basit harmonik hareketin konum-zaman grafiğinden periyot, genlik ve denge", [], "programda yok (basit harmonik hareketin x–t grafiği; 10. sınıf FİZ.10.4.1-2 yalnız periyot ve genlik kavramları)", None, "none", [],
      2, 2, 1, "gr", ROMAN, "Grafikten periyot (tam salınım süresi), genlik (maksimum uzaklık) ve konum sıfır anı okunur; genlikle tepeden tepeye aralık karıştırılmaz",
      "Sinüs biçimli konum-zaman grafiği verilen cismin periyodu, genliği ve belirli bir anda denge konumunda olup olmadığına dair üç yargı değerlendiriliyor.",
      "no", "Basit harmonik hareket yeni programda yok; periyot-genlik yalnız dalga bağlamında 10. sınıfta.", "MEDIUM"),
    Q(2021, "AYT", 11, "Çift yarıkta yeşil yerine kırmızı ışık kullanılınca saçak değişimi", [], "12. sınıf FİZ.12.3.3 (ve FİZ.12.3.6)", None, "none", [],
      2, 2, 0, "ex", ROMAN, "Dalga boyu büyüyünce saçak genişliği artar; merkezî aydınlık saçak aynı yerde kalır; diğer saçakların yeri değişir",
      "Çift yarık deneyinde ışığın rengi yeşilden kırmızıya çevrilince saçak genişliği, merkezî aydınlık saçağın yeri ve diğer saçakların yeri hakkındaki yargılar sınanıyor.",
      "no", "Işıkta girişim 12. sınıf (FİZ.12.3.3) konusu.", "HIGH"),
    Q(2021, "AYT", 12, "Radyoaktif ve kararlı çekirdeklerin ortak özellikleri", [], "12. sınıf FİZ.12.4.8 (radyoaktivite programda yalnız nükleer enerji sorgulaması düzeyinde)", None, "none", [],
      3, 2, 0, "", ROMAN, "Her öncül hem radyoaktif hem kararlı çekirdek için sınanır; yalnız radyoaktife özgü özellikler elenir",
      "Rastgele seçilen radyoaktif ve kararlı bir çekirdek için kendiliğinden ışıma, nötron fazlası ve bozunmayla başka çekirdeğe dönüşme özelliklerinden hangilerinin ortak olabileceği soruluyor.",
      "no", "Çekirdek kararlılığı ve radyoaktivite 12. sınıf nükleer enerji bölümündedir.", "MEDIUM"),
    Q(2021, "AYT", 13, "Elektroskoplarda morötesi ışıkla fotoelektron kopması ve yük cinsi", [], "12. sınıf FİZ.12.4.2 (elektrikle yüklenme 8. sınıf ön bilgi)", None, "none", [],
      3, 3, 0, "ex", "iki sütunlu şıklar (pozitif / negatif / nötr)", "Eşik enerjisini aşan foton yalnız negatif yüklü elektroskoptan elektron söker, yaprak biraz kapanır; pozitifte değişim görünmez",
      "Morötesi ışıkla aydınlatılan iki elektroskoptan birinin yaprakları biraz kapanırken diğerinde değişim yok; her birinin yük cinsi için olası eşleşme seçiliyor.",
      "no", "Fotoelektrik olay 12. sınıf (FİZ.12.4.2) konusudur.", "HIGH"),
    Q(2021, "AYT", 14, "Lazer ışığının elde edilişinde atomda gerçekleşen olaylar", [], "programda yok (lazer; atomda uyarılma ve foton yayınlama 12. sınıf FİZ.12.4.7 çerçevesinde anılmıyor)", None, "none", [],
      2, 1, 0, "dl", ROMAN, "Lazerde uyarılma ve uyarılmış ışıma gerçekleşir; füzyon çekirdek olayıdır, atom düzeyinde olmaz",
      "Lazer ışığı üretilirken atomda uyarılma, foton yayınlama ve füzyon olaylarından hangilerinin gerçekleştiği öncüllerle soruluyor.",
      "no", "Lazer ve uyarılmış ışıma yeni 9-12. sınıf programında açıkça yok.", "MEDIUM"),
]

# ============================ 2022 AYT (14/14 okundu) ============================
ITEMS += [
    Q(2022, "AYT", 1, "Sürtünmesiz yatayda iki kişinin farklı yönlerde etkilediği kolinin hareket yönü", ["FİZ.11.1.4", "FİZ.11.1.5"], "vektör toplama ön bilgisi 9. sınıf FİZ.9.2.4", "net-force-motion-state", "exact", ["KB2.14"],
      2, 3, 0, "dl", ROMAN, "Ahmet kolayı yatay iter, Ali iple çeker; bileşke bu iki kuvvet arasında kalır, yalnız büyüklük oranına göre ulaşılabilen yönler seçilir",
      "Yandan itilen ve iple çekilen kolinin, iki kuvvetin büyüklükleri değiştikçe üç işaretli yönden hangilerine doğru harekete geçebileceği soruluyor.",
      "yes", "Bileşke kuvvet ile hareket yönü ilişkisi programda doğrudan var; hesap gerekmiyor.", "MEDIUM"),
    Q(2022, "AYT", 2, "Sabit hızlı kamyonda duran sandığa etki eden kuvvetler (yerdeki gözlemci)", ["FİZ.11.1.4", "FİZ.11.1.5"], "", "newton1-inertia", "exact", ["KB2.14"],
      2, 2, 0, "dl", ROMAN, "Sabit hızda net kuvvet sıfır: yatay kuvvet yok; düşey kuvvetler dengede, sandık kamyona ağırlığı kadar bastırır",
      "Yatay yolda sabit hızla giden kamyonun kasasında durağan sandık için yatay kuvvet, düşey kuvvet ve net kuvvet yargıları yerdeki gözlemciye göre değerlendiriliyor.",
      "yes", "Eylemsizlik ve net kuvvetin sıfır olduğu durumun yorumu programda doğrudan; soru biçimi uygun.", "HIGH"),
    Q(2022, "AYT", 3, "Yumurtanın sert zemine ve yumuşak ambalaja çarpması: temas süresi, momentum ve ortalama kuvvet", [], "12. sınıf FİZ.12.1.3", None, "none", [],
      2, 2, 0, "ex dl", ROMAN, "Momentum değişimi aynı; temas süresi artar, ortalama kuvvet azalır; her nicelik ayrı ayrı sınanır",
      "Aynı yükseklikten sert zemine ve köpükle sarılı hâlde bırakılan iki yumurtanın temas süresi, momentum değişimi ve ortalama kuvvetin ikinci durumda artıp artmadığı soruluyor.",
      "no", "İtme-momentum 12. sınıf (FİZ.12.1.3) konusu.", "HIGH"),
    Q(2022, "AYT", 4, "Makas seçimi ve tel konumuna göre kesme kuvvetinin büyüklüğü", [], "12. sınıf FİZ.12.1.1", None, "none", [],
      2, 3, 1, "dl", "beş şekil seçeneği (makas ve tel konumu kombinasyonları)", "Tork dengesi: kesme kuvveti kuvvet kolunun kesme noktasına olan kola oranıyla artar; birimkareli şekilden kollar okunur",
      "Farklı boy ve destek noktalı üç makas arasından, telin hangi konumunda aynı el kuvvetiyle bıçakların tele en büyük kuvveti uygulayacağı şekillerden seçiliyor.",
      "no", "Tork ve kaldıraç 12. sınıf (FİZ.12.1.1) konusudur.", "HIGH"),
    Q(2022, "AYT", 5, "Parçacığın düz yörünge ve çember yörüngesinde elektrik ya da manyetik alan türü", ["FİZ.11.2.2", "FİZ.11.2.8"], "yüklü parçacığa manyetik alanın uyguladığı kuvvet programda ayrı çıktı değil (yalnız FİZ.11.2.8 notu)", None, "none", [],
      3, 3, 0, "ex", "iki bölge için alan türü ve yönü çiftleri (elektrik/manyetik, sembol ve ok yönü)", "Çembersel yörünge manyetik alanı gösterir; kuvvet yönü ve yük işaretinden alan sembolü çıkarılır; düz yörünge için uyumlu alan türü seçilir",
      "Pozitif yüklü parçacığın birinci bölgede düz, ikincisinde çembersel gittiği bilinirken iki bölgedeki alanın türü ve yönü için olası çift seçiliyor.",
      "no", "Hareketli yüke etki eden manyetik kuvvet ve çembersel yörünge programda yok; yalnız alan yönü ve yük işareti ilişkisi var.", "MEDIUM"),
    Q(2022, "AYT", 6, "Compton olayında saçılan fotonun hız, momentum ve dalga boyu değişimi", [], "12. sınıf FİZ.12.4.2 (foton kavramı; Compton olayı programda anılmıyor)", None, "none", [],
      3, 2, 0, "", ROMAN, "Işık hızı değişmez; enerji kaybı momentumu azaltır, dalga boyu artar",
      "X-ışını fotonlarının serbest elektronlardan saçılmasında saçılan fotonun hız, momentum ve dalga boyunun gelene göre azalıp azalmadığı öncüllerle soruluyor.",
      "no", "Compton olayı 11-12. sınıf programında yok; foton kavramı 12. sınıfta.", "MEDIUM"),
    Q(2022, "AYT", 7, "Transformatörün uçlarının 110 V cihaz ve 220 V prize bağlanması", ["FİZ.11.2.13"], "", "transformer-turns-voltage-current-ratio", "partial", ["FBAB8"],
      2, 3, 0, "dl", "uç eşleştirme dizileri (K, L, M, N için 1-4 kablo permütasyonları)", "220 V'u 110 V'a indirmek için çok sarımlı bobin primerdir (prize), az sarımlı sekonderdir (cihaza); uç harfleri şekle göre eşleşir",
      "Sarım sayıları arasında iki kat fark olan hazır bir transformatörün K, L, M, N uçlarının 110 V cihaz kabloları ile prize hangi sırayla bağlanacağı soruluyor.",
      "yes", "Alçaltıcı transformatörün yapısı ve primer-sekonder ilişkisi hesapsız yorum düzeyinde programda var.", "MEDIUM"),
    Q(2022, "AYT", 8, "Dönen hedef tahtasında farklı yarıçaplardaki oklar: çizgisel ve açısal sürat", ["FİZ.11.1.10"], "", "circular-kinematics", "exact", ["FBAB10"],
      1, 2, 0, "dl", "iki sütunlu sıralama şıkları (vK = vL = vM … vM > vL > vK; ωK = ωL = ωM …)", "Aynı cisim üzerindeki noktaların açısal hızı eşit; v = ωr olduğundan yarıçap büyüdükçe çizgisel sürat büyür",
      "Sabit açısal hızla dönen hedef tahtasında merkeze farklı uzaklıkta saplanan K, L, M oklarının çizgisel süratleri ve açısal süratleri arasındaki ilişkiler soruluyor.",
      "yes", "Çizgisel sürat, açısal hız ilişkisi programda doğrudan var; hesap gerekmiyor.", "HIGH"),
    Q(2022, "AYT", 9, "Eliptik yörüngede Yerküre'nin iki konumunda açısal momentum ve çizgisel hız", [], "programda yok (kütle çekim ve eliptik yörünge; açısal momentum korunumu 12. sınıf FİZ.12.1.6 dönme bağlamında)", None, "none", [],
      3, 2, 0, "", "iki sütunlu şıklar (LA = LB, vA < vB … )", "Merkezî kuvvet torksuzdur: açısal momentum korunur; yarıçap büyük olan konumda çizgisel hız küçüktür",
      "Güneş çevresinde eliptik yörüngedeki Yerküre'nin Güneş'e uzak ve yakın iki konumunda Güneş-Yerküre sisteminin açısal momentumu ile çizgisel hız büyüklükleri karşılaştırılıyor.",
      "no", "Kütle çekim ve Kepler yasaları 9-12. sınıf programında yok; açısal momentum 12. sınıf.", "HIGH"),
    Q(2022, "AYT", 10, "Yaya bağlı cismin basit harmonik hareketinde ivme, esneklik potansiyel enerjisi ve kuvvet-hız yönü", [], "programda yok (basit harmonik hareket; yay potansiyel enerjisi 12. sınıf FİZ.12.2.3)", None, "none", [],
      3, 2, 0, "", ROMAN, "Sürat en küçükken (uç noktada) ivme ve potansiyel enerji en büyüktür; yay kuvveti hareket boyunca hızla hep ters yönlü değildir",
      "Sürtünmesiz düzlemde yaya bağlı cismin salınımında süratin en düşük olduğu andaki ivme ve potansiyel enerji ile kuvvet ve hızın yönleri öncüllerle sınanıyor.",
      "no", "Basit harmonik hareket yeni programda yok; yay potansiyel enerjisi 12. sınıf FİZ.12.2.3.", "MEDIUM"),
    Q(2022, "AYT", 11, "Doppler etkisinin gözlenebildiği dalga türleri", [], "programda yok (Doppler olayı; dalga türleri 10. sınıf FİZ.10.4.3, elektromanyetik dalga 12. sınıf FİZ.12.3.5)", None, "none", [],
      2, 1, 0, "", ROMAN, "Doppler etkisi kaynağa ve alıcıya göre hareketle her dalga türünde (mekanik ve elektromanyetik) gözlenir",
      "Kaynak ile alıcı arasındaki göreli hareketle frekansın farklı algılanması tanımı verilip enine, boyuna ve elektromanyetik dalgalardan hangilerinde bunun görülebileceği soruluyor.",
      "no", "Doppler etkisi yeni 9-12. sınıf programında yok.", "HIGH"),
    Q(2022, "AYT", 12, "Standart modelde Higgs bozonuyla etkileşen parçacıklar", [], "12. sınıf FİZ.12.4.6", None, "none", [],
      2, 1, 0, "", ROMAN, "Higgs alanıyla etkileşen kütleli parçacıklar (elektron, kuarklar) ile kütlesiz foton ayrılır",
      "Higgs bozonu ile kütle kazanma bilgisi verilip foton, elektron ve yukarı kuarktan hangilerinin Higgs bozonuyla etkileştiği soruluyor.",
      "no", "Standart model 12. sınıf (FİZ.12.4.6) konusu.", "HIGH"),
    Q(2022, "AYT", 13, "Özel görelilik kuramının postülaları", [], "programda yok (özel görelilik postülaları; 12. sınıf yalnız kütle-enerji eşdeğerliğini anar)", None, "none", [],
      2, 1, 0, "", ROMAN, "Işık hızı gözlemciden ve kaynaktan bağımsız sabittir; fizik yasaları eylemsiz gözlemcilere göre aynıdır",
      "Özel göreliliğin dayandığı varsayımlardan ışık hızının gözlemci ve kaynak hareketinden bağımsızlığı ile fizik yasalarının gözlemciye bağlılığı yargılarının doğruluğu soruluyor.",
      "no", "Özel görelilik 9-12. sınıf programında yok.", "HIGH"),
    Q(2022, "AYT", 14, "Tıbbi görüntülemede MR, ultrason ve tomografinin dalga türleri", [], "12. sınıf FİZ.12.3.7 (ve FİZ.12.3.5)", None, "none", [],
      2, 2, 0, "dl", ROMAN, "Metal yasağı manyetik alana, zararlı ışın X-ışınına, dalga kullanmama ultrasona işaret eder; yöntemler eşleştirilir",
      "Üç kişinin görüntüleme cihazına dair ipuçlarından (metal yasağı, zararlı ışın, elektromanyetik dalga yokluğu) hangi yöntem hangi kişiye ait olabilir sorgulanıyor.",
      "no", "Dalga kullanan görüntüleme cihazları 12. sınıf (FİZ.12.3.7) konusu.", "MEDIUM"),
]

# ============================ 2023 AYT (14/14 okundu) ============================
ITEMS += [
    Q(2023, "AYT", 1, "Köpeğin ve kişinin yer değiştirmesi: yön okuna göre vektör toplama", [], "9. sınıf FİZ.9.2.3-4 (vektör toplama, yer değiştirme)", None, "none", [],
      1, 2, 1, "ms dl", "mesafe+yön çiftleri (50√2 m Kuzey … 100√2 m Kuzeydoğu)", "Köpeğin toplam yer değiştirmesinden kişinin aldığı yol çıkarılır; geriye kalan vektörün büyüklüğü ve yönü şekildeki okla eşleşir",
      "Kuzeydoğuya ve sonra batıya giden köpeğin bulunduğu noktaya, batıya koşarak yarı yolda kalan kişinin ulaşması için gereken en kısa yol ve yön soruluyor.",
      "no", "Yer değiştirme ve vektör toplama 9. sınıf konusu; 11. sınıf çıktısı değil.", "HIGH"),
    Q(2023, "AYT", 2, "Tepsi ve meyve suyu kutusunun birlikte itilmesi: kutunun ivmesinden uygulanan kuvvet", ["FİZ.11.1.5"], "", "connected-bodies-same-acceleration", "exact", ["KB2.14"],
      2, 2, 2, "ms dl", NUM, "Bitişik iki cisim aynı ivmeyle gider; itme kuvveti toplam kütle ile ortak ivmenin çarpımıdır",
      "Sürtünmesiz masada bitişik duran tepsiye uygulanan sabit kuvvetle iki cisim birlikte hareket ederken kutunun ivmesi verilip uygulanan kuvvet isteniyor.",
      "yes", "Aynı ivmeli bağlı/temaslı cisimler ve F=ma programda doğrudan var; sayısal hesap kapsamda.", "HIGH"),
    Q(2023, "AYT", 3, "Hız-zaman grafiğinden iki otomobilin hareketinin yorumu", [], "10. sınıf FİZ.10.1.3 (hareket grafikleri); 9. sınıf FİZ.9.2.6-7", None, "none", [],
      1, 2, 1, "gr dl", ROMAN, "Eğim ivmeyi, işaret yönü, grafik altındaki alan yer değiştirmeyi verir; iki aracın alanı eşit çıkar",
      "Aynı noktadan kalkan iki aracın hız-zaman grafiği veriliyor; hızlanma-yavaşlama, geri dönüş ve konum karşılaştırması yargıları grafik okunarak sınanıyor.",
      "no", "Doğrusal hareket grafikleri 10. sınıf konusudur; 11. sınıfta yeni çıktı sayılmaz.", "HIGH"),
    Q(2023, "AYT", 4, "Esnek olmayan çarpışmada bloğa saplanan bilye sayısı", [], "12. sınıf FİZ.12.1.4 (momentumun korunumu)", None, "none", [],
      2, 1, 2, "ms ex", NUM, "Çarpışma öncesi toplam momentum sonrası toplam momentuma eşitlenir; bilye sayısı denklemden bulunur",
      "Oyun hamuru bloğa hızla atılan demir bilyeler saplanıyor; bloğun ortak son hızı verilerek kaç bilyenin atıldığı hesaplatılıyor.",
      "no", "Momentum korunumu 12. sınıf (FİZ.12.1.4) konusu.", "HIGH"),
    Q(2023, "AYT", 5, "Döner kapıda kuvvet ve kol uzunluğuna göre dönme durumu", [], "12. sınıf FİZ.12.1.1 (tork)", None, "none", [],
      2, 3, 1, "dl", ROMAN, "Her kuvvetin dönme eksenine göre torku (kuvvet × kol, yönüyle) bulunur; net tork sıfır değilse kapı döner",
      "Eksene uzaklıkları farklı kulplara iki kişinin itme-çekme kuvvetleri uygulandığında hangi durumlarda kapının dönmeyeceği tork toplamı ile sorgulanıyor.",
      "no", "Tork ve dönme dengesi 12. sınıf (FİZ.12.1.1) konusu.", "HIGH"),
    Q(2023, "AYT", 6, "Ampermetre ibresinin sapmasını artıran değişiklikler (mıknatıs kutup şiddeti ve aralığı)", ["FİZ.11.2.9", "FİZ.11.2.8"], "", "loop-rotation-torque", "exact", ["KB2.15"],
      2, 2, 0, "dl ex", ROMAN, "Akım sabitken manyetik kuvvet B ile artar; güçlü mıknatıs ve daha dar aralık B'yi büyütür, geniş aralık küçültür",
      "Mıknatıs kutupları arasındaki tel çerçeve akım geçince dönüp ibreyi saptırıyor; akım sabitken sapmanın artması için kutup şiddeti ve aralıkta yapılacak değişiklikler değerlendiriliyor.",
      "yes", "Galvanometre/motor ilkesi ve F=BIL'in alana bağlılığı programda hesapsız yorum düzeyinde var.", "HIGH"),
    Q(2023, "AYT", 7, "Fotoğraf flaş devresi: pil, sığaç ve ampul ile ilgili yargılar", [], "programda yok (sığaç, yük depolama ve enerji; 9-12. sınıf programında anılmıyor)", None, "none", [],
      3, 2, 0, "dl", ROMAN, "Sığaç enerjiyi depolar; sığa pil gerilimine bağlı değildir, büyük sığaç daha çok enerji ve yük tutar, boşalırken yük azalır",
      "Pil, sığaç, anahtar ve ampulden oluşan flaş devresinde pil gerilimi ile sığaç büyüklüğünün etkisi ve boşalma sırasındaki yük değişimi yargılanıyor.",
      "no", "Sığaç ve elektriksel enerji depolama 9-12. sınıf programında yok.", "MEDIUM"),
    Q(2023, "AYT", 8, "İdeal olmayan transformatörde primer ve sekonderde gerilim, güç ve sarım sayısı karşılaştırması", ["FİZ.11.2.13"], "", "transformer-transmission-loss", "partial", ["FBAB8"],
      3, 2, 0, "", ROMAN, "Yükseltici mi alçaltıcı mı bilinmediğinden gerilim ve sarım için kesin yargı verilemez; kayıp nedeniyle primer güç sekonder güçten büyüktür",
      "Primer ve sekonderi bilinmeyen sarım oranlı ideal olmayan transformatörde hangi niceliğin primerde kesinlikle büyük olduğu, gerilim, güç ve sarım sayısı üzerinden soruluyor.",
      "yes", "Transformatörün kayıpları ve yükseltici/alçaltıcı ayrımı hesapsız yorumlanır; program ile uyumlu.", "HIGH"),
    Q(2023, "AYT", 9, "Frekans artınca K, L, M devre elemanlarının direncindeki değişimden eleman türü", [], "programda yok (bobin ve sığacın alternatif akımdaki direnci/empedansı)", None, "none", [],
      3, 3, 0, "ex", "eleman sıralama çiftleri (K, L, M için direnç/sığaç/bobin permütasyonları)", "Frekansla direnci artan bobin, azalan sığaç, değişmeyen dirençtir; gözlemler elemanlarla eşleştirilir",
      "Gerilim frekansı artırıldığında üç elemandan birinin direnci arttı, biri değişmedi, biri azaldı; bu gözlemlerden elemanların bobin, sığaç ya da direnç olduğu eşleştiriliyor.",
      "no", "Bobin, sığaç ve empedans yeni programda yer almıyor; alternatif akım yalnız üretim ve etmenleri düzeyinde.", "HIGH"),
    Q(2023, "AYT", 10, "Düzgün çembersel hareketli cam bilye ile yaydaki bilyenin hareketinin karşılaştırılması", ["FİZ.11.1.9"], "basit harmonik hareket programda yok; iş-enerji 10. sınıf FİZ.10.2.1", "circular-velocity-direction", "partial", ["KB2.16.3"],
      3, 2, 0, "", ROMAN, "Çembersel harekette sürat sabit ve ivme hıza diktir; yay hareketinde ikisi de geçerli değildir; periyotta net kuvvetin işi iki harekette de sıfırdır",
      "İpteki düzgün çembersel hareketle yaydaki salınım yapan bilyenin sürat, ivme-hız ilişkisi ve bir periyottaki net iş bakımından hangi yargıların ikisi için de geçerli olduğu aranıyor.",
      "form_changes", "Çembersel hareket öncülleri kapsamda, salınım bağlamı programda yok; ikinci hareket başka bir çembersel harekete çevrilirse uygun olur.", "MEDIUM"),
    Q(2023, "AYT", 11, "İp üzerinde yürüyen cambazın dengesi ve eylemsizlik momenti", [], "12. sınıf FİZ.12.1.5 (eylemsizlik momenti)", None, "none", [],
      2, 2, 0, "dl", ROMAN, "Dönmeye karşı direnç, kütlenin eksenden uzaklaşmasıyla artar; uzun sırık ve uçlara yerleştirilen ağırlık eylemsizlik momentini büyütür",
      "Sırık kullanarak ip üzerinde dengede kalmaya çalışan cambaz için uzunluk, uçlara ağırlık bağlama ve kütle değişiklikleriyle dengenin kolaylaşıp kolaylaşmayacağı eylemsizlik momenti ile soruluyor.",
      "no", "Eylemsizlik momenti 12. sınıf (FİZ.12.1.5) konusu.", "HIGH"),
    Q(2023, "AYT", 12, "Gezegen halkasındaki yakın ve uzak parçacıkların çizgisel sürat, periyot ve çekim kuvveti karşılaştırması", [], "programda yok (kütle çekim ve yörünge hareketi; çembersel hareket kinematiği 11.1.10 yalnız bağlam)", None, "none", [],
      3, 2, 0, "", "beş nicelik seçeneği (çizgisel sürat, periyot, açısal sürat, merkezcil ivme, çekim kuvveti)", "Yarıçap küçüldükçe yörünge periyodu kısalır, sürat ve açısal sürat artar; hangi nicelik yakındaki parçacıkta daha küçük aranır",
      "Gezegeni çevreleyen halkada yakın ve uzak iki parçacık çembersel yörüngede kabul edilip beş niceliğinden hangisinin yakındaki parçacıkta daha küçük olduğu soruluyor.",
      "no", "Kütle çekim ve Kepler tipi yörünge ilişkileri 9-12. sınıf programında yok.", "MEDIUM"),
    Q(2023, "AYT", 13, "Basit sarkaç hedefinin periyodu ile yatay giden okun sabit hızlı hareketinin eşleştirilmesi", [], "programda yok (basit sarkaç / basit harmonik hareketin periyodu); ok hareketi 10. sınıf FİZ.10.1.1", None, "none", [],
      2, 2, 1, "ms dl", NUM, "Okun aldığı yoldan geçen süre bulunur; denge noktasına ilk varış çeyrek periyoda karşılık geldiğinden periyot dört katıdır",
      "Salınan hedef uç noktadan geçerken atılan sabit hızlı ok denge noktasında hedefi vuruyor; okun yol ve hızından geçen süre hesaplanıp hedefin periyodu isteniyor.",
      "no", "Basit harmonik hareket yeni programda yok; sabit hızlı hareket 10. sınıf konusu.", "HIGH"),
    Q(2023, "AYT", 14, "Dairesel su dalgalarının girişim desenindeki noktalarda genliklerin karşılaştırılması", [], "12. sınıf FİZ.12.3.2 (dairesel su dalgalarında girişim)", None, "none", [],
      2, 3, 0, "ex", "sıralama şıkları (AI = AII = AIII … AIII > AI > AII)", "Tepe-tepe ya da çukur-çukur çakışan noktalar yapıcı, tepe-çukur çakışanlar yıkıcı girişim verir; genlikler dalga çemberlerinin kesişiminden okunur",
      "Eş zamanlı iki kaynaktan yayılan dairesel dalgaların üstten görünüşünde üç işaretli noktada çember kesişimlerine bakılarak titreşim genliklerinin sıralanması isteniyor.",
      "no", "Su dalgalarında girişim 12. sınıf (FİZ.12.3.2) konusu.", "HIGH"),
]

# ============================ 2024 AYT (14/14 okundu) ============================
ITEMS += [
    Q(2024, "AYT", 1, "Yüzücüler ve antrenörün aynı yönde sabit hızlarla hareketi: bağıl hızların karşılaştırılması", [], "9. sınıf FİZ.9.2.3 (aynı doğrultuda vektörler); hareketli referanstan bakış yalnız 11. sınıf zenginleştirmede", None, "none", [],
      2, 2, 0, "dl", "bağıl hız eşitlik ve büyüklük yargıları (A–E)", "Bir gözlemciye göre hız, iki hızın vektör farkıdır; iki yönlü bağıl hız aynı büyüklükte ama zıt yönlüdür",
      "Aynı yönde farklı sabit hızlarla giden iki yüzücü ve antrenör için hangi kişiye göre hangi bağıl hızın eşit ya da eşit büyüklükte olduğu seçiliyor.",
      "no", "Bağıl hız programda yalnız zenginleştirme önerisi; vektör işlemi 9. sınıf konusu.", "MEDIUM"),
    Q(2024, "AYT", 2, "Kütleleri çok farklı top ve kuş tüyünün hava direnci yokken serbest düşmesi", ["FİZ.11.1.1"], "", "ff-mass-independence", "exact", ["FBAB10"],
      2, 2, 0, "dl", ROMAN, "İvme g ve düşme süresi kütleden bağımsız eşittir; net kuvvet ağırlığa eşit olduğundan kütle farkında eşit olmaz",
      "Aynı yükseklikten aynı anda bırakılan çok farklı kütleli iki cisimde net kuvvet, ivme ve yere düşme süresinin eşit olup olmadığı yargılanıyor.",
      "yes", "Serbest düşmede ivmenin kütleden bağımsızlığı doğrudan çıktıda; hesap gerektirmiyor.", "HIGH"),
    Q(2024, "AYT", 3, "Eğik atış yörüngesindeki üç noktada cismin momentum büyüklüklerinin sıralanması", ["FİZ.11.1.3"], "momentum 12. sınıf FİZ.12.1.3; mekanik enerji korunumu 10. sınıf FİZ.10.2.4 (aynı yükseklikte eşit sürat)", "2d-velocity-at-point", "partial", ["FBAB10"],
      3, 2, 0, "", "sıralama şıkları (PK < PL < PM … PL < PK < PM)", "Momentum kütle çarpı sürattir; tepede sürat en küçük, daha alçak noktada daha büyüktür; konumlardan sıralama yapılır",
      "Yatayla açılı fırlatılan cismin yörüngesinde çıkış, tepe ve iniş evresindeki üç noktanın yüksekliklerine bakılarak çizgisel momentum büyüklüklerinin sıralaması isteniyor.",
      "form_changes", "Yörüngede hız büyüklüğü yorumu kapsamda; momentum terimi 12. sınıf, soru sürat sıralaması olarak yeniden yazılmalı.", "MEDIUM"),
    Q(2024, "AYT", 4, "Ağır bloğu eğik düzlemde sabit hızla çıkarmanın yoldan, kuvvetten ve işten kazancı", [], "10. sınıf FİZ.10.2.1-2 (iş ve enerji); eğik düzlemde kuvvet bileşenleri 11. sınıf FİZ.11.1.5 yalnız ön bilgi", None, "none", [],
      2, 2, 0, "dl", ROMAN, "Kuvvetten kazanç yoldan kayıpla gelir; sürtünmesiz düzende yapılan iş değişmez; yoldan kazanç yoktur",
      "Ağır bir taşı doğrudan kaldırmak yerine eğik düzlemde çekmenin yoldan kazanç, daha küçük kuvvet ve daha az iş sağlayıp sağlamadığı öncüllerle sorgulanıyor.",
      "no", "Makine kazançları iş-enerji bağlamında 10. sınıfta işlenir; 11. sınıf çıktısı değil.", "MEDIUM"),
    Q(2024, "AYT", 5, "Doğrusal dizili noktasal yüklerin L ve N noktalarında elektriksel potansiyellerinin oranı", [], "programda yok (noktasal yükün elektriksel potansiyeli; 11. sınıf yalnız elektriksel alan ve kuvvet)", None, "none", [],
      2, 2, 2, "ms", NUM, "Her yükün katkısı k·q/r olarak skaler toplanır; L ve N'de uzaklıklar eşit aralıklardan bulunarak oran alınır",
      "Eşit aralıklı K, M, P noktalarındaki pozitif ve negatif yüklerin L ve N noktalarında oluşturduğu elektriksel potansiyellerin oranı hesaplatılıyor.",
      "no", "Elektriksel potansiyel 9-12. sınıf programında yok; Coulomb ve alan hesapsız.", "HIGH"),
    Q(2024, "AYT", 6, "Düzgün manyetik alanda yörüngeleri verilen K, L, M, N parçacıklarının yük işaretleri", ["FİZ.11.2.8"], "yüklü parçacığa manyetik alanın uyguladığı kuvvet programda ayrı çıktı değil (yalnız FİZ.11.2.8 notu)", None, "none", [],
      3, 3, 0, "", "yük işareti dizileri (K, L, M, N için nötr, + ve −)", "Doğru giden parçacık yüksüzdür; eğrilme yönü yük işaretini belirler; alanın yönü sabit olduğundan zıt eğrilenler zıt yüklüdür",
      "Sayfaya dik alana giren dört parçacığın düz ya da yarım çember çizen yörüngelerinden yük işaretlerinin hangi eşleştirmede doğru olabileceği seçiliyor.",
      "no", "Hareketli yüke etki eden manyetik kuvvet ve çembersel yörünge programda yok.", "MEDIUM"),
    Q(2024, "AYT", 7, "Seri RLC devresinde rezonans frekansı üzerinde empedans, akım ve sığa değişimi", [], "programda yok (RLC devresi, empedans, rezonans frekansı; bobin ve sığaç)", None, "none", [],
      3, 2, 0, "", ROMAN, "Rezonansta empedans en küçük ve akım en büyüktür; frekans artırılırsa empedans artar, akım azalır; sığa frekanstan bağımsızdır",
      "Direnç, bobin ve sığacın seri bağlı olduğu devrede rezonans frekansından sonra frekans artırılırsa empedans, etkin akım ve sığanın değişimi yargılanıyor.",
      "no", "RLC devreleri ve rezonans yeni programda yok; alternatif akım yalnız üretim ve etmenleri düzeyinde.", "HIGH"),
    Q(2024, "AYT", 8, "Stadyumda farklı yarıçaplı kulvarlarda sabit süratle koşan üç sporcunun açısal hızları", ["FİZ.11.1.10"], "", "circular-kinematics", "exact", ["FBAB10"],
      2, 3, 1, "ms dl", "açısal hız sıralama şıkları (wK > wL > wM … wM > wK = wL)", "Başlangıç noktalarından bitişe tarayılan açı ve geçen süre karşılaştırılır; ω = Δθ/Δt ile sıralama yapılır",
      "Çember kulvarların başlangıç noktaları ve bitiş çizgisi şekilde verilirken bitiş sırasından yararlanılarak üç koşucunun merkeze göre açısal hızlarının sıralaması isteniyor.",
      "yes", "Açısal hız ve çizgisel sürat ilişkisi programda doğrudan; sayısal hesap olmadan şekil yorumu yeterli.", "MEDIUM"),
    Q(2024, "AYT", 9, "Yerküre çevresinde düzgün çembersel yörüngedeki uydu: yerçekiminin işi, açısal momentum ve net kuvvet", ["FİZ.11.1.9"], "kütle çekim programda yok; açısal momentum 12. sınıf FİZ.12.1.6; iş kavramı 10. sınıf FİZ.10.2.1", "circular-analogies", "partial", ["KB2.16.3"],
      3, 2, 0, "", ROMAN, "Çekim kuvveti hıza dik olduğundan iş yapmaz; açısal momentum korunur; net kuvvet merkezcildir ve sıfır değildir",
      "Sabit süratle çembersel yörüngede dolanan uydu için çekim kuvvetinin yaptığı iş, açısal momentumun sabitliği ve net kuvvetin sıfır olması yargıları sınanıyor.",
      "form_changes", "Net kuvvet-hız ilişkisi kapsamda; uydu/kütle çekim bağlamı ve açısal momentum programda yok, bağlam değiştirilmeli.", "MEDIUM"),
    Q(2024, "AYT", 10, "Metronom çubuğunda sürgü konumuna göre salınım periyotlarının oranı", [], "programda yok (basit sarkaç benzeri salınım periyodu; basit harmonik hareket)", None, "none", [],
      2, 3, 2, "ms dl", "kökli kesir şıkları (1/√2, 1/√3, 1/2, 1/√5, 1/√6)", "Sürgü sabit noktadan ne kadar uzaksa periyot o oranın kareköküyle büyür; konum oranı birimkareli çubuktan okunur",
      "Metronomun çubuğundaki sürgü iki farklı işaretli noktaya konunca salınım periyotları oranı, sabit noktaya uzaklıkların oranından hesaplanıyor.",
      "no", "Basit harmonik hareket ve salınım periyodu yeni programda yok.", "HIGH"),
    Q(2024, "AYT", 11, "Hareketli ambulans sirenini duyan üç kişinin frekansları", [], "programda yok (Doppler olayı; dalga kavramları 10. sınıf FİZ.10.4.2-4)", None, "none", [],
      2, 3, 1, "dl", "frekans değeri şıkları (1900, 1800, 1700, 1500, 1600 Hz)", "Yaklaşılan gözlemci yüksek, uzaklaşılan gözlemci düşük, ambulansta oturan ise aynı frekansı algılar",
      "Sirenin frekansı verilmişken ambulans hareket ederken içindeki kişi ile önünde ve arkasında duran iki kişinin işittiği frekanslardan doğru olanı bulunuyor.",
      "no", "Doppler olayı yeni 9-12. sınıf programında yok.", "HIGH"),
    Q(2024, "AYT", 12, "Uranyum-235 fisyonunda ürün çekirdeklerde korunan nicelikler", [], "12. sınıf FİZ.12.4.8", None, "none", [],
      3, 2, 0, "", ROMAN, "Tepkimede atom numarası ve kütle numarası korunur; nötron sayısı serbest nötronlar nedeniyle korunmayabilir",
      "Nötron yakalayan uranyum çekirdeğinin bölünmesinde ürünlerdeki atom numarası, kütle numarası ve nötron sayısı toplamlarının girenle eşit olup olmadığı soruluyor.",
      "no", "Nükleer enerji 12. sınıf (FİZ.12.4.8) konusu.", "HIGH"),
    Q(2024, "AYT", 13, "Fotoelektrik olayda Ek–f grafiğinden eşik enerjisini bulmak için gereken değerler", [], "12. sınıf FİZ.12.4.2", None, "none", [],
      3, 3, 1, "gr ex", ROMAN, "Eğim h sabitidir; eşik frekansı ve enerji eksen kesişimlerinden bulunur; hangi noktalardan biri bilinirse yeter karar verilir",
      "Doğrusal Ek–f grafiğinde üç işaretli noktanın değerlerinden hangileri bilindiğinde, başka sabit gerekmeden eşik enerjisinin bulunabileceği soruluyor.",
      "no", "Fotoelektrik olay 12. sınıf (FİZ.12.4.2) konusu.", "HIGH"),
    Q(2024, "AYT", 14, "Süper iletken özellikli reostanın direnç–sıcaklık grafiği ve ampul parlaklığı", [], "12. sınıf FİZ.12.4.5 (süper iletkenler); direnç ve reosta 10. sınıf FİZ.10.3.3-4", None, "none", [],
      3, 3, 0, "gr ms", ROMAN, "Kritik sıcaklığın altında direnç sıfırdır, sürgü konumu etkisizdir; üstünde ise direnç artar ve ampul parlaklığı değişir",
      "Direnci sıcaklıkla değişen bir malzemeden yapılmış reostanın bulunduğu devrede kritik sıcaklığın altı ve üstünde sürgü kaydırılınca ampul parlaklığı yargıları değerlendiriliyor.",
      "no", "Süper iletkenler 12. sınıf (FİZ.12.4.5) konusu; devre kısmı 10. sınıfta.", "HIGH"),
]

# ============================ 2025 AYT (14/14 okundu) ============================
ITEMS += [
    Q(2025, "AYT", 1, "Karganın bıraktığı cevizin düşerken hareket eden arabanın tamponuna çarpması: yatay uzaklık", ["FİZ.11.1.3"], "", "2d-horizontal-launch", "exact", ["FBAB10"],
      2, 3, 2, "ms dl", NUM, "Düşme süresi h'den bulunur; bu sürede aracın aldığı yol ile cevizin karşı yöndeki yatay yolu toplanarak başlangıç uzaklığı bulunur",
      "Yatay hızla uçan karganın bıraktığı ceviz yere inerken karşıdan gelen araba ile buluşuyor; belirli yükseklik ve hızlardan başlangıçtaki yatay uzaklık hesaplatılıyor.",
      "yes", "Yatay ilk hızlı iki boyutlu hareketin sayısal hesabı programda kapsamda (CALC_INCLUDED); bağlam günlük hayattan.", "HIGH"),
    Q(2025, "AYT", 2, "Doğrusal yolda K ve L anlarındaki anlık hızlardan ortalama hız büyüklüğünün bulunabilmesi için gereken bilgiler", [], "10. sınıf FİZ.10.1.2-3 (yatay doğrultuda sabit ivmeli hareket)", None, "none", [],
      2, 2, 0, "", ROMAN, "Sabit ivmede ortalama hız başlangıç ve son hızın ortalamasıdır; yön değişimi ve kütle bu hesap için belirleyici değildir",
      "Yalnız iki anlık hız bilinen otomobilin iki an arasındaki ortalama hız büyüklüğü için ivmenin sabitliği, yön değiştirmeme ve kütle bilgilerinden hangilerinin yeterli olduğu soruluyor.",
      "no", "Doğrusal sabit ivmeli hareket 10. sınıf konusu; 11. sınıfta yeni çıktı yok.", "MEDIUM"),
    Q(2025, "AYT", 3, "Aynı yayın tek elle sıkıştırılması, iki elle sıkıştırılması ve gerilmesinde esneklik potansiyel enerjisi", [], "12. sınıf FİZ.12.2.3 (yayın esneklik potansiyel enerjisi)", None, "none", [],
      2, 2, 0, "dl", "sıralama şıkları (U2 > U1 > U3 … U1 = U2 = U3)", "Dengedeki yayda uygulanan kuvvet aynıysa uzanım aynıdır; enerji uzanımın büyüklüğüne bağlıdır, yönüne ya da kaç el kullanıldığına değil",
      "Aynı büyüklükte kuvvetle bir uçtan sabit, iki uçtan sıkıştırılan ve gerilen yayın dengede depoladığı esneklik enerjileri karşılaştırılıyor.",
      "no", "Yay potansiyel enerjisi 12. sınıf (FİZ.12.2.3) konusu.", "HIGH"),
    Q(2025, "AYT", 4, "Balonla çalışan arabanın hava çıkarken ve hava bittikten sonraki hareketi", ["FİZ.11.1.4", "FİZ.11.1.5"], "", "newton3-action-reaction", "partial", ["FBAB10", "KB2.14"],
      2, 2, 0, "ex", "iki sütunlu hareket durumu şıkları (yönde hızlanır / sabit hızla gider / yavaşlar)", "Havaya uygulanan kuvvetin tepkisi arabayı ters yönde hızlandırır; hava bitince net kuvvet sıfır olur, sürtünmesiz ortamda sabit hızla gider",
      "Pipetinden hava çıkan balonlu arabanın havanın çıktığı ve bittiği iki evredeki hareket yönü ve türü, sürtünmesiz ortamda soruluyor.",
      "yes", "Etki-tepki ve eylemsizlik yorumu programda doğrudan; hesap gerekmiyor.", "HIGH"),
    Q(2025, "AYT", 5, "Eş potansiyel yüzeyler arasında yük taşınırken yapılan iş", [], "programda yok (elektriksel potansiyel, eş potansiyel yüzey ve elektriksel iş; 11. sınıf yalnız alan ve kuvvet)", None, "none", [],
      2, 3, 2, "ms gr", NUM, "İş yükle potansiyel farkın çarpımıdır; iki noktanın yola bağlı olmadan potansiyel farkı okunur ve oranlanır",
      "Potansiyel değerleri işaretli eş potansiyel çizgilerinde, verilen yükle yapılan işten yola başka bir yükü taşımak için yapılan iş W cinsinden hesaplatılıyor.",
      "no", "Elektriksel potansiyel ve elektriksel iş 9-12. sınıf programında yok.", "HIGH"),
    Q(2025, "AYT", 6, "Bölgelerden geçen elektronun yön değiştirmesine neden olan alanın türü ve yönü", ["FİZ.11.2.2", "FİZ.11.2.8"], "yüklü parçacığa manyetik alanın uyguladığı kuvvet programda ayrı çıktı değil (yalnız FİZ.11.2.8 notu)", "efield-charged-particle-deflection", "partial", ["FBAB10"],
      3, 3, 0, "ex", "alan türü ve yön çiftleri (düzleme paralel ya da dik; elektrik ya da manyetik)", "Negatif yüke elektrik kuvveti alana ters yönlüdür; yön değişiminin eğrisinden elektrik ya da manyetik alan seçilir, manyetik seçenekte sağ el kuralı ve yük işareti kullanılır",
      "Kırmızı bölgeye giren elektronun yörüngesinin bir tarafa sapması bilinirken orada hangi alan türü ve yönünün olabileceği seçeneklerden aranıyor.",
      "no", "Hareketli yüke etki eden manyetik kuvvet 11. sınıf çıktısı değil; yalnız elektrik alanda yüklü parçacık sapması kapsamda.", "MEDIUM"),
    Q(2025, "AYT", 7, "Bobin ve sığaç içeren alternatif akım devrelerinde ampul parlaklığının karşılaştırılması", [], "programda yok (bobin ve sığacın alternatif akımdaki davranışı; empedans)", None, "none", [],
      3, 3, 0, "dl ex", ROMAN, "Bobin ve sığaç alternatif akıma frekansa bağlı direnç gösterir; sığaç doğru akımı keser, devreye seri bağlandığında ampul parlaklığı değişir ya da söner",
      "Yalnız ampul ve kaynaktan oluşan devredeki parlaklıkla, bobin ve sığaç eklenmiş üç farklı devredeki parlaklıklardan hangilerinin aynı olabileceği soruluyor.",
      "no", "Bobin, sığaç ve alternatif akım devre analizi yeni programda yok.", "HIGH"),
    Q(2025, "AYT", 8, "Roketle fırlatılan kapsülün üç çembersel yörüngedeki ortalama süratlerinin karşılaştırılması", [], "programda yok (kütle çekim altında çembersel yörünge; yörünge sürati yarıçap ilişkisi)", None, "none", [],
      3, 2, 0, "ms", "sıralama şıkları (vK = vL = vM … vM > vK = vL)", "Yörünge yarıçapı arttıkça çekim altındaki çembersel yörünge sürati azalır; yükseklikler karşılaştırılıp sürat sıralanır",
      "Yerküre çevresinde 200, daha yüksek ve 400 km civarında üç yörüngede dolanan kapsülün sürat sıralaması, yörünge yüksekliklerinden yorumlanarak aranıyor.",
      "no", "Kütle çekim ve yörünge hareketi 9-12. sınıf programında yok.", "MEDIUM"),
    Q(2025, "AYT", 9, "Yerküre'nin eliptik yörüngesinde alan, açısal momentum ve enerji yargıları", [], "programda yok (Kepler yasaları ve kütle çekim; açısal momentum 12. sınıf FİZ.12.1.6)", None, "none", [],
      3, 3, 0, "dl", ROMAN, "Eşit sürelerde eşit alan taranır; günberiden günötesine açısal momentum korunur, enerji toplamı sabittir; öncüller konumlara bakılarak sınanır",
      "Güneş çevresindeki eliptik yörüngede dört konumun uzaklık sıralaması verilerek taranan alanlar, açısal momentum ve enerji toplamıyla ilgili yargılar değerlendiriliyor.",
      "no", "Kepler yasaları ve kütle çekim programda yok; açısal momentum 12. sınıf konusu.", "HIGH"),
    Q(2025, "AYT", 10, "Basit harmonik harekette uzanım artarken ivme, hız ve net kuvvet değişimi", [], "programda yok (basit harmonik hareket)", None, "none", [],
      2, 1, 0, "", ROMAN, "Uzanım büyüdükçe geri çağırıcı kuvvet ve ivme artar, hız azalır; azalan nicelik aranır",
      "Denge noktasından uzanımı büyüyen titreşimde ivme, hız ve net kuvvetten hangilerinin büyüklüğünün azaldığı öncüllerle soruluyor.",
      "no", "Basit harmonik hareket yeni programda yok.", "HIGH"),
    Q(2025, "AYT", 11, "Işığın tek yarıkta kırınımının girişimdeki gibi aydınlık-karanlık desen vermesinin nedeni", [], "12. sınıf FİZ.12.3.4 (ışıkta kırınım)", None, "none", [],
      2, 2, 0, "ex", "beş kavramsal açıklama seçeneği (kaynak sayısı, yarık genişliği, frekans, dalga boyu, sapma)", "Yarığın her noktası ikincil kaynak gibi davranır; bu kaynaklar birbiriyle girişim yaparak desen oluşturur",
      "Tek yarıktan geçen ışıkta ikinci bir kaynak olmadan da girişime benzer desen oluşmasının ışığın hangi davranışından kaynaklandığı seçeneklerden bulunuyor.",
      "no", "Işığın kırınımı 12. sınıf (FİZ.12.3.4) konusu.", "HIGH"),
    Q(2025, "AYT", 12, "Atom çekirdeğinden yayınlanan en yüksek enerjili elektromanyetik dalga", [], "12. sınıf FİZ.12.3.5", None, "none", [],
      1, 1, 0, "dl", "dalga türü adları (radyo, X, kızılötesi, mikrodalga, gama)", "Çekirdekten kaynaklanan ve tayfın en enerjili ucundaki dalga gama ışınlarıdır",
      "Süpernovadan gelen ve atom çekirdeğinden yayınlandığı bilinen en yüksek enerjili elektromanyetik dalganın türü seçeneklerden bulunuyor.",
      "no", "Elektromanyetik tayf 12. sınıf (FİZ.12.3.5) konusu.", "HIGH"),
    Q(2025, "AYT", 13, "Doğadaki temel kuvvetlerin etkilediği sistemlerle eşleştirilmesi", [], "9. sınıf FİZ.9.2.5 (doğadaki temel kuvvetler)", None, "none", [],
      1, 2, 0, "tb", "üçlü eşleştirme (X, Y, Z için kütle çekim, elektromanyetik, güçlü çekirdek)", "Gök cisimlerini bir arada tutan kütle çekim, atomdaki elektron-proton kuvveti elektromanyetik, çekirdekteki protonları tutan güçlü çekirdek kuvvetidir",
      "Gök cisimleri, hidrojen atomu ve helyum çekirdeği örnekleriyle üç temel kuvvet tanıtılıp hangi örneğin hangi kuvvete ait olduğu eşleştiriliyor.",
      "no", "Temel kuvvetlerin karşılaştırılması 9. sınıf (FİZ.9.2.5) konusu.", "HIGH"),
    Q(2025, "AYT", 14, "Görüntüleme cihazlarının kullandığı ses ve elektromanyetik dalgaların sınıflandırılması", [], "12. sınıf FİZ.12.3.7 (ve FİZ.12.3.5)", None, "none", [],
      2, 2, 0, "dl tb", "iki sütunlu cihaz eşleştirme (ses dalgası kullanan / elektromanyetik dalga kullanan)", "Ultrason ve sonar ses, röntgen, tomografi ve termal kamera elektromanyetik dalgalarla çalışır; her şıkta bir cihaz iki sütundan doğru yerleştirilir",
      "Röntgen, ultrason, tomografi, sonar ve termal kameradan hangisinin ses, hangisinin elektromanyetik dalgayla görüntü oluşturduğunu gösteren doğru eşleştirme aranıyor.",
      "no", "Dalga kullanan görüntüleme cihazları 12. sınıf (FİZ.12.3.7) konusu.", "HIGH"),
]


# ============================ TYT 2018–2025: optik ve 11. sınıf çıktılarına denk gelen fizik soruları ============================
# Kapsam: TYT Fen Bilimleri testinin Fizik bölümü (1-7). Yalnız optik (ışık, aydınlanma, ayna, kırılma, mercek, renk) ve
# 11. sınıf Maarif çıktılarına denk gelen (Newton yasaları, sürtünme, elektriksel kuvvet) sorular kaydedilmiştir; diğerleri (ısı, basınç, dalga, devre vb.) kapsam dışıdır.
# Gölge ve yarı gölge: 2018–2025 TYT fizik testlerinde soru çıkmamıştır.

# ---- 2018 TYT ----
ITEMS += [
    Q(2018, "TYT", 5, "İtme-çekme gözleminden üç iletken kürenin yük işaretlerinin çıkarılması", ["FİZ.11.2.1"], "", "coulomb-direction-newton3", "partial", ["FBAB10"],
      1, 1, 0, "", "üçlü işaret kombinasyonları (K, L, M için Pozitif/Negatif)", "Aynı cins yükler iter, zıt cinsler çeker: K ile L aynı işaretli, L ile M zıt işaretli olmalıdır",
      "Nötr olmayan üç iletken kürede K'nin L'yi ittiği, L'nin M'yi çektiği gözleminden yüklerin işaretlerinin hangi kombinasyon olabileceği soruluyor.",
      "yes", "Elektriksel kuvvetin yönü (itme-çekme) FİZ.11.2.1 kapsamında; sayısal Coulomb hesabı yok, program da hesabı dışlıyor.", "HIGH"),
    Q(2018, "TYT", 6, "Işık şiddeti, ışık akısı ve aydınlanmadan hangilerinin kaynağa uzaklıkla değiştiği", ["FİZ.11.3.1"], "", "lum-concept-definitions", "exact", ["FBAB8"],
      2, 1, 0, "", ROMAN, "Işık şiddeti ve toplam akı kaynağın özelliğidir; yalnız aydınlanma (E = I/d²) kaynağa uzaklıkla değişir",
      "Birimleri (cd, lm, lüks) verilen ışık şiddeti, toplam ışık akısı ve aydınlanma niceliklerinden hangilerinin kaynağa olan uzaklığa göre değiştiği öncüllerle soruluyor.",
      "yes", "Üç niceliğin tanımı, birimi ve bağlı olduğu etmen FİZ.11.3.1 kapsamında; nitel yorum düzeyi programa uygun.", "HIGH"),
    Q(2018, "TYT", 7, "Kırılan ışının yolundan ortamların kırıcılığının karşılaştırılması ve L'den M'ye geçişte olası yollar", ["FİZ.11.3.5"], "", "rf-ray-path-media-comparison", "exact", ["FBAB7"],
      3, 2, 0, "ms gr", "dört ışın yolu (I–IV) kombinasyonları (Yalnız I … II, III ve IV)", "İki şekilden n_L > n_M > n_K bulunur; L'den M'ye geçişte ışık normalden uzaklaşır, büyük gelme açısında sınır açısı ve tam yansıma da olabilir",
      "K ortamından L ve M ortamlarına geçen ışının iki kırılma şeklinden ortamların kırıcılığı karşılaştırılıyor; L'den M'ye geçişte izlenebilecek yollar (kırılma, sınır, yansıma) seçiliyor.",
      "yes", "Snell yasasının nitel kullanımı, sınır açısı ve tam yansıma FİZ.11.3.5 kapsamındadır; formül gerekmiyor.", "HIGH"),
]

# ---- 2019 TYT (optik: S6, S7 okundu; S1–S5 kapsam dışı: yoğunluk, çembersel yolda yer değiştirme/hız, iş-güç, genleşme, devre) ----
ITEMS += [
    Q(2019, "TYT", 6, "Noktasal kaynak aynı uzaklıkta kalıp eğik konuma gelince perdedeki bölgeden geçen ışık akısının değişimi", ["FİZ.11.3.1"], "", "illum-oblique-angle", "partial", ["FBAB8"],
      2, 2, 0, "", ROMAN, "Kaynak–perde uzaklığı sabit kalsa da ışınlar bölgeye eğik gelince akı azalır; bölge büyüyünce daha fazla ışık geçer, akı artar",
      "Noktasal kaynak yarım çemberin K noktasından L noktasına getirilince perdedeki küçük dikdörtgenden geçen ışık akısının azalıp azalmadığı ve bölge büyütülünce artıp artmadığı soruluyor.",
      "yes", "Işık akısı ve aydınlanmanın uzaklık ve eğimle nitel yorumu FİZ.11.3.1 kapsamında; sayısal hesap gerekmiyor.", "MEDIUM"),
    Q(2019, "TYT", 7, "Sarı far ışığında tabelanın boya rengiyle fark edilebilirliği (ışık ve boya renk karışımı şemaları)", [], "12. sınıf FİZ.12.3.6 (ana ışık renkleri); boya karışımı ve cismin rengi programda yok", None, "none", [],
      2, 3, 0, "dl", "tek renk seçenekli (mavi, sarı, yeşil, kırmızı, cyan)", "Sarı far ışığı kırmızı ve yeşil ışık içerir; mavi boya bunları yansıtmaz, siyah görünür ve siyah fonla karışır",
      "Sarı ışık yayan farlarla aydınlatılan siyah fonlu tabelanın harfleri hangi renkte boyanırsa farkın en az algılanacağı, verilen ışık ve boya renk şemalarından çıkarılıyor.",
      "no", "Işık renkleri 12. sınıf (FİZ.12.3.6); boya ve cisim rengi bağlamı Maarif 9-12. sınıf programında yer almıyor.", "MEDIUM"),
]

# ---- 2020 TYT (S2 Newton, S7 düzlem ayna okundu; S1 birim, S3 kaldırma, S4 basınç/ısı, S5 devre, S6 telde dalga kapsam dışı) ----
ITEMS += [
    Q(2020, "TYT", 2, "Freni bozuk otomobilin çöp kovasına çarpmasında kuvvet, ivme ve hız değişimi yorumları", ["FİZ.11.1.4"], "", "newton3-action-reaction", "partial", ["FBAB10"],
      2, 2, 0, "dl", "üç kişinin yorumları (Ahmet, Burçin, Cevdet); şıklar yorum kombinasyonları", "Etki-tepki kuvvetleri eşittir; kütlesi küçük kovanın ivmesi ve aynı sürede hız değişimi büyüktür",
      "Küçük kütleli kovaya çarpan otomobil için kuvvetin, ivmenin ve hız değişiminin kimde daha büyük olduğuna dair üç yorumdan hangilerinin doğru olduğu seçiliyor.",
      "yes", "Etki-tepki eşitliği ve F = ma ilişkisinin nitel yorumu FİZ.11.1.4 kapsamında; hesap gerekmiyor.", "HIGH"),
    Q(2020, "TYT", 7, "Düzlem aynada kişi ve aynanın birlikte suya batırılmasında görüntünün boyu ve uzaklığı", ["FİZ.11.3.2"], "", "pm-image-properties", "partial", ["FBAB9"],
      2, 2, 0, "dl", ROMAN, "Görüntü boyu ve ayna uzaklığı cisimle aynıdır; ayna ve kişi aynı ortamda olduğundan ortamın cinsi (hava, tatlı su, tuzlu su) görüntüyü değiştirmez",
      "Kişi aynaya önce havada, sonra aynayla birlikte suya batarak bakıyor; görüntünün boyunun, uzaklığının ve su cinsine bağlılığının değişip değişmediği öncüllerle soruluyor.",
      "yes", "Düzlem ayna görüntüsünün özellikleri FİZ.11.3.2 kapsamında; ortam değişimi bağlamı yeni duruma uyarlama (FBAB9.SB2) ruhuna uygun.", "MEDIUM"),
]

# ---- 2021 TYT (S2 net kuvvet, S7 mercek okundu; S1 yüzey gerilimi, S3 basınç, S4 ısı iletimi, S5 elektrik enerjisi, S6 telde dalga kapsam dışı) ----
ITEMS += [
    Q(2021, "TYT", 2, "Otomobil, tren ve uçağın hız bilgilerinden üzerlerindeki net kuvvetlerin büyüklüklerinin sıralanması", ["FİZ.11.1.4"], "", "net-force-motion-state", "exact", ["FBAB10"],
      2, 2, 0, "dl", "sıralama şıkları (F1, F2, F3 arasındaki >, = ilişkileri)", "Sabit hızda hareket eden araçta net kuvvet sıfırdır; hızı artan trende net kuvvet sıfırdan büyüktür",
      "Sabit hızla giden otomobil, hızlanan tren ve sabit hızla giden uçak için net kuvvet büyüklükleri karşılaştırılıyor; hareket durumundan net kuvvetin sıfır olup olmadığı çıkarılıyor.",
      "yes", "Net kuvvet ile hareket durumu arasındaki nitel ilişki FİZ.11.1.4 kapsamında; hesap yok, günlük hayat bağlamı Maarif üslubuna yakın.", "HIGH"),
    Q(2021, "TYT", 7, "Pencereden ağaç görüntüsü veren mercekten sonra ikinci özdeş mercekle aynı boyda düz görüntü için konum seçimi", ["FİZ.11.3.10", "FİZ.11.3.9"], "", "lens-image-position-properties", "partial", ["FBAB7", "KB2.7"],
      3, 3, 0, "ms ex", "ikili konum eşleştirmesi (merceğin ve kâğıdın K, L, M, N noktalarındaki yerleri)", "Uzak cismin görüntüsü odakta oluşur; ilk görüntüden 2f uzağa konan özdeş merceğin 2f ötesinde cisimle aynı boyda ters, yani düz görüntü oluşur",
      "Odakta ağaç görüntüsü veren mercek sabitken, ilk görüntüyü cisim kabul eden ikinci özdeş merceğin ve kâğıdın eşit aralıklı noktalardan hangilerine konacağı görüntü özelliklerinden çıkarılıyor.",
      "yes", "Cismin 2f ve sonsuzdaki konumuna göre görüntü yeri ve boyu FİZ.11.3.9-10 konum–özellik tablosuyla çözülür; mercek denklemi gerekmiyor.", "MEDIUM"),
]

# ---- 2022 TYT (S2 etki-tepki, S5 elektriksel kuvvet, S7 düzlem ayna okundu; S1 özkütle, S3 akışkan, S4 ısı iletimi, S6 su dalgası (10. sınıf FİZ.10.4.5) kapsam dışı) ----
ITEMS += [
    Q(2022, "TYT", 2, "Masadaki kitap için kitap–masa–Yerküre kuvvet çiftlerinden hangisinin verilenlerle bulunamayacağı", ["FİZ.11.1.4", "FİZ.11.1.5"], "", "newton3-action-reaction", "exact", ["FBAB10", "KB2.14"],
      2, 2, 1, "dl", "beş kuvvet ifadesi (hangisi çıkarılamaz tipi, olumsuz kök)", "Kitap dengede olduğundan etki-tepki çiftleri ve denge ile 10 N bulunur; masanın kütlesi bilinmediği için Yerküre'nin masaya kuvveti verilemez",
      "Dengedeki kitap için Yerküre ve masayla etkileşim kuvvetleri 10 N olarak sorulurken, masa kütlesi verilmediğinden hangi kuvvetin bulunamayacağı soruluyor.",
      "yes", "Etki-tepki çiftleri ve dengede kuvvet analizi FİZ.11.1.4-5 kapsamında; olumsuz kök ve eksik veri bağlamı beceri temelli yazıma uygun.", "HIGH"),
    Q(2022, "TYT", 5, "Pozitif yüklü taraktan asılı kalan nötr kâğıdın üst ve alt yarısındaki elektriksel kuvvetlerin yönü ve büyüklüğü", ["FİZ.11.2.1"], "kâğıdın kutuplanması (yük ayrışması) açık çıktı değil; elektriklenme çeşitleri 11. Ünite 2 temel kabulü (önceki sınıf ön bilgisi)", "coulomb-direction-newton3", "partial", ["FBAB10"],
      3, 2, 0, "ms ex", ROMAN, "Tarağa yakın uçta zıt, uzak uçta aynı işaretli yük birikir; çekim ve itme yönleri ters olur ve asılı kalan kâğıtta bileşke kuvvet ağırlığı dengeler",
      "Pozitif yüklü tarağa asılı kalan nötr kâğıdın A ve B yarılarına etki eden elektriksel kuvvetlerin yönleri ile A bölümündeki kuvvetin kütle çekim kuvvetinden büyüklüğü öncüllerle soruluyor.",
      "form_changes", "Elektriksel kuvvetin yönü ve denge FİZ.11.2.1 ve 11.1.5 ile uyumlu; yalıtkanda yük ayrışması açık çıktıda yok, bağlam olarak verilmesi gerekir.", "MEDIUM"),
    Q(2022, "TYT", 7, "Yürüyen merdivende yansıtıcı alt yüzeyden arkadaki kişiyi ve kendini görmek için bakılacak yönler", ["FİZ.11.3.2"], "", "pm-reflection-ray-paths", "partial", ["FBAB9"],
      2, 3, 0, "ms dl", "iki yönlü eşleştirme (arkadaki kişi, kendisi) şıkları (I ve II … II ve IV)", "Yansıma yasasıyla kişinin görüntüsü aynaya göre simetrik çizilir; kendini görmek için ayna yüzeyine dik yönde bakmak gerekir",
      "Düzlem ayna gibi davranan merdiven altına bakan kişinin arkadaki kişiyi ve sonra kendini görebilmesi için hangi yönlere bakacağı yansıma kuralıyla seçiliyor.",
      "yes", "Düzlem aynada yansıma yasasıyla ışın yolu ve görüntü bulma FİZ.11.3.2 kapsamında; günlük hayat modeli (alışveriş merkezi) beceri temelli.", "MEDIUM"),
]

# ---- 2023 TYT (S3 ışık şiddeti–enerji, S6 abajur, S7 Ay yüzeyi ayna sistemi okundu; S1 özkütle, S2 yer değiştirme-yol, S4 ısı aktarımı, S5 devre kapsam dışı) ----
ITEMS += [
    Q(2023, "TYT", 3, "Aynı ışık şiddetini sağlayan akkor, LED ve floresan ampullerin eşit sürede harcadığı enerjilerin karşılaştırılması", ["FİZ.11.3.1"], "", "lamp-lumen-efficiency", "partial", ["FBAB8"],
      1, 2, 1, "dl tb", "sıralama şıkları (E_I, E_II, E_III arasındaki >, = ilişkileri)", "Ampuller aynı ışık şiddetini verdiğinden fark watt değerindedir; eşit sürede enerji gücle orantılı olduğundan en az güçlü ampul en az enerji harcar",
      "Masayı aynı ışık şiddetiyle aydınlatan üç ampulün watt değerleri verilip, eşit süre çalışınca harcayacakları elektrik enerjilerinin sıralaması soruluyor.",
      "yes", "Işık şiddeti kavramı ve ampul verimini yorumlamak FİZ.11.3.1 kapsamında; enerji–güç ilişkisi ön bilgi, günlük hayat bağlamı uygun.", "MEDIUM"),
    Q(2023, "TYT", 6, "Saydam küresel abajur içindeki noktasal kaynakta yarıçap, saydamlık ve zincir değişiminin I, E ve Φ üzerindeki etkisi", ["FİZ.11.3.1"], "", "lum-qualitative-factors", "exact", ["FBAB8"],
      3, 2, 0, "ms dl", "beş ayrı ifade (işlem ve nicelik eşleşmeleri), tek doğru", "Noktasal kaynağın ışık şiddeti ve toplam akısı kaynağa bağlıdır; aydınlanma kaynak uzaklığı ve yüzeyin ışığı geçirme oranıyla değişir",
      "Abajur yarıçapı, saydamlığı ve asılma yüksekliği değiştirilince ışık şiddeti, K noktasındaki aydınlanma ve abajurdan geçen toplam akının nasıl değiştiğine dair ifadeler değerlendiriliyor.",
      "yes", "Işık şiddeti, akı ve aydınlanmanın bağlı olduğu etmenlerin nitel yorumu FİZ.11.3.1 kapsamında; hesap yok, üç nicelik birlikte kullanılıyor.", "HIGH"),
    Q(2023, "TYT", 7, "Ay yüzeyinde lazer ışığını kendi üzerinden geri yansıtan çukur ayna ve açılı düzlem ayna düzeneklerinin seçimi", ["FİZ.11.3.2", "FİZ.11.3.3"], "", "sm-arbitrary-ray-path", "partial", ["FBAB9", "KB2.7"],
      3, 3, 0, "ms gr", ROMAN, "Merkezden geçen ışın çukur aynadan kendi üzerinden döner; açılı düzlem aynalarda ikinci aynaya dik gelen ışın geri döner",
      "Birimkareli zeminde verilen üç ayna düzeneğinde lazer ışınının geldiği yolu izleyip kaynağa dönüp dönmediği, merkez ve odak noktası ile açı bilgilerinden çıkarılıyor.",
      "yes", "Çukur aynada merkezden geçen ışın ve düzlem aynada yansıma yasası FİZ.11.3.2-3 kapsamında; açılı aynalarda görüntü sayısı formülü kullanılmıyor.", "MEDIUM"),
]

# ---- 2024 TYT (S2 statik sürtünme, S7 çukur ayna + mercek + renk okundu; S1 özkütle, S3 kaldırma, S4 ısı alışverişi, S5 devre/güç, S6 yayda dalga kapsam dışı) ----
ITEMS += [
    Q(2024, "TYT", 2, "Aynı kuvvetle itilen farklı kütleli ve sürtünme katsayılı hareketsiz blokların statik sürtünme kuvvetlerinin karşılaştırılması", ["FİZ.11.1.6", "FİZ.11.1.7"], "", "friction-threshold", "exact", ["KB2.7"],
      2, 1, 0, "tb dl", "sıralama şıkları (f_K, f_L, f_M arasındaki >, <, = ilişkileri)", "Bloklar hareketsiz olduğundan statik sürtünme uygulanan kuvvete eşittir; kütle ve katsayı fark yaratmaz, f = μN yazmak tuzaktır",
      "Üç farklı bloğa aynı yatay kuvvet uygulanıyor ve hiçbiri kımıldamıyor; kütle ve katsayı verilerine rağmen statik sürtünme kuvvetlerinin büyüklük sıralaması soruluyor.",
      "yes", "Statik sürtünmenin denge koşulundan bulunması ve katsayıya bağlı olmaması FİZ.11.1.6-7 kapsamında; hesap gerekmiyor.", "HIGH"),
    Q(2024, "TYT", 7, "Çukur ayna ve yakınsak mercek sisteminde odaktaki kaynaktan mavi ışık yayılınca toplanma noktası (kırmızıda K)", ["FİZ.11.3.3", "FİZ.11.3.9"], "renge göre farklı kırılma (kromatik sapma) 12. sınıf FİZ.12.3.6 bağlamında; 11. sınıf prizma çıktısı tek renkli ışıkla sınırlı", "lens-chromatic", "exact", ["KB2.7"],
      3, 2, 0, "ms gr", "beş konum seçeneği (F, T, K, T–K arası, F–T arası)", "Odaktaki kaynağın ışınları aynadan paralel yansır; mavi ışık kırmızıdan daha çok kırıldığı için mercekte odak daha yakın olur ve mavi T ile K arasında toplanır",
      "Çukur aynanın odağındaki kaynak kırmızı ışıkta K noktasında toplanıyor; aynı düzenekte mavi ışık kullanılınca ışığın asal eksende hangi bölgede toplanacağı seçiliyor.",
      "form_changes", "Ayna ve mercekte özel ışın yolu 11. sınıf kapsamında; ışığın renge göre farklı kırılması Maarif'te tek renkli ışıkla sınırlı olduğundan renk bilgisi verilmeli ya da soru tek renge indirgenmeli.", "MEDIUM"),
]

# ---- 2025 TYT (S1 net kuvvet, S5 elektriklenme, S7 görünür derinlik okundu; S2 ortalama hız, S3 özkütle, S4 ısı sığası, S6 su dalgası genliği/periyodu kapsam dışı) ----
ITEMS += [
    Q(2025, "TYT", 1, "Koltuğu iten iki kişinin kuvvetleri ve kinetik sürtünme ile net kuvvetin büyüklüğü ve yönü", ["FİZ.11.1.5", "FİZ.11.1.6"], "", "friction-horizontal-dynamics", "partial", ["KB2.14"],
      1, 1, 1, "dl", "sayı–yön çiftleri (10 N–Sol … 40 N–Sağ)", "Aynı yöndeki kuvvetler toplanır, zıt yöndeki kinetik sürtünme çıkarılır; net kuvvet büyük olan yöndedir (yön hatası ve toplama hatası tuzağı)",
      "İki kişinin aynı yönde uyguladığı kuvvetler ile zıt yöndeki kinetik sürtünme verilerek hareket eden koltuğa etki eden net kuvvetin büyüklüğü ve yönü soruluyor.",
      "yes", "Serbest cisim diyagramı ile net kuvvet ve kinetik sürtünmenin yönü FİZ.11.1.5-6 kapsamında; tek işlemlik basit toplama.", "HIGH"),
    Q(2025, "TYT", 5, "Sürtünme, temas ve iletimle elektron alış verişi sonucu hangi öğrencinin negatif yüklü olduğu", [], "11. sınıf Ünite 2 temel kabulü (elektriklenme çeşitleri, önceki sınıf ön bilgisi); açık çıktı yok", None, "none", [],
      1, 2, 0, "dl", "tek veya ikili öğrenci kombinasyonları (Yalnız Ayşe … Ezgi ve Seda)", "Elektron alan cisim negatif, veren pozitif olur; ayakkabıyla halıda elektron alınır, jeneratöre dokununca elektron kaybedilir",
      "Üç öğrencinin halıda sürtünme, jeneratöre dokunma ve kazak çıkarma işlemlerinden hangilerinde elektron kazanıp negatif yüklü hale geldiği günlük olaylar üzerinden soruluyor.",
      "no", "Elektriklenme çeşitleri program metninde önceki sınıf bilgisi (11. sınıf temel kabulü) olarak geçiyor; 11. sınıf çıktısı elektriksel kuvvetin modellenmesidir.", "MEDIUM"),
    Q(2025, "TYT", 7, "Havadaki gözlemci ve deniz altındaki dalgıcın birbirlerini gördükleri konumlar (görünür derinlik)", ["FİZ.11.3.6"], "", "ad-explain-direction-of-shift", "exact", ["FBAB1"],
      2, 3, 0, "dl", "iki konum ifadesi (M'nin aşağısı/yukarısı/bulunduğu konum; B için aynı)", "Yoğun ortamdaki cisim yüzeye daha yakın, seyrek ortamdaki cisim yüzeyden daha uzak görünür; gözlemcinin bulunduğu ortam belirleyicidir",
      "Havadaki eğitmenin suyun altındaki öğrenciyi ve öğrencinin eğitmeni görürken bu cisimlerin gerçek konumlarına göre hangi yönde kaymış göründüğü, kırılma indisi bilgisiyle soruluyor.",
      "yes", "Görünür derinliğin ortamların kırılma indisine bağlı nitel yorumu FİZ.11.3.6 kapsamında; matematiksel model gerekmiyor.", "HIGH"),
]
