"""STEP 5 — 11. sınıf fizik kavram grafiğinin elle yazılmış kaynak verisi.

Bu dosya kavram listesinin ve ilişkilerin tek kaynağıdır; JSON çıktıları build_concepts.py ile üretilir.

KAVRAM alanları:
  slug, ad, tür, köken, resmî_anahtar_kavram, çıktılar, sembol, birim, eşleme_terimleri, tanım
  - köken: "11" | "10" | "9" | "ortaokul" | "matematik"
  - resmî_anahtar_kavram: programın "Anahtar Kavramlar" listesindeki birebir ifade (yoksa None)
  - eşleme_terimleri: bağlantı kanıtı için resmî metinde / ders kitabı bölümünde aranacak ifadeler
  - tanım: bizim yazdığımız kısa tanım (uzman incelemesi bekler)

İLİŞKİ türleri: REQUIRES, PART_OF, SPECIAL_CASE_OF, CAUSES, USED_IN, RELATED_TO
  (PREREQUISITE_OF, REQUIRES'ın tersidir; saklanmaz, türetilir.)
"""


CONCEPTS = [
    # ---------------- Ön koşul / temel kavramlar ----------------
    ("vektorel-nicelik", "Vektörel nicelik", "quantity_class", "9", None, ["FİZ.11.1.3", "FİZ.11.1.9", "FİZ.11.2.2", "FİZ.11.2.8"], None, None,
     ["vektör"], "Büyüklüğü, doğrultusu ve yönü birlikte belirtilmesi gereken nicelik (yer değiştirme, hız, kuvvet, alan gibi)."),
    ("skaler-nicelik", "Skaler nicelik", "quantity_class", "9", None, ["FİZ.11.1.10", "FİZ.11.3.1"], None, None,
     ["sürat", "ışık akısı"], "Yalnızca büyüklüğü ve birimiyle tam olarak belirtilen nicelik (sürat, kütle, zaman gibi)."),
    ("vektor-bilesenleri", "Vektörün bileşenlerine ayrılması", "method", "9", None, ["FİZ.11.1.3"], None, None,
     ["bileşen"], "Bir vektörü, toplamı kendisini veren dik doğrultulardaki iki vektöre ayırma işlemi."),
    ("trigonometrik-oranlar", "Trigonometrik oranlar (sin, cos, tan)", "math", "matematik", None, ["FİZ.11.1.3", "FİZ.11.3.5"], None, None,
     ["trigonometri", "Snell"], "Dik üçgende bir açının karşı, komşu kenar ve hipotenüs oranları; vektör bileşenleri ve kırılma hesabında kullanılır."),
    ("oran-oranti", "Doğru ve ters orantı", "math", "matematik", None, ["FİZ.11.1.7", "FİZ.11.1.10", "FİZ.11.2.1", "FİZ.11.2.5", "FİZ.11.2.8"], None, None,
     ["matematiksel model", "ilişki"], "İki nicelikten biri artarken diğerinin aynı oranda artması (doğru) ya da azalması (ters) ilişkisi."),
    ("ters-kare-iliskisi", "Ters kare ilişkisi", "math", "matematik", None, ["FİZ.11.2.1", "FİZ.11.2.2", "FİZ.11.3.1"], None, None,
     ["uzaklığın karesi", "karesi ile ters", "uzaklıktaki yüzeye dik"], "Bir niceliğin uzaklığın karesiyle ters orantılı değişmesi: uzaklık 2 katına çıkınca nicelik 1/4'üne iner."),
    ("grafik-egim-alan", "Grafikte eğim ve alan", "math", "10", None, ["FİZ.11.1.2", "FİZ.11.1.3", "FİZ.11.1.7"], None, None,
     ["grafik"], "Bir grafikte eğimin (dikey değişim / yatay değişim) ve grafik altında kalan alanın fiziksel anlamı."),
    ("konum", "Konum", "quantity", "9", None, ["FİZ.11.1.2"], "x", "m", ["konum"], "Bir cismin seçilen referans noktasına göre yeri."),
    ("yer-degistirme", "Yer değiştirme", "quantity", "9", None, ["FİZ.11.1.2", "FİZ.11.1.3"], "Δx", "m", ["yer değiştirme"],
     "Son konum ile ilk konum arasındaki fark; vektörel niceliktir."),
    ("hiz", "Hız", "quantity", "9", None, ["FİZ.11.1.1", "FİZ.11.1.2", "FİZ.11.1.3"], "v", "m/s", ["hız"],
     "Birim zamandaki yer değiştirme; vektörel niceliktir."),
    ("surat", "Sürat", "quantity", "9", None, ["FİZ.11.1.10"], "v", "m/s", ["sürat"], "Birim zamanda alınan yol; skaler niceliktir."),
    ("ivme", "İvme", "quantity", "10", None, ["FİZ.11.1.1", "FİZ.11.1.2", "FİZ.11.1.3", "FİZ.11.1.4"], "a", "m/s²", ["ivme"],
     "Birim zamandaki hız değişimi; vektörel niceliktir."),
    ("sabit-hizli-hareket", "Sabit hızlı hareket", "model", "10", None, ["FİZ.11.1.3"], None, None, ["sabit hızlı"],
     "Hızın büyüklüğü ve yönü değişmeden yapılan hareket; ivme sıfırdır."),
    ("sabit-ivmeli-hareket", "Bir boyutta sabit ivmeli hareket", "model", "10", None, ["FİZ.11.1.1", "FİZ.11.1.2", "FİZ.11.1.3", "FİZ.11.1.5"], None, None,
     ["sabit ivmeli"], "Doğrusal yolda ivmenin büyüklük ve yönünün sabit olduğu hareket; hız zamanla doğrusal değişir."),
    ("hareket-grafikleri", "Konum-zaman, hız-zaman, ivme-zaman grafikleri", "representation", "10", None, ["FİZ.11.1.2", "FİZ.11.1.3"], None, None,
     ["konum-zaman", "hız-zaman"], "Hareketin üç grafikle gösterimi; x-t eğimi hızı, v-t eğimi ivmeyi, v-t altındaki alan yer değiştirmeyi verir."),
    ("kuvvet", "Kuvvet", "quantity", "9", None, ["FİZ.11.1.4", "FİZ.11.1.5", "FİZ.11.2.1", "FİZ.11.2.8"], "F", "N", ["kuvvet"],
     "Cisimlerin hareket durumunu ya da şeklini değiştirebilen etki; vektörel niceliktir."),
    ("kutle", "Kütle", "quantity", "ortaokul", None, ["FİZ.11.1.1", "FİZ.11.1.4", "FİZ.11.1.8"], "m", "kg", ["kütle"],
     "Madde miktarının ve eylemsizliğin ölçüsü; skaler niceliktir."),
    ("agirlik", "Ağırlık", "quantity", "ortaokul", None, ["FİZ.11.1.5", "FİZ.11.1.8", "FİZ.11.1.10"], "G", "N", ["ağırlık", "ağırlığı"],
     "Cisme etki eden yer çekimi kuvveti; G = m·g."),
    ("periyot", "Periyot", "quantity", "10", None, ["FİZ.11.1.10", "FİZ.11.2.12"], "T", "s", ["periyot"],
     "Periyodik bir hareketin bir tam tekrarı için geçen süre."),
    ("frekans", "Frekans", "quantity", "10", None, ["FİZ.11.1.10", "FİZ.11.2.12"], "f", "Hz", ["frekans"],
     "Birim zamandaki tekrar (devir) sayısı; f = 1/T."),
    ("enerji-donusumu", "Enerji dönüşümü", "principle", "10", None, ["FİZ.11.2.9", "FİZ.11.2.11"], None, None,
     ["enerji"], "Enerjinin bir biçimden başka bir biçime (ör. mekanik → elektrik) dönüşmesi; toplam enerji korunur."),
    ("elektrik-yuku", "Elektrik yükü", "quantity", "ortaokul", None, ["FİZ.11.2.1", "FİZ.11.2.2"], "q", "C", ["yük"],
     "Maddenin elektriksel etkileşimlere yol açan temel özelliği; pozitif ve negatif olmak üzere iki türlüdür."),
    ("elektroskop", "Elektroskop", "device", "ortaokul", None, ["FİZ.11.2.1", "FİZ.11.2.2"], None, None, ["elektroskop"],
     "Bir cismin yüklü olup olmadığını ve yükün işaretini yapraklarının açılmasıyla gösteren düzenek."),
    ("elektrik-akimi", "Elektrik akımı", "quantity", "10", None, ["FİZ.11.2.5", "FİZ.11.2.6", "FİZ.11.2.8"], "I", "A", ["akım"],
     "İletkenin kesitinden birim zamanda geçen yük miktarı."),
    ("potansiyel-fark", "Potansiyel fark (gerilim)", "quantity", "10", None, ["FİZ.11.2.11", "FİZ.11.2.13"], "V", "V", ["gerilim"],
     "Birim yük başına aktarılan elektrik enerjisi; devrede akımı oluşturan etken."),
    ("direnc", "Elektriksel direnç", "quantity", "10", None, ["FİZ.11.2.13"], "R", "Ω", ["direnc"],
     "İletkenin akıma karşı gösterdiği zorluk; R = V/I."),
    ("miknatis", "Mıknatıs", "device", "ortaokul", None, ["FİZ.11.2.4"], None, None, ["mıknatıs"],
     "Çevresinde manyetik alan oluşturan, N ve S kutuplarına sahip cisim."),
    ("manyetik-kutup", "Manyetik kutup", "concept", "ortaokul", None, ["FİZ.11.2.4"], None, None, ["kutup"],
     "Mıknatısın manyetik etkinin en yoğun olduğu uçları (N, S); aynı kutuplar iter, zıt kutuplar çeker."),
    ("pusula", "Pusula", "device", "ortaokul", None, ["FİZ.11.2.4", "FİZ.11.2.5"], None, None, ["pusula"],
     "Serbestçe dönebilen küçük mıknatıs; bulunduğu yerdeki manyetik alan yönünü gösterir."),
    ("isik", "Işık ve ışın", "phenomenon", "ortaokul", None, ["FİZ.11.3.1", "FİZ.11.3.3", "FİZ.11.3.9"], None, None, ["ışın", "ışık"],
     "Işık bir enerji türüdür; ışın, ışığın izlediği yolu gösteren doğru (model)."),
    ("yansima", "Yansıma", "phenomenon", "ortaokul", None, ["FİZ.11.3.2", "FİZ.11.3.3"], None, None, ["yansı"],
     "Işığın bir yüzeye çarpıp geldiği ortama geri dönmesi."),
    ("kirilma", "Kırılma", "phenomenon", "ortaokul", None, ["FİZ.11.3.5", "FİZ.11.3.6", "FİZ.11.3.8", "FİZ.11.3.9"], None, None, ["kırıl"],
     "Işığın bir saydam ortamdan diğerine geçerken hızının ve (eğik gelişte) doğrultusunun değişmesi."),
    ("odak-noktasi", "Odak noktası", "concept", "ortaokul", None, ["FİZ.11.3.3", "FİZ.11.3.9"], "F", None, ["odak"],
     "Asal eksene paralel gelen ışınların yansıdıktan/kırıldıktan sonra kendilerinin ya da uzantılarının toplandığı nokta."),

    # ---------------- Ünite 1: Kuvvet ve Hareket ----------------
    ("serbest-dusme", "Serbest düşme", "phenomenon", "11", "serbest düşme", ["FİZ.11.1.1", "FİZ.11.1.2"], None, None, ["serbest düş"],
     "Yalnızca yer çekimi kuvvetinin etkisindeki hareket. Programda ilk hızı sıfır olan ve olmayan tüm düşey hareketlerin ortak adıdır."),
    ("yer-cekimi-ivmesi", "Yer çekimi ivmesi", "quantity", "11", None, ["FİZ.11.1.1", "FİZ.11.1.2", "FİZ.11.1.3"], "g", "m/s²",
     ["yer çekimi ivmesi"], "Serbest düşen her cismin kütlesinden bağımsız olarak sahip olduğu ivme; programda sabit kabul edilir."),
    ("hava-direnci", "Hava (akışkan) direnç kuvveti", "force", "11", None, ["FİZ.11.1.8"], None, "N",
     ["hava direnc", "sürtünme kuvveti"], "Akışkan içinde hareket eden cisme harekete zıt yönde etki eden kuvvet; hız, kesit alanı ve şekle bağlıdır. Serbest düşme çıktılarında (FİZ.11.1.1–2) ihmal edilir; asıl FİZ.11.1.8'de incelenir."),
    ("tepe-noktasi-hareket", "Tepe noktası (yukarı yönlü serbest düşmede)", "concept", "11", None, ["FİZ.11.1.2", "FİZ.11.1.3"], None, None,
     ["tepe", "ilk hızı sıfırdan farklı"], "Yukarı yönlü harekette hızın (düşey bileşeninin) sıfır olduğu an; ivme bu anda da g'dir."),
    ("maksimum-yukseklik", "Maksimum yükseklik", "quantity", "11", None, ["FİZ.11.1.2", "FİZ.11.1.3"], "h_max", "m",
     ["maksimum yükseklik", "ilk hızı sıfırdan farklı"], "Yukarı yönlü hareketteki cismin çıkabildiği en büyük yükseklik."),
    ("iki-boyutta-sabit-ivmeli-hareket", "İki boyutta sabit ivmeli hareket", "phenomenon", "11", None, ["FİZ.11.1.3"], None, None,
     ["iki boyutta sabit ivmeli"], "Yalnız yer çekimi etkisinde, ilk hızı yatayla açı yapan (ya da yatay) cismin hareketi. Eski kaynaklarda 'yatay atış / eğik atış'."),
    ("bilesenlerin-bagimsizligi", "Hareket bileşenlerinin bağımsızlığı", "principle", "11", None, ["FİZ.11.1.3"], None, None,
     ["yatay ve düşey eksende ayrı ayrı", "bileşen"], "İki boyutlu harekette yatay (sabit hızlı) ve düşey (sabit ivmeli) bileşenlerin birbirinden bağımsız incelenebilmesi; ortak değişken zamandır."),
    ("parabolik-yorunge", "Parabolik yörünge", "representation", "11", None, ["FİZ.11.1.3"], None, None, ["yörünge", "iki boyutta"],
     "İki boyutta sabit ivmeli hareketin izlediği eğri yol."),
    ("menzil", "Menzil", "quantity", "11", None, ["FİZ.11.1.3"], "x_max", "m", ["menzil", "yer değiştirme"],
     "İki boyutta sabit ivmeli harekette cismin yatayda aldığı toplam yol."),
    ("ucus-suresi", "Uçuş süresi", "quantity", "11", None, ["FİZ.11.1.3"], "t_uçuş", "s", ["uçuş süresi", "zaman"],
     "Cismin atıldığı andan yere düştüğü ana kadar geçen süre; düşey hareketten bulunur."),
    ("bileske-kuvvet", "Bileşke (net) kuvvet", "quantity", "11", None, ["FİZ.11.1.4", "FİZ.11.1.5", "FİZ.11.1.10"], "F_net", "N",
     ["bileşke kuvvet", "net kuvvet"], "Cisme etki eden tüm kuvvetlerin vektörel toplamı."),
    ("eylemsizlik", "Eylemsizlik", "principle", "11", "eylemsizlik", ["FİZ.11.1.4"], None, None, ["Newton", "eylemsizlik"],
     "Cismin, hareket durumunu koruma eğilimi; ölçüsü kütledir."),
    ("newton-birinci-yasa", "Newton'ın 1. Hareket Yasası (eylemsizlik ilkesi)", "law", "11", None, ["FİZ.11.1.4", "FİZ.11.1.5", "FİZ.11.1.8"], None, None,
     ["Newton", "net kuvvet değeri sıfır"], "Bileşke kuvvet sıfırsa cisim duruyorsa durmaya, hareket ediyorsa sabit hızla hareketine devam eder."),
    ("newton-ikinci-yasa", "Newton'ın 2. Hareket Yasası (temel yasa)", "law", "11", None, ["FİZ.11.1.4", "FİZ.11.1.5", "FİZ.11.1.7", "FİZ.11.1.10"], None, None,
     ["Newton", "bileşke kuvvet"], "Cismin ivmesi bileşke kuvvetle doğru, kütleyle ters orantılıdır ve bileşke kuvvet yönündedir: F_net = m·a."),
    ("etki-tepki", "Etki-tepki kuvvetleri (Newton'ın 3. Yasası)", "law", "11", "etki-tepki kuvvetleri", ["FİZ.11.1.4", "FİZ.11.1.5"], None, None,
     ["Newton", "etki"], "İki cisim birbirine eşit büyüklükte, zıt yönlü kuvvet uygular; bu kuvvetler farklı cisimlere etki ettiği için birbirini dengelemez."),
    ("serbest-cisim-diyagrami", "Serbest cisim diyagramı", "representation", "11", "serbest cisim diyagramı", ["FİZ.11.1.5"], None, None,
     ["serbest cisim diyagram"], "Tek bir cismi çevresinden ayırarak ona etki eden tüm kuvvetleri vektörlerle gösteren çizim."),
    ("normal-kuvvet", "Normal (tepki) kuvveti", "force", "11", None, ["FİZ.11.1.5", "FİZ.11.1.7"], "N", "N",
     ["normal kuvvet", "tepki kuvvet", "kuvvet"], "Temas yüzeyinin cisme yüzeye dik doğrultuda uyguladığı kuvvet."),
    ("gerilme-kuvveti", "İp gerilme kuvveti", "force", "11", None, ["FİZ.11.1.5", "FİZ.11.1.10"], "T", "N",
     ["gerilme kuvvet", "kuvvet"], "Gergin bir ipin bağlı olduğu cisme ip doğrultusunda uyguladığı çekme kuvveti."),
    ("bagli-cisim-sistemi", "Aynı ivmeli bağlı cisim sistemleri", "model", "11", None, ["FİZ.11.1.5"], None, None,
     ["sistem", "kuvvet"], "İp, temas ya da makarayla birbirine bağlı, aynı büyüklükte ivmeyle hareket eden cisimler. Farklı ivmeli sistemler programda hesaplanmaz."),
    ("egik-duzlem", "Eğik düzlem", "model", "11", None, ["FİZ.11.1.5", "FİZ.11.1.7"], None, None, ["eğik düzlem"],
     "Yatayla açı yapan yüzey; ağırlık yüzeye paralel ve dik bileşenlere ayrılarak incelenir. Ders kitabında var, programda adı geçmez."),
    ("surtunme-kuvveti", "Sürtünme kuvveti", "force", "11", "sürtünme kuvveti", ["FİZ.11.1.6", "FİZ.11.1.7", "FİZ.11.1.8"], "f", "N",
     ["sürtünme"], "Temas eden yüzeyler arasında, bağıl hareketi ya da hareket eğilimini engelleyen kuvvet."),
    ("statik-surtunme", "Statik sürtünme kuvveti", "force", "11", "statik sürtünme kuvveti", ["FİZ.11.1.6", "FİZ.11.1.7", "FİZ.11.1.10"], "f_s", "N",
     ["statik sürtünme", "sürtünme"], "Cisim harekete zorlanıp henüz kaymıyorken etki eden sürtünme; büyüklüğü uygulanan kuvvete eşit olacak şekilde 0 ile maksimum değer arasında değişir."),
    ("kinetik-surtunme", "Kinetik sürtünme kuvveti", "force", "11", "kinetik sürtünme kuvveti", ["FİZ.11.1.6", "FİZ.11.1.7"], "f_k", "N",
     ["kinetik sürtünme"], "Yüzey üzerinde kayan cisme etki eden sürtünme; büyüklüğü f_k = k·N ile yaklaşık sabittir."),
    ("maksimum-statik-surtunme", "Maksimum statik sürtünme (harekete geçme sınırı)", "quantity", "11", None, ["FİZ.11.1.6", "FİZ.11.1.7"], "f_s,max", "N",
     ["statik sürtünme", "harekete zorlanmasına rağmen"], "Statik sürtünmenin alabileceği en büyük değer; uygulanan kuvvet bunu aşınca cisim kaymaya başlar."),
    ("surtunme-katsayisi", "Sürtünme katsayısı", "quantity", "11", None, ["FİZ.11.1.7"], "k", None,
     ["sürtünme kuvvetinin bağlı olduğu değişkenler", "matematiksel model"], "Yüzey çiftine bağlı, birimsiz sabit; sürtünme kuvveti = katsayı × normal kuvvet."),
    ("kayarak-oteleme", "Kayarak öteleme hareketi", "concept", "11", None, ["FİZ.11.1.6", "FİZ.11.1.7"], None, None, ["kayarak öteleme"],
     "Cismin yüzey üzerinde dönmeden kayarak ilerlemesi; temas noktası yüzeye göre hareketlidir (kinetik sürtünme)."),
    ("donerek-oteleme", "Dönerek öteleme hareketi", "concept", "11", None, ["FİZ.11.1.6", "FİZ.11.1.7"], None, None, ["dönerek öteleme"],
     "Cismin kaymadan dönerek ilerlemesi (yuvarlanma); temas noktası anlık durgundur, sürtünme statiktir."),
    ("limit-hiz", "Limit hız", "quantity", "11", "limit hız", ["FİZ.11.1.8"], "v_limit", "m/s", ["limit hız"],
     "Akışkanda düşen cismin direnç kuvveti ağırlığına eşitlendiğinde ulaştığı sabit hız."),
    ("kesit-alani", "Kesit alanı", "quantity", "11", None, ["FİZ.11.1.8"], "A", "m²", ["kesit alan", "limit hız"],
     "Cismin hareket doğrultusuna dik kesitinin alanı; akışkan direncini etkiler."),
    ("duzgun-cembersel-hareket", "Düzgün çembersel hareket", "phenomenon", "11", "düzgün çembersel hareket", ["FİZ.11.1.9", "FİZ.11.1.10"], None, None,
     ["düzgün çembersel"], "Çembersel yörüngede sabit süratle yapılan hareket; hızın yönü sürekli değiştiği için ivmelidir."),
    ("yaricap-vektoru", "Yarıçap vektörü", "concept", "11", None, ["FİZ.11.1.9"], "r", "m", ["yarıçap vektör"],
     "Çemberin merkezinden cismin bulunduğu noktaya çizilen vektör; çizgisel hız buna her an diktir."),
    ("cizgisel-hiz", "Çizgisel hız", "quantity", "11", "çizgisel hız", ["FİZ.11.1.9", "FİZ.11.1.10"], "v", "m/s",
     ["hız vektör", "çizgisel hız"], "Çembersel harekette yörüngeye teğet olan hız vektörü."),
    ("cizgisel-surat", "Çizgisel sürat", "quantity", "11", "çizgisel sürat", ["FİZ.11.1.10"], "v", "m/s", ["çizgisel sürat"],
     "Çizgisel hızın büyüklüğü; v = 2πr/T."),
    ("acisal-hiz", "Açısal hız", "quantity", "11", "açısal hız", ["FİZ.11.1.10"], "ω", "rad/s", ["açısal hız"],
     "Birim zamanda taranan açı; ω = 2π/T = 2πf."),
    ("acisal-ivme", "Açısal ivme", "quantity", "11", "açısal ivme", ["FİZ.11.1.10"], "α", "rad/s²", ["açısal ivme"],
     "Açısal hızın birim zamandaki değişimi; düzgün çembersel harekette sıfırdır."),
    ("merkezcil-ivme", "Merkezcil ivme", "quantity", "11", "merkezcil ivme", ["FİZ.11.1.10"], "a_m", "m/s²", ["merkezcil ivme"],
     "Hız vektörünün yön değişiminden doğan, merkeze yönelik ivme; a = v²/r = ω²r."),
    ("merkezcil-kuvvet", "Merkezcil kuvvet", "force", "11", "merkezcil kuvvet", ["FİZ.11.1.10"], "F_m", "N", ["merkezcil kuvvet"],
     "Çembersel hareketi sağlayan, merkeze yönelik bileşke kuvvet; ayrı bir kuvvet türü değil, mevcut kuvvetlerin (ip, sürtünme, normal, ağırlık) bileşkesidir. F = m·v²/r."),
    ("yatay-duzlemde-cembersel", "Yatay düzlemde düzgün çembersel hareket", "model", "11", None, ["FİZ.11.1.10"], None, None, ["yatay düzlemde"],
     "Yörüngesi yatay düzlemde olan çembersel hareket (ör. ipe bağlı cismin yatay masada dönmesi)."),
    ("dusey-duzlemde-cembersel", "Düşey düzlemde çembersel hareket", "model", "11", None, ["FİZ.11.1.10"], None, None, ["düşey düzlemde"],
     "Yörüngesi düşey düzlemde olan çembersel hareket; tepe ve dip noktalarında ağırlık ile ip/normal kuvvetinin bileşkesi merkezcil kuvveti verir."),
    ("yatay-viraj", "Yatay viraj", "model", "11", None, ["FİZ.11.1.10"], None, None, ["viraj"],
     "Düz yoldaki virajda merkezcil kuvveti statik sürtünmenin sağladığı durum."),
    ("egimli-viraj", "Eğimli viraj", "model", "11", None, ["FİZ.11.1.10"], None, None, ["eğimli viraj"],
     "Yatayla açı yapan virajda merkezcil kuvvete normal kuvvetin yatay bileşeninin (ve varsa sürtünmenin) katkı verdiği durum."),

    # ---------------- Ünite 2: Elektrik ve Manyetizma ----------------
    ("elektriksel-kuvvet", "Elektriksel kuvvet", "force", "11", "elektriksel kuvvet", ["FİZ.11.2.1"], "F", "N", ["elektriksel kuvvet"],
     "Yüklü cisimlerin birbirine uyguladığı itme ya da çekme kuvveti."),
    ("coulomb-yasasi", "Coulomb Yasası", "law", "11", None, ["FİZ.11.2.1"], None, None, ["Coulomb"],
     "İki noktasal yük arasındaki elektriksel kuvvet, yüklerin çarpımıyla doğru, aradaki uzaklığın karesiyle ters orantılıdır: F = k·q₁·q₂/d². Programda hesaplamasız."),
    ("coulomb-sabiti", "Coulomb sabiti", "quantity", "11", None, ["FİZ.11.2.1"], "k", "N·m²/C²", ["Coulomb sabiti"],
     "Coulomb Yasası'ndaki orantı sabiti; boşluk için yaklaşık 9·10⁹ N·m²/C²."),
    ("noktasal-yuk", "Noktasal yük", "model", "11", None, ["FİZ.11.2.1", "FİZ.11.2.2"], None, None, ["noktasal yük"],
     "Boyutları aradaki uzaklığa göre ihmal edilebilen yüklü cisim modeli."),
    ("elektriksel-alan", "Elektriksel alan", "quantity", "11", "elektriksel alan", ["FİZ.11.2.2", "FİZ.11.2.3"], "E", "N/C", ["elektriksel alan"],
     "Bir yükün çevresinde, oraya konan birim pozitif yüke etki eden kuvvet; E = k·q/d². Programda hesaplamasız."),
    ("elektriksel-alan-cizgileri", "Elektriksel alan çizgileri", "representation", "11", None, ["FİZ.11.2.2"], None, None,
     ["alan çizgi", "elektriksel alan"], "Elektriksel alanın yönünü (+ yükten çıkan, − yüke giren) ve sıklığıyla büyüklüğünü gösteren çizgiler."),
    ("bileske-elektriksel-alan", "Bileşke elektriksel alan", "quantity", "11", None, ["FİZ.11.2.2"], "E_net", "N/C",
     ["bileşke", "elektriksel alan"], "Birden fazla yükün bir noktada oluşturduğu alanların vektörel toplamı."),
    ("faraday-kafesi", "Faraday kafesi", "device", "11", None, ["FİZ.11.2.3"], None, None, ["Faraday kafes"],
     "İletken kafes ya da kabuk; dış elektriksel alanı içeriden perdeler, içteki bölgede alan oluşmaz."),
    ("manyetik-alan", "Manyetik alan", "quantity", "11", "manyetik alan", ["FİZ.11.2.4", "FİZ.11.2.5", "FİZ.11.2.6", "FİZ.11.2.8", "FİZ.11.2.10"], "B", "T",
     ["manyetik alan"], "Mıknatısların ve hareketli yüklerin (akımların) çevresinde oluşan, diğer mıknatıslara ve akımlara kuvvet uygulayan alan."),
    ("manyetik-alan-cizgileri", "Manyetik alan çizgileri", "representation", "11", None, ["FİZ.11.2.4"], None, None, ["manyetik alan çizgi"],
     "Mıknatısın dışında N'den S'ye yönelen, kapalı eğriler; sıklığı alanın büyüklüğünü gösterir."),
    ("dunyanin-manyetik-alani", "Dünya'nın manyetik alanı", "phenomenon", "11", None, ["FİZ.11.2.4"], None, None, ["Dünya'nın manyetik", "Dünya’nın manyetik"],
     "Dünya'nın bir mıknatıs gibi davranarak oluşturduğu alan; coğrafi kuzeye yakın bölgede manyetik güney kutbu bulunur."),
    ("oersted-deneyi", "Ørsted deneyi", "experiment", "11", None, ["FİZ.11.2.5"], None, None, ["Ørsted"],
     "Akım geçen telin yanındaki pusulanın sapması; elektrik akımının manyetik alan oluşturduğunu gösterir."),
    ("duz-telin-manyetik-alani", "Akım geçen düz telin manyetik alanı", "phenomenon", "11", None, ["FİZ.11.2.5"], None, None,
     ["düz bir iletken tel"], "Akım geçen düz telin çevresinde oluşan, tel merkezli çembersel alan; B akımla doğru, uzaklıkla ters orantılıdır. Programda hesaplamasız."),
    ("sag-el-kurali", "Sağ el kuralı", "method", "11", None, ["FİZ.11.2.5", "FİZ.11.2.6", "FİZ.11.2.8"], None, None, ["sağ el"],
     "Akım, manyetik alan ve manyetik kuvvet yönlerini belirlemek için kullanılan el kuralları."),
    ("manyetik-alan-katsayisi", "Manyetik alan katsayısı", "quantity", "11", None, ["FİZ.11.2.5", "FİZ.11.2.6"], "k", None,
     ["manyetik alan katsayısı"], "Akımın oluşturduğu manyetik alan bağıntılarındaki orantı sabiti."),
    ("akim-makarasi", "Akım makarası", "device", "11", None, ["FİZ.11.2.6", "FİZ.11.2.7"], None, None, ["akım makarası"],
     "Sarmal biçimde sarılmış iletken tel; içinden akım geçince ekseni boyunca mıknatısa benzer bir alan oluşur."),
    ("sarim-sayisi", "Sarım sayısı", "quantity", "11", None, ["FİZ.11.2.6", "FİZ.11.2.11", "FİZ.11.2.13"], "N", None, ["sarım sayısı"],
     "Makara ya da bobindeki tel dolanma sayısı."),
    ("elektromiknatis", "Elektromıknatıs", "device", "11", None, ["FİZ.11.2.7"], None, None, ["elektromıknatıs"],
     "Akım geçtiğinde mıknatıslanan, akım kesilince etkisi kaybolan makara (genellikle demir çekirdekli)."),
    ("manyetik-kuvvet", "Manyetik kuvvet", "force", "11", "manyetik kuvvet", ["FİZ.11.2.8", "FİZ.11.2.9"], "F", "N", ["manyetik kuvvet"],
     "Manyetik alanın içindeki akım geçen tele (hareketli yüklere) uyguladığı kuvvet."),
    ("tele-etki-eden-manyetik-kuvvet", "Manyetik alanda akım geçen tele etki eden kuvvet", "phenomenon", "11", None, ["FİZ.11.2.8"], None, None,
     ["tele etki eden"], "Büyüklüğü F = B·I·L (alan tele dikken); yönü sağ el kuralıyla bulunur."),
    ("elektrik-motoru", "Elektrik motoru", "device", "11", None, ["FİZ.11.2.9"], None, None, ["elektrik motor"],
     "Manyetik alandaki akım geçen çerçeveye etki eden kuvvetlerle elektrik enerjisini dönme hareketine çeviren düzenek."),
    ("manyetik-aki", "Manyetik akı", "quantity", "11", "manyetik akı", ["FİZ.11.2.10", "FİZ.11.2.11"], "Φ", "Wb", ["manyetik akı"],
     "Bir yüzeyden geçen manyetik alan çizgilerinin ölçüsü; alan yüzeye dikken Φ = B·A."),
    ("induksiyon-gerilimi", "İndüksiyon gerilimi (indüksiyon emk)", "quantity", "11", "indüksiyon gerilimi", ["FİZ.11.2.11", "FİZ.11.2.12"], "ε", "V",
     ["indüksiyon gerilim"], "Bir devreden geçen manyetik akı değiştiğinde oluşan gerilim."),
    ("induksiyon-akimi", "İndüksiyon akımı", "quantity", "11", "indüksiyon akımı", ["FİZ.11.2.11", "FİZ.11.2.12"], "I", "A", ["indüksiyon akım"],
     "İndüksiyon geriliminin kapalı devrede oluşturduğu akım."),
    ("faraday-induksiyon-yasasi", "Faraday'ın indüksiyon yasası", "law", "11", None, ["FİZ.11.2.11"], None, None,
     ["birim zamandaki manyetik akı değişim"], "İndüksiyon gerilimi, devreden geçen manyetik akının birim zamandaki değişimiyle orantılıdır: ε = −N·ΔΦ/Δt."),
    ("lenz-yasasi", "Lenz Yasası", "law", "11", None, ["FİZ.11.2.11"], None, None, ["Lenz"],
     "İndüksiyon akımı, kendisini oluşturan akı değişimine karşı koyacak yönde oluşur. Ders kitabında var, programda adı geçmez."),
    ("jenerator", "Elektrik jeneratörü", "device", "11", None, ["FİZ.11.2.11", "FİZ.11.2.12"], None, None, ["jeneratör", "mekanik enerji"],
     "Manyetik alanda döndürülen çerçevede akı değişimiyle mekanik enerjiyi elektrik enerjisine çeviren düzenek."),
    ("alternatif-akim", "Alternatif (değişken) akım", "quantity", "11", "alternatif akım", ["FİZ.11.2.12"], None, "A", ["alternatif"],
     "Büyüklüğü ve yönü zamanla periyodik olarak değişen akım."),
    ("etkin-deger", "Alternatif akımda etkin değer", "quantity", "11", None, ["FİZ.11.2.12"], "I_e", "A", ["etkin değer", "alternatif"],
     "Alternatif akımın, aynı direnç üzerinde aynı ısıyı üreten doğru akım değeri. Ders kitabında var (s. 261-262), programda adı geçmez."),
    ("transformator", "Transformatör", "device", "11", "transformatör", ["FİZ.11.2.13"], None, None, ["transformatör"],
     "Ortak çekirdek üzerindeki iki sarım arasında indüksiyonla alternatif gerilimi yükselten ya da düşüren düzenek."),
    ("birincil-ikincil-sarim", "Birincil ve ikincil sarım", "concept", "11", None, ["FİZ.11.2.13"], None, None, ["birincil"],
     "Transformatörün gerilimin uygulandığı (birincil) ve gerilimin alındığı (ikincil) sarımları."),
    ("iletimde-enerji-kaybi", "Elektrik iletiminde enerji kaybı", "phenomenon", "11", None, ["FİZ.11.2.13"], None, None,
     ["harcanan elektrik enerjisi", "en düşük akımlarla"], "İletim hatlarının direncinde ısıya dönüşen enerji; akım küçüldükçe azalır, bu yüzden iletim yüksek gerilimle yapılır."),

    # ---------------- Ünite 3: Optik ----------------
    ("isik-siddeti", "Işık şiddeti", "quantity", "11", "ışık şiddeti", ["FİZ.11.3.1"], "I", "cd", ["ışık şiddeti"],
     "Işık kaynağının belirli bir doğrultuda yaydığı ışık miktarının ölçüsü; birimi kandela."),
    ("isik-akisi", "Işık akısı", "quantity", "11", "ışık akısı", ["FİZ.11.3.1"], "Φ", "lm", ["ışık akısı"],
     "Bir kaynaktan birim zamanda yayılan ya da bir yüzeye düşen toplam ışık miktarı; birimi lümen."),
    ("aydinlanma", "Aydınlanma", "quantity", "11", "aydınlanma", ["FİZ.11.3.1"], "E", "lx", ["aydınlanma"],
     "Bir yüzeyin birim alanına düşen ışık akısı; birimi lüks. Noktasal kaynaktan uzaklığın karesiyle ters orantılıdır."),
    ("yansima-yasalari", "Yansıma yasaları", "law", "11", None, ["FİZ.11.3.2", "FİZ.11.3.3"], None, None, ["yansıma"],
     "Gelen ışın, normal ve yansıyan ışın aynı düzlemdedir; gelme açısı yansıma açısına eşittir."),
    ("duzlem-ayna", "Düzlem ayna", "device", "11", None, ["FİZ.11.3.2"], None, None, ["düzlem ayna"],
     "Düz yansıtıcı yüzey; cismin aynaya göre simetriğinde, cisimle aynı boyda, sanal ve düz görüntü oluşturur."),
    ("goruntu", "Görüntü (gerçek / sanal)", "concept", "11", None, ["FİZ.11.3.2", "FİZ.11.3.4", "FİZ.11.3.10"], None, None, ["görüntü"],
     "Işınların ya da uzantılarının kesiştiği yerde oluşan cisim benzeri. Gerçek görüntü ekranda toplanır, sanal görüntü toplanamaz."),
    ("gorus-alani", "Görüş alanı", "concept", "11", None, ["FİZ.11.3.2"], None, None, ["görüş alanı", "düzlem ayna"],
     "Gözün bir aynaya bakarak görebildiği bölge; aynanın kenarlarından yansıyan ışınlarla sınırlanır."),
    ("kuresel-ayna", "Küresel ayna", "device", "11", None, ["FİZ.11.3.3", "FİZ.11.3.4"], None, None, ["küresel ayna"],
     "Bir küre parçası biçimindeki yansıtıcı yüzey."),
    ("cukur-ayna", "Çukur ayna", "device", "11", None, ["FİZ.11.3.3", "FİZ.11.3.4"], None, None, ["çukur"],
     "İç yüzeyi yansıtıcı küresel ayna; paralel ışınları odakta toplar."),
    ("tumsek-ayna", "Tümsek ayna", "device", "11", None, ["FİZ.11.3.3", "FİZ.11.3.4"], None, None, ["tümsek"],
     "Dış yüzeyi yansıtıcı küresel ayna; paralel ışınları uzantıları odaktan geçecek şekilde dağıtır, her zaman küçük, düz, sanal görüntü verir."),
    ("asal-eksen", "Asal eksen", "concept", "11", "asal eksen", ["FİZ.11.3.3", "FİZ.11.3.9"], None, None, ["asal eksen"],
     "Küresel aynada merkez ile tepe noktasından, mercekte odaklardan ve optik merkezden geçen eksen."),
    ("ayna-tepe-noktasi", "Tepe noktası (küresel ayna)", "concept", "11", "tepe noktası", ["FİZ.11.3.3"], "T", None, ["tepe nokta"],
     "Küresel aynanın asal eksenle kesiştiği orta noktası."),
    ("egrilik-merkezi", "Merkez (eğrilik merkezi)", "concept", "11", "merkez", ["FİZ.11.3.3"], "M", None, ["merkez nokta", "merkez"],
     "Aynanın parçası olduğu kürenin merkezi; tepe noktasına uzaklığı odak uzaklığının iki katıdır."),
    ("odak-uzakligi", "Odak uzaklığı", "quantity", "11", None, ["FİZ.11.3.3", "FİZ.11.3.9"], "f", "m", ["odak uzaklığı", "odak"],
     "Odak noktasının tepe noktasına (aynada) ya da optik merkeze (mercekte) uzaklığı."),
    ("ozel-isinlar", "Özel ışınlar", "method", "11", None, ["FİZ.11.3.3", "FİZ.11.3.4", "FİZ.11.3.9", "FİZ.11.3.10"], None, None,
     ["özel ışın", "izlediği yol"], "Ayna ve merceklerde yolu kuralla bilinen ışınlar (paralel → odaktan, odaktan → paralel, merkezden/optik merkezden geçen); görüntü çiziminde kullanılır."),
    ("kuresel-aynada-goruntu", "Küresel aynada görüntü oluşumu", "phenomenon", "11", None, ["FİZ.11.3.4"], None, None,
     ["görüntü oluşum"], "Cismin aynaya göre konumuna (merkezin dışı, merkez, merkez-odak arası, odak, odak-ayna arası) bağlı olarak görüntünün yeri, boyu ve gerçek/sanal oluşu."),
    ("kirma-indisi", "Ortamın ışığı kırma indisi", "quantity", "11", "ortamın ışığı kırma indisi", ["FİZ.11.3.5", "FİZ.11.3.6", "FİZ.11.3.8"], "n", None,
     ["kırma indis", "kırıcılık"], "Işığın boşluktaki hızının ortamdaki hızına oranı; birimsizdir, büyüdükçe ortam ışığı daha çok kırar."),
    ("snell-yasasi", "Snell Yasası", "law", "11", "Snell Yasası", ["FİZ.11.3.5", "FİZ.11.3.8"], None, None, ["Snell", "kırılma yasa"],
     "n₁·sin(gelme açısı) = n₂·sin(kırılma açısı)."),
    ("sinir-acisi", "Sınır açısı", "quantity", "11", "sınır açısı", ["FİZ.11.3.5", "FİZ.11.3.7"], "θ_s", "°", ["sınır açısı"],
     "Çok kırıcı ortamdan az kırıcı ortama geçişte kırılma açısını 90° yapan gelme açısı."),
    ("tam-yansima", "Tam yansıma", "phenomenon", "11", "tam yansıma", ["FİZ.11.3.5", "FİZ.11.3.7", "FİZ.11.3.8"], None, None, ["tam yansıma"],
     "Çok kırıcı ortamdan gelen ışının, gelme açısı sınır açısından büyükken tamamen geri yansıması."),
    ("gorunur-derinlik", "Görünür derinlik", "phenomenon", "11", "görünür derinlik", ["FİZ.11.3.6"], None, None, ["görünür derinlik"],
     "Farklı kırıcılıktaki ortamdan bakıldığında cismin olduğundan farklı derinlikte görünmesi. Programda hesaplamasız."),
    ("gercek-derinlik", "Gerçek derinlik", "quantity", "11", None, ["FİZ.11.3.6"], None, "m", ["gerçek derinlik"],
     "Cismin ortam yüzeyine gerçek uzaklığı."),
    ("fiber-optik", "Fiber optik", "device", "11", "fiber optik", ["FİZ.11.3.7"], None, None, ["fiber optik"],
     "Işığı ardışık tam yansımalarla ileten ince saydam lif; iletişim ve tıpta kullanılır."),
    ("prizma", "Prizma", "device", "11", None, ["FİZ.11.3.8"], None, None, ["prizma"],
     "Saydam, kırıcı yüzeyleri birbirine açılı katı; ışığı kırarak ya da tam yansıtarak yönünü değiştirir."),
    ("tek-renkli-isik", "Tek renkli ışık", "concept", "11", None, ["FİZ.11.3.8"], None, None, ["tek renkli"],
     "Tek bir dalga boyundan oluşan ışık; prizmada renklere ayrılmaz. Renklere ayrılma 12. sınıf konusudur."),
    ("sapma-acisi", "Sapma açısı", "quantity", "11", None, ["FİZ.11.3.5", "FİZ.11.3.8"], None, "°", ["sapma", "prizma"],
     "Işının ilk doğrultusu ile son doğrultusu arasındaki açı."),
    ("mercek", "Mercek", "device", "11", None, ["FİZ.11.3.9", "FİZ.11.3.10"], None, None, ["mercek"],
     "En az bir yüzeyi küresel olan saydam ortam; ışığı kırarak toplar ya da dağıtır."),
    ("yakinsak-mercek", "Yakınsak (ince kenarlı) mercek", "device", "11", None, ["FİZ.11.3.9", "FİZ.11.3.10"], None, None, ["yakınsak"],
     "Paralel ışınları odakta toplayan mercek."),
    ("iraksak-mercek", "Iraksak (kalın kenarlı) mercek", "device", "11", None, ["FİZ.11.3.9", "FİZ.11.3.10"], None, None, ["ıraksak"],
     "Paralel ışınları uzantıları odaktan geçecek şekilde dağıtan mercek; her zaman küçük, düz, sanal görüntü verir."),
    ("optik-merkez", "Optik merkez", "concept", "11", None, ["FİZ.11.3.9"], "O", None, ["optik merkez"],
     "Merceğin merkezi; buradan geçen ışın sapmadan devam eder."),
    ("mercekte-goruntu", "Mercekte görüntü oluşumu", "phenomenon", "11", None, ["FİZ.11.3.10"], None, None, ["görüntü oluşum"],
     "Cismin merceğe göre konumuna bağlı olarak görüntünün yeri, boyu ve gerçek/sanal oluşu."),
]

R = "REQUIRES"; P = "PART_OF"; S = "SPECIAL_CASE_OF"; C = "CAUSES"; U = "USED_IN"; L = "RELATED_TO"
RELATIONS = [
    # temel
    ("vektor-bilesenleri", R, "vektorel-nicelik", "Bileşenlere ayırma vektör kavramına dayanır."),
    ("vektor-bilesenleri", R, "trigonometrik-oranlar", "Bileşenler sin/cos ile hesaplanır."),
    ("yer-degistirme", R, "konum", "Yer değiştirme konum farkıdır."),
    ("yer-degistirme", R, "vektorel-nicelik", "Yer değiştirme vektöreldir."),
    ("hiz", R, "yer-degistirme", "Hız birim zamandaki yer değiştirmedir."),
    ("surat", L, "hiz", "Sürat skaler, hız vektörel karşılığıdır; sık karıştırılır."),
    ("surat", R, "skaler-nicelik", "Sürat skalerdir."),
    ("ivme", R, "hiz", "İvme hız değişimidir."),
    ("sabit-hizli-hareket", R, "hiz", "Sabit hızlı hareket hız kavramına dayanır."),
    ("sabit-ivmeli-hareket", R, "ivme", "Sabit ivmeli hareket ivme kavramına dayanır."),
    ("hareket-grafikleri", R, "grafik-egim-alan", "Grafiklerden eğim ve alanla bilgi çıkarılır."),
    ("hareket-grafikleri", R, "sabit-ivmeli-hareket", "Grafikler sabit hızlı/ivmeli hareketi gösterir."),
    ("agirlik", R, "kuvvet", "Ağırlık bir kuvvettir."),
    ("agirlik", R, "kutle", "G = m·g."),
    ("frekans", R, "periyot", "f = 1/T."),
    ("manyetik-kutup", P, "miknatis", "Kutuplar mıknatısın parçasıdır."),
    ("odak-noktasi", R, "isik", "Odak, ışınların toplandığı noktadır."),
    ("yansima", R, "isik", "Yansıma ışığın davranışıdır."),
    ("kirilma", R, "isik", "Kırılma ışığın davranışıdır."),
    ("potansiyel-fark", L, "elektrik-akimi", "Gerilim devrede akımı oluşturur (Ohm)."),
    ("direnc", R, "potansiyel-fark", "R = V/I."),
    ("direnc", R, "elektrik-akimi", "R = V/I."),
    ("elektrik-akimi", R, "elektrik-yuku", "Akım birim zamanda geçen yüktür."),
    # Ünite 1
    ("serbest-dusme", S, "sabit-ivmeli-hareket", "Serbest düşme, ivmesi g olan bir boyutlu sabit ivmeli harekettir."),
    ("serbest-dusme", R, "yer-cekimi-ivmesi", "Hareketin ivmesi g'dir."),
    ("serbest-dusme", R, "hareket-grafikleri", "FİZ.11.1.2 x-t, v-t, a-t grafiklerini ister."),
    ("yer-cekimi-ivmesi", R, "ivme", "g bir ivmedir."),
    ("yer-cekimi-ivmesi", L, "agirlik", "G = m·g."),
    ("hava-direnci", S, "surtunme-kuvveti", "Program limit hızı sürtünme kuvvetiyle ilişkilendirir; akışkan sürtünmesidir."),
    ("hava-direnci", L, "serbest-dusme", "Serbest düşmede ihmal edilir (resmî varsayım)."),
    ("tepe-noktasi-hareket", P, "serbest-dusme", "Yukarı yönlü serbest düşmenin özel anı."),
    ("tepe-noktasi-hareket", R, "ivme", "Tepede v=0 iken a=g olduğunu anlamak ivme kavramını gerektirir."),
    ("maksimum-yukseklik", P, "serbest-dusme", "Yukarı yönlü serbest düşmenin büyüklüğü."),
    ("maksimum-yukseklik", U, "iki-boyutta-sabit-ivmeli-hareket", "Düşey bileşenden bulunur."),
    ("iki-boyutta-sabit-ivmeli-hareket", R, "vektor-bilesenleri", "Hız bileşenlerine ayrılır."),
    ("iki-boyutta-sabit-ivmeli-hareket", R, "sabit-hizli-hareket", "Yatay bileşen sabit hızlıdır (FİZ.11.1.3 a)."),
    ("iki-boyutta-sabit-ivmeli-hareket", R, "serbest-dusme", "Düşey bileşen serbest düşmedir."),
    ("iki-boyutta-sabit-ivmeli-hareket", R, "bilesenlerin-bagimsizligi", "Bileşenler ayrı ayrı incelenir."),
    ("iki-boyutta-sabit-ivmeli-hareket", R, "trigonometrik-oranlar", "Programda trigonometrik hesap açıkça var."),
    ("bilesenlerin-bagimsizligi", R, "vektor-bilesenleri", "Bağımsızlık bileşen kavramına dayanır."),
    ("parabolik-yorunge", P, "iki-boyutta-sabit-ivmeli-hareket", "Hareketin yörüngesidir."),
    ("menzil", P, "iki-boyutta-sabit-ivmeli-hareket", "Hareketin büyüklüğüdür."),
    ("menzil", R, "ucus-suresi", "Menzil = yatay hız × uçuş süresi."),
    ("ucus-suresi", P, "iki-boyutta-sabit-ivmeli-hareket", "Hareketin büyüklüğüdür."),
    ("ucus-suresi", R, "serbest-dusme", "Düşey hareketten bulunur."),
    ("bileske-kuvvet", R, "kuvvet", "Kuvvetlerin toplamıdır."),
    ("bileske-kuvvet", R, "vektorel-nicelik", "Vektörel toplamadır."),
    ("eylemsizlik", R, "kutle", "Eylemsizliğin ölçüsü kütledir."),
    ("newton-birinci-yasa", R, "bileske-kuvvet", "F_net = 0 koşulu."),
    ("newton-birinci-yasa", R, "eylemsizlik", "Eylemsizlik ilkesidir."),
    ("newton-ikinci-yasa", R, "bileske-kuvvet", "F_net = m·a."),
    ("newton-ikinci-yasa", R, "ivme", "F_net = m·a."),
    ("newton-ikinci-yasa", R, "kutle", "F_net = m·a."),
    ("etki-tepki", R, "kuvvet", "Kuvvet çiftidir."),
    ("serbest-cisim-diyagrami", R, "kuvvet", "Kuvvetleri gösterir."),
    ("serbest-cisim-diyagrami", R, "vektorel-nicelik", "Kuvvetler vektör olarak çizilir."),
    ("serbest-cisim-diyagrami", U, "newton-ikinci-yasa", "FİZ.11.1.5: Newton yasaları diyagramla yeniden ifade edilir."),
    ("normal-kuvvet", R, "kuvvet", "Bir temas kuvvetidir."),
    ("normal-kuvvet", L, "etki-tepki", "Cismin yüzeye bastırması ile yüzeyin tepkisi bir etki-tepki çiftidir; normal kuvvet ağırlığın tepkisi değildir."),
    ("gerilme-kuvveti", R, "kuvvet", "Bir temas kuvvetidir."),
    ("bagli-cisim-sistemi", R, "newton-ikinci-yasa", "Sistem ivmesi F_net/m_toplam."),
    ("bagli-cisim-sistemi", R, "serbest-cisim-diyagrami", "Her cisim ayrı ayrı incelenir."),
    ("bagli-cisim-sistemi", R, "gerilme-kuvveti", "Cisimler iple bağlıdır."),
    ("egik-duzlem", R, "vektor-bilesenleri", "Ağırlık bileşenlerine ayrılır."),
    ("egik-duzlem", R, "serbest-cisim-diyagrami", "Kuvvetler diyagramla gösterilir."),
    ("egik-duzlem", R, "agirlik", "Ağırlığın bileşenleri kullanılır."),
    ("surtunme-kuvveti", R, "kuvvet", "Bir temas kuvvetidir."),
    ("surtunme-kuvveti", R, "normal-kuvvet", "Büyüklüğü normal kuvvete bağlıdır."),
    ("statik-surtunme", S, "surtunme-kuvveti", "Sürtünmenin bir türü."),
    ("kinetik-surtunme", S, "surtunme-kuvveti", "Sürtünmenin bir türü."),
    ("maksimum-statik-surtunme", P, "statik-surtunme", "Statik sürtünmenin üst sınırı."),
    ("surtunme-katsayisi", U, "maksimum-statik-surtunme", "f_s,max = k_s·N; nicel model FİZ.11.1.7'de, nitel karşılaştırma FİZ.11.1.6'da."),
    ("surtunme-katsayisi", U, "kinetik-surtunme", "f_k = k·N; nicel model FİZ.11.1.7'de."),
    ("surtunme-katsayisi", P, "surtunme-kuvveti", "Sürtünmenin matematiksel modelinin parçası (FİZ.11.1.7)."),
    ("kayarak-oteleme", L, "kinetik-surtunme", "Kayan cisme kinetik sürtünme etki eder."),
    ("donerek-oteleme", L, "statik-surtunme", "Kaymadan yuvarlanmada sürtünme statiktir."),
    ("limit-hiz", R, "hava-direnci", "Direnç kuvveti ağırlığa eşitlenince oluşur."),
    ("limit-hiz", R, "agirlik", "Direnç = ağırlık koşulu."),
    ("limit-hiz", R, "newton-birinci-yasa", "Bileşke kuvvet sıfır → sabit hız."),
    ("limit-hiz", L, "serbest-dusme", "Hava direnci ihmal edilmezse serbest düşme limit hıza ulaşır."),
    ("kesit-alani", U, "hava-direnci", "Direnç kuvvetini etkileyen değişkendir."),
    ("duzgun-cembersel-hareket", R, "cizgisel-hiz", "Hız teğet ve sabit büyüklükte."),
    ("duzgun-cembersel-hareket", R, "periyot", "Hareket periyodiktir."),
    ("duzgun-cembersel-hareket", R, "yaricap-vektoru", "FİZ.11.1.9: hız ve yarıçap vektörü yönleri."),
    ("cizgisel-hiz", R, "hiz", "Hızın çembersel harekette adı."),
    ("cizgisel-hiz", R, "vektorel-nicelik", "Yönü sürekli değişen vektör."),
    ("cizgisel-surat", R, "surat", "Çizgisel hızın büyüklüğü."),
    ("cizgisel-surat", R, "periyot", "v = 2πr/T."),
    ("acisal-hiz", R, "periyot", "ω = 2π/T."),
    ("acisal-hiz", R, "frekans", "ω = 2πf."),
    ("acisal-ivme", R, "acisal-hiz", "Açısal hızın değişimi."),
    ("acisal-ivme", L, "duzgun-cembersel-hareket", "Düzgün çembersel harekette sıfırdır."),
    ("merkezcil-ivme", R, "cizgisel-hiz", "Hız yönünün değişiminden doğar."),
    ("merkezcil-ivme", R, "ivme", "Bir ivmedir."),
    ("merkezcil-kuvvet", R, "merkezcil-ivme", "F = m·a_m."),
    ("merkezcil-kuvvet", R, "newton-ikinci-yasa", "Newton'ın 2. yasasının çembersel hareketteki uygulaması."),
    ("merkezcil-kuvvet", R, "bileske-kuvvet", "Merkezcil kuvvet bileşke kuvvettir, ayrı bir kuvvet değildir."),
    ("yatay-duzlemde-cembersel", S, "duzgun-cembersel-hareket", "Programdaki problem türü."),
    ("yatay-duzlemde-cembersel", R, "merkezcil-kuvvet", "Merkezcil kuvvet analizi."),
    ("dusey-duzlemde-cembersel", S, "duzgun-cembersel-hareket", "Programdaki problem türü (program 'düşey düzlemde düzgün çembersel hareket' der)."),
    ("dusey-duzlemde-cembersel", R, "merkezcil-kuvvet", "Tepe/dip noktalarında kuvvet analizi."),
    ("dusey-duzlemde-cembersel", R, "agirlik", "Ağırlık merkezcil kuvvete katkı verir."),
    ("dusey-duzlemde-cembersel", R, "gerilme-kuvveti", "İp gerilmesi analizi."),
    ("yatay-viraj", S, "yatay-duzlemde-cembersel", "Yolda yatay çembersel hareket."),
    ("yatay-viraj", R, "statik-surtunme", "Merkezcil kuvveti statik sürtünme sağlar."),
    ("egimli-viraj", S, "duzgun-cembersel-hareket", "Programdaki problem türü."),
    ("egimli-viraj", R, "merkezcil-kuvvet", "Merkezcil kuvvet analizi."),
    ("egimli-viraj", R, "normal-kuvvet", "Normal kuvvetin yatay bileşeni katkı verir."),
    ("egimli-viraj", R, "vektor-bilesenleri", "Kuvvetler bileşenlerine ayrılır."),
    # Ünite 2
    ("elektriksel-kuvvet", R, "elektrik-yuku", "Yükler arası etkileşimdir."),
    ("elektriksel-kuvvet", R, "kuvvet", "Bir kuvvettir."),
    ("coulomb-yasasi", R, "elektriksel-kuvvet", "Kuvvetin matematiksel modelidir."),
    ("coulomb-yasasi", R, "noktasal-yuk", "Noktasal yükler için geçerlidir."),
    ("coulomb-yasasi", R, "ters-kare-iliskisi", "F ∝ 1/d²."),
    ("coulomb-yasasi", R, "oran-oranti", "Programda yorum oran-orantıyla yapılır."),
    ("coulomb-sabiti", P, "coulomb-yasasi", "Yasadaki sabittir."),
    ("noktasal-yuk", R, "elektrik-yuku", "Bir yük modelidir."),
    ("elektroskop", U, "coulomb-yasasi", "Programdaki uygulamada gözlem aracıdır."),
    ("elektriksel-alan", R, "elektriksel-kuvvet", "Birim yük başına kuvvettir."),
    ("elektriksel-alan", R, "vektorel-nicelik", "Vektöreldir."),
    ("elektriksel-alan", R, "ters-kare-iliskisi", "E ∝ 1/d²."),
    ("elektriksel-alan-cizgileri", P, "elektriksel-alan", "Alanın gösterimidir."),
    ("bileske-elektriksel-alan", R, "elektriksel-alan", "Alanların toplamıdır."),
    ("bileske-elektriksel-alan", R, "vektorel-nicelik", "Vektörel toplamadır."),
    ("faraday-kafesi", R, "elektriksel-alan", "İç bölgede alanın sıfır olması."),
    ("manyetik-alan", R, "miknatis", "Mıknatısların alanıyla tanıtılır (FİZ.11.2.4)."),
    ("manyetik-alan", R, "vektorel-nicelik", "Vektöreldir."),
    ("manyetik-alan-cizgileri", P, "manyetik-alan", "Alanın gösterimidir."),
    ("dunyanin-manyetik-alani", S, "manyetik-alan", "Bir manyetik alan örneğidir."),
    ("pusula", U, "dunyanin-manyetik-alani", "Yön bulmada kullanılır."),
    ("pusula", U, "oersted-deneyi", "Deneyde akımın alanını gösterir."),
    ("elektrik-akimi", C, "manyetik-alan", "Akım geçen iletken çevresinde manyetik alan oluşur (Ørsted)."),
    ("oersted-deneyi", L, "duz-telin-manyetik-alani", "Düz telin alanını keşfettiren deneydir (FİZ.11.2.5)."),
    ("duz-telin-manyetik-alani", R, "elektrik-akimi", "Kaynağı akımdır."),
    ("duz-telin-manyetik-alani", R, "manyetik-alan", "Bir manyetik alandır."),
    ("duz-telin-manyetik-alani", R, "sag-el-kurali", "Yönü sağ el kuralıyla bulunur."),
    ("duz-telin-manyetik-alani", R, "oran-oranti", "B ∝ I/d yorumu."),
    ("manyetik-alan-katsayisi", P, "duz-telin-manyetik-alani", "Bağıntıdaki sabittir."),
    ("akim-makarasi", R, "duz-telin-manyetik-alani", "Sarımların alanlarının toplamıdır."),
    ("akim-makarasi", R, "sarim-sayisi", "Alan sarım sayısına bağlıdır."),
    ("akim-makarasi", R, "sag-el-kurali", "Kutupları sağ el kuralıyla bulunur."),
    ("elektromiknatis", R, "akim-makarasi", "Akım makarasının uygulamasıdır."),
    ("manyetik-kuvvet", R, "manyetik-alan", "Alan kuvvet uygular."),
    ("manyetik-kuvvet", R, "kuvvet", "Bir kuvvettir."),
    ("tele-etki-eden-manyetik-kuvvet", S, "manyetik-kuvvet", "Manyetik kuvvetin akım geçen teldeki durumu."),
    ("tele-etki-eden-manyetik-kuvvet", R, "elektrik-akimi", "F = B·I·L."),
    ("tele-etki-eden-manyetik-kuvvet", R, "sag-el-kurali", "Yönü sağ el kuralıyla bulunur."),
    ("elektrik-motoru", R, "tele-etki-eden-manyetik-kuvvet", "FİZ.11.2.9: tele etki eden kuvvetten motora."),
    ("elektrik-motoru", R, "enerji-donusumu", "Elektrik → mekanik enerji."),
    ("manyetik-aki", R, "manyetik-alan", "Φ = B·A."),
    ("manyetik-aki", C, "induksiyon-gerilimi", "Akının zamanla değişimi indüksiyon gerilimi oluşturur."),
    ("faraday-induksiyon-yasasi", R, "manyetik-aki", "ε = −N·ΔΦ/Δt."),
    ("faraday-induksiyon-yasasi", P, "induksiyon-gerilimi", "İndüksiyon geriliminin matematiksel modelidir (FİZ.11.2.11)."),
    ("induksiyon-gerilimi", R, "potansiyel-fark", "Bir gerilimdir."),
    ("induksiyon-gerilimi", C, "induksiyon-akimi", "Kapalı devrede akım oluşturur."),
    ("induksiyon-akimi", R, "elektrik-akimi", "Bir akımdır."),
    ("lenz-yasasi", R, "induksiyon-akimi", "İndüksiyon akımının yönünü verir."),
    ("lenz-yasasi", R, "manyetik-aki", "Akı değişimine karşı koyar."),
    ("alternatif-akim", R, "induksiyon-akimi", "FİZ.11.2.12: indüklenme sonucu oluşan alternatif akım."),
    ("alternatif-akim", R, "periyot", "Periyodik değişir."),
    ("etkin-deger", P, "alternatif-akim", "Alternatif akımın büyüklük ölçüsü."),
    ("jenerator", R, "induksiyon-gerilimi", "Akı değişimiyle gerilim üretir."),
    ("jenerator", R, "enerji-donusumu", "Mekanik → elektrik enerjisi."),
    ("jenerator", L, "elektrik-motoru", "Ünite amacı: motor ve jeneratör arasındaki ilişki (ters işlevli düzenekler)."),
    ("jenerator", C, "alternatif-akim", "Dönen çerçevede alternatif akım oluşur."),
    ("transformator", R, "induksiyon-gerilimi", "Sarımlar arası indüksiyonla çalışır."),
    ("transformator", R, "alternatif-akim", "Değişen akı için alternatif akım gerekir."),
    ("transformator", R, "sarim-sayisi", "Gerilim oranı sarım oranına bağlıdır."),
    ("birincil-ikincil-sarim", P, "transformator", "Transformatörün parçalarıdır."),
    ("iletimde-enerji-kaybi", R, "direnc", "Kayıp hattın direncinde olur."),
    ("iletimde-enerji-kaybi", R, "elektrik-akimi", "Kayıp akımla artar."),
    ("transformator", U, "iletimde-enerji-kaybi", "Gerilimi yükseltip akımı düşürerek kaybı azaltır (FİZ.11.2.13 uygulaması)."),
    # Ünite 3
    ("isik-siddeti", R, "isik", "Işık kaynağının özelliğidir."),
    ("isik-akisi", R, "isik-siddeti", "Akı, şiddetle ilişkilidir."),
    ("isik-akisi", R, "skaler-nicelik", "Skalerdir."),
    ("aydinlanma", R, "isik-akisi", "Birim alana düşen akıdır."),
    ("aydinlanma", R, "ters-kare-iliskisi", "Noktasal kaynakta E ∝ 1/d²."),
    ("yansima-yasalari", R, "yansima", "Yansımanın yasalarıdır."),
    ("duzlem-ayna", R, "yansima-yasalari", "Görüntü yansıma yasalarıyla bulunur."),
    ("duzlem-ayna", R, "goruntu", "Sanal görüntü oluşturur."),
    ("goruntu", R, "isik", "Işınların kesişiminden oluşur."),
    ("gorus-alani", P, "duzlem-ayna", "Düzlem ayna problem türüdür."),
    ("kuresel-ayna", R, "yansima-yasalari", "Yansıma yasaları geçerlidir."),
    ("cukur-ayna", S, "kuresel-ayna", "Küresel ayna türü."),
    ("tumsek-ayna", S, "kuresel-ayna", "Küresel ayna türü."),
    ("asal-eksen", P, "kuresel-ayna", "Aynanın geometrik öğesi."),
    ("asal-eksen", P, "mercek", "Merceğin geometrik öğesi."),
    ("ayna-tepe-noktasi", P, "kuresel-ayna", "Aynanın geometrik öğesi."),
    ("egrilik-merkezi", P, "kuresel-ayna", "Aynanın geometrik öğesi."),
    ("odak-noktasi", P, "kuresel-ayna", "Aynanın geometrik öğesi."),
    ("odak-noktasi", P, "mercek", "Merceğin geometrik öğesi."),
    ("odak-uzakligi", R, "odak-noktasi", "Odağın uzaklığıdır."),
    ("ozel-isinlar", R, "odak-noktasi", "Kurallar odağa göre tanımlıdır."),
    ("ozel-isinlar", R, "asal-eksen", "Kurallar asal eksene göre tanımlıdır."),
    ("kuresel-aynada-goruntu", R, "kuresel-ayna", "Küresel ayna gerekir."),
    ("kuresel-aynada-goruntu", R, "ozel-isinlar", "Görüntü özel ışınlarla çizilir."),
    ("kuresel-aynada-goruntu", R, "goruntu", "Gerçek/sanal ayrımı."),
    ("kirma-indisi", R, "kirilma", "Kırılmanın niceliğidir."),
    ("snell-yasasi", R, "kirma-indisi", "n₁ sin θ₁ = n₂ sin θ₂."),
    ("snell-yasasi", R, "trigonometrik-oranlar", "Sinüs kullanılır."),
    ("sinir-acisi", R, "snell-yasasi", "Kırılma açısı 90° koşulu."),
    ("tam-yansima", R, "sinir-acisi", "Gelme açısı sınır açısını aşınca oluşur."),
    ("gorunur-derinlik", R, "kirilma", "Kırılmanın sonucudur."),
    ("gorunur-derinlik", R, "kirma-indisi", "Ortamların indisine bağlıdır."),
    ("gercek-derinlik", L, "gorunur-derinlik", "Karşılaştırılır."),
    ("fiber-optik", R, "tam-yansima", "Tam yansımayla çalışır."),
    ("prizma", R, "snell-yasasi", "FİZ.11.3.8: kırılma yasaları prizmaya uygulanır."),
    ("prizma", R, "tek-renkli-isik", "Programda tek renkli ışıkla sınırlı."),
    ("prizma", L, "tam-yansima", "Prizmalarda tam yansıma oluşabilir."),
    ("sapma-acisi", R, "kirilma", "Kırılmanın sonucudur."),
    ("sapma-acisi", P, "prizma", "Prizma problemlerinin büyüklüğüdür."),
    ("mercek", R, "kirilma", "Kırılmayla çalışır."),
    ("yakinsak-mercek", S, "mercek", "Mercek türü."),
    ("iraksak-mercek", S, "mercek", "Mercek türü."),
    ("optik-merkez", P, "mercek", "Merceğin geometrik öğesi."),
    ("mercekte-goruntu", R, "mercek", "Mercek gerekir."),
    ("mercekte-goruntu", R, "ozel-isinlar", "Görüntü özel ışınlarla çizilir."),
    ("mercekte-goruntu", R, "goruntu", "Gerçek/sanal ayrımı."),
    ("cukur-ayna", L, "yakinsak-mercek", "Benzer görüntü özellikleri (toplayıcı)."),
    ("tumsek-ayna", L, "iraksak-mercek", "Benzer görüntü özellikleri (dağıtıcı, hep sanal-küçük-düz)."),
]
