"""STEP 7 — 11. sınıf fizik formül veritabanının elle yazılmış kaynak verisi.

Her formül, MEB 11. sınıf ders kitabının sayfa GÖRÜNTÜSÜNDEN doğrulandı (textbook_page). Metin çıkarımı
sembolleri bozduğu için (ϑ → θ, kesirler) sayfa görüntüsü esas alındı. Kitapta görülmeyenler
textbook_page=None ve verified=False ile işaretlidir.

Boyut analizi: `dims` her formülün iki yanını ve toplam terimlerini {değişken: üs} sözlükleriyle verir;
build_formulas.py hepsinin aynı boyutta olduğunu doğrular. DIM_OVERRIDES ile bilinçli olarak yanlış bir
varsayım (kitaptaki 'k boyutsuz' iddiası) test edilir.

Kitap gösterimi: hız ϑ (theta değil), akım i, manyetik alan katsayısı K, Coulomb sabiti k.
"""

# Temel boyutlar: M kütle, L uzunluk, T zaman, I akım, J ışık şiddeti. Açı ve π boyutsuz.
VAR_DIMS = {
    "h": {"L": 1}, "x": {"L": 1}, "r": {"L": 1}, "d": {"L": 1}, "len": {"L": 1},
    "t": {"T": 1}, "per": {"T": 1}, "dt": {"T": 1},
    "v": {"L": 1, "T": -1}, "c": {"L": 1, "T": -1},
    "g": {"L": 1, "T": -2}, "a": {"L": 1, "T": -2},
    "m": {"M": 1},
    "F": {"M": 1, "L": 1, "T": -2},
    "kf": {},  # sürtünme katsayısı (boyutsuz)
    "kd": {"M": 1, "L": -3},  # akışkan direnç katsayısı (ρ·C_d/2 birimi)
    "A": {"L": 2},
    "w": {"T": -1}, "fr": {"T": -1},
    "q": {"I": 1, "T": 1},
    "kc": {"M": 1, "L": 3, "T": -4, "I": -2},
    "eps0": {"M": -1, "L": -3, "T": 4, "I": 2},
    "E": {"M": 1, "L": 1, "T": -3, "I": -1},
    "V": {"M": 1, "L": 2, "T": -3, "I": -1},
    "B": {"M": 1, "T": -2, "I": -1},
    "Km": {"M": 1, "L": 1, "T": -2, "I": -2},
    "i": {"I": 1},
    "N": {},  # sarım sayısı
    "phiB": {"M": 1, "L": 2, "T": -2, "I": -1},
    "R": {"M": 1, "L": 2, "T": -3, "I": -2},
    "P": {"M": 1, "L": 2, "T": -3},
    "Iv": {"J": 1},       # ışık şiddeti (cd)
    "phiV": {"J": 1},     # ışık akısı (lm = cd·sr; sr boyutsuz)
    "Ev": {"J": 1, "L": -2},
    "n": {}, "ang": {}, "eta": {}, "one": {},
}

# Kitap tablosunda k "boyutsuz bir katsayı" olarak tanımlanıyor (s. 90). Bu varsayımla boyut testi başarısız olmalı.
DIM_OVERRIDES = {"drag-force-textbook-claim": {"kd": {}}}


def F(slug, name, formula, spoken, meaning, lo, page, variables, dims, validity, invalid, mistakes,
      concepts, level="given_in_textbook", notes=None, verified=True):
    return dict(slug=slug, name=name, formula=formula, spoken_tr=spoken, meaning=meaning, learning_outcomes=lo,
                textbook_page=page, textbook_verified=verified and page is not None, variables=variables, dims=dims,
                validity_conditions=validity, invalid_use_cases=invalid, common_mistakes=mistakes,
                related_concepts=concepts, derivation_level=level, notes=notes)


V = lambda sym, name, unit, var, tb=None: {"symbol": sym, "name": name, "si_unit": unit, "dim_var": var,
                                            "textbook_symbol": tb or sym}

FORMULAS = [
    # ===================== ÜNİTE 1 =====================
    F("free-fall-h-v0zero", "Serbest düşmede yükseklik (ilk hız sıfır)", "h = ½·g·t²",
      "h eşittir bir bölü iki g t kare",
      "Durgun hâlden bırakılan cismin t sürede düştüğü yükseklik.", ["FİZ.11.1.2"], 29,
      [V("h", "düşülen yükseklik", "m", "h"), V("g", "yer çekimi ivmesi", "m/s²", "g"), V("t", "süre", "s", "t")],
      [[{"h": 1}], [{"g": 1, "t": 2}]],
      ["İlk hız sıfır", "Hava direnci ihmal", "g sabit (yükseklik Dünya yarıçapına göre küçük)"],
      ["İlk hızı sıfırdan farklı cisimlerde (h = ϑ₀t ± ½gt² kullanılır)", "Hava direncinin önemli olduğu, limit hıza yaklaşan hareketlerde (FİZ.11.1.8)",
       "Cisim yerden yukarı atıldıysa toplam süreye doğrudan uygulanamaz"],
      ["½ katsayısını unutmak", "t'yi değil t²'yi almayı unutmak", "Ardışık eşit sürelerde alınan yolları eşit sanmak (oran 1:3:5:7'dir)"],
      ["serbest-dusme", "yer-cekimi-ivmesi"]),
    F("free-fall-v-v0zero", "Serbest düşmede hız (ilk hız sıfır)", "ϑ = g·t", "hız eşittir g çarpı t",
      "Durgun hâlden bırakılan cismin t anındaki hızı.", ["FİZ.11.1.1", "FİZ.11.1.2"], 29,
      [V("ϑ", "hız", "m/s", "v"), V("g", "yer çekimi ivmesi", "m/s²", "g"), V("t", "süre", "s", "t")],
      [[{"v": 1}], [{"g": 1, "t": 1}]],
      ["İlk hız sıfır", "Hava direnci ihmal", "g sabit"],
      ["İlk hızlı hareketlerde", "Hava direncinin önemli olduğu düşüşlerde (hız sınırsız artmaz)"],
      ["Hızın kütleye bağlı olduğunu sanmak", "Hız birimini m/s² yazmak"],
      ["serbest-dusme", "yer-cekimi-ivmesi", "hiz"]),
    F("free-fall-v2-v0zero", "Zamansız hız bağıntısı (ilk hız sıfır)", "ϑ² = 2·g·h", "hız kare eşittir iki g h",
      "Durgun bırakılan cismin h yükseklik düştükten sonraki hızı; süre bilinmeden kullanılır.", ["FİZ.11.1.2"], 29,
      [V("ϑ", "hız", "m/s", "v"), V("g", "yer çekimi ivmesi", "m/s²", "g"), V("h", "düşülen yükseklik", "m", "h")],
      [[{"v": 2}], [{"g": 1, "h": 1}]],
      ["İlk hız sıfır", "Hava direnci ihmal", "g sabit"],
      ["İlk hızlı hareketlerde (ϑ² = ϑ₀² ± 2gh)", "h yükseklik değil yol (gidiş-dönüş) olarak alınırsa"],
      ["Karekök almayı unutmak", "h'yi yerden yükseklik yerine düşülen mesafe yerine karıştırmak"],
      ["serbest-dusme"]),
    F("free-fall-h-general", "Serbest düşmede konum (ilk hızlı)", "h = ϑ₀·t ± ½·g·t²",
      "h eşittir hız sıfır çarpı t artı eksi bir bölü iki g t kare",
      "İlk hızı ϑ₀ olan düşey harekette t sürede alınan düşey yer değiştirme; aşağı yönlü ilk hızda +, yukarı yönlüde −.",
      ["FİZ.11.1.2"], 29,
      [V("h", "düşey yer değiştirme", "m", "h"), V("ϑ₀", "ilk hız", "m/s", "v"), V("t", "süre", "s", "t"), V("g", "yer çekimi ivmesi", "m/s²", "g")],
      [[{"h": 1}], [{"v": 1, "t": 1}, {"g": 1, "t": 2}]],
      ["Yalnız yer çekimi etkisi (hava direnci ihmal)", "g sabit", "İşaret seçimi hareket boyunca tutarlı"],
      ["Yatayda ilk hız bileşeni varken düşey bileşen yerine toplam hız konursa", "Hava direnci önemliyse"],
      ["± işaretini ilk hızın yönüne göre seçmemek", "Yukarı atışta tepe noktasından sonra işaret değiştirmeye çalışıp karışıklık yaratmak",
       "Yer değiştirme ile alınan yolu karıştırmak"],
      ["serbest-dusme", "tepe-noktasi-hareket", "maksimum-yukseklik"]),
    F("free-fall-v-general", "Serbest düşmede hız (ilk hızlı)", "ϑ = ϑ₀ ± g·t", "hız eşittir hız sıfır artı eksi g t",
      "İlk hızı ϑ₀ olan düşey harekette t anındaki hız.", ["FİZ.11.1.2"], 29,
      [V("ϑ", "hız", "m/s", "v"), V("ϑ₀", "ilk hız", "m/s", "v"), V("g", "yer çekimi ivmesi", "m/s²", "g"), V("t", "süre", "s", "t")],
      [[{"v": 1}], [{"v": 1}, {"g": 1, "t": 1}]],
      ["Yalnız yer çekimi etkisi", "g sabit"],
      ["Hava direncinin önemli olduğu durumlarda"],
      ["Tepe noktasında ivmenin de sıfır olduğunu sanmak (ivme her an g)", "Çıkış ve iniş sürelerinin farklı olduğunu sanmak (aynı seviyede eşittir)"],
      ["serbest-dusme", "tepe-noktasi-hareket"]),
    F("free-fall-v2-general", "Zamansız hız bağıntısı (ilk hızlı)", "ϑ² = ϑ₀² ± 2·g·h",
      "hız kare eşittir hız sıfır kare artı eksi iki g h", "Süre bilinmeden hız ile yer değiştirme arasındaki ilişki.",
      ["FİZ.11.1.2"], 29,
      [V("ϑ", "son hız", "m/s", "v"), V("ϑ₀", "ilk hız", "m/s", "v"), V("g", "yer çekimi ivmesi", "m/s²", "g"), V("h", "düşey yer değiştirme", "m", "h")],
      [[{"v": 2}], [{"v": 2}, {"g": 1, "h": 1}]],
      ["Yalnız yer çekimi etkisi", "g sabit", "h yer değiştirmedir (yol değil)"],
      ["h yerine toplam alınan yol konursa (yukarı çıkıp inen cisimde)"],
      ["Maksimum yükseklikte ϑ = 0 koşulunu kullanmayı unutmak (h_max = ϑ₀²/2g)"],
      ["serbest-dusme", "maksimum-yukseklik"]),
    F("2d-horizontal-range", "İki boyutlu harekette yatay konum ve menzil", "x = ϑₓ·t ;  x_menzil = ϑₓ·t_uçuş",
      "x eşittir hız x çarpı t; menzil eşittir hız x çarpı uçuş süresi",
      "Yatay bileşen sabit hızlıdır; menzil, yatay hızın uçuş süresiyle çarpımıdır.", ["FİZ.11.1.3"], 39,
      [V("x", "yatay konum", "m", "x"), V("ϑₓ", "hızın yatay bileşeni", "m/s", "v"), V("t", "süre", "s", "t")],
      [[{"x": 1}], [{"v": 1, "t": 1}]],
      ["Yalnız yer çekimi etkisi (yatayda ivme yok)", "Hava direnci ihmal"],
      ["Yatayda bir kuvvet/ivme varsa (ör. rüzgâr)", "Hareketli referanstan atılan cisimde zemine göre hız kullanılmazsa (zenginleştirme konusu)"],
      ["ϑₓ yerine ilk hızın büyüklüğünü (ϑ₀) koymak", "Uçuş süresini yatay hareketten bulmaya çalışmak (düşeyden bulunur)"],
      ["iki-boyutta-sabit-ivmeli-hareket", "menzil", "ucus-suresi", "bilesenlerin-bagimsizligi"]),
    F("2d-velocity-components", "İlk hızın bileşenleri", "ϑₓ = ϑ₀·cosα ;  ϑᵧ = ϑ₀·sinα",
      "hız x eşittir hız sıfır kosinüs alfa; hız y eşittir hız sıfır sinüs alfa",
      "Yatayla α açısı yapan ilk hızın yatay ve düşey bileşenleri.", ["FİZ.11.1.3"], None,
      [V("ϑ₀", "ilk hız", "m/s", "v"), V("α", "atış açısı (yatayla)", "°", "ang")],
      [[{"v": 1}], [{"v": 1, "ang": 1}]],
      ["α yatayla ölçülür", "Bileşenler dik eksenlerde"],
      ["Açı düşeyle verilmişse sin ve cos yer değiştirir", "Yatay ilk hızlı harekette (α = 0) ϑᵧ = 0 olduğunu unutmamak gerekir"],
      ["Açının hangi eksenle verildiğine bakmamak", "Özel üçgen değerlerini (37°-53°, 30°-60°) karıştırmak"],
      ["vektor-bilesenleri", "trigonometrik-oranlar", "iki-boyutta-sabit-ivmeli-hareket"], level="derived",
      notes="Program FİZ.11.1.3 öğretme uygulaması trigonometrik bileşen hesabını açıkça istiyor; kitapta formül kutusu sayfa görüntüsünde doğrulanmadı."),
    F("2d-vertical-up-phase", "İki boyutlu harekette düşey bileşen (yükselme)", "h = ϑᵧ·t − ½·g·t² ;  ϑᵧ₁ = ϑᵧ − g·t ;  ϑ² = ϑᵧ² − 2·g·h",
      "h eşittir hız y çarpı t eksi bir bölü iki g t kare", "Düşey bileşen, ilk hızı ϑᵧ olan yukarı yönlü serbest düşmedir.",
      ["FİZ.11.1.3"], 39,
      [V("h", "düşey yer değiştirme", "m", "h"), V("ϑᵧ", "hızın düşey bileşeni", "m/s", "v"), V("g", "yer çekimi ivmesi", "m/s²", "g"), V("t", "süre", "s", "t")],
      [[{"h": 1}], [{"v": 1, "t": 1}, {"g": 1, "t": 2}]],
      ["Yalnız yer çekimi etkisi", "Düşey bileşene uygulanır, toplam hıza değil"],
      ["Toplam hız (ϑ₀) düşey bileşen yerine konursa"],
      ["Tepe noktasında hızın sıfır olduğunu sanmak (yalnız düşey bileşen sıfır, yatay bileşen ϑₓ)"],
      ["iki-boyutta-sabit-ivmeli-hareket", "maksimum-yukseklik", "tepe-noktasi-hareket"]),
    F("newton-second-law", "Newton'ın 2. Hareket Yasası", "F⃗_net = m·a⃗", "F net eşittir m çarpı a",
      "Bileşke kuvvet, kütle ile ivmenin çarpımına eşittir; ivme bileşke kuvvet yönündedir.", ["FİZ.11.1.4", "FİZ.11.1.5"], 64,
      [V("F_net", "bileşke kuvvet", "N", "F"), V("m", "kütle", "kg", "m"), V("a", "ivme", "m/s²", "a")],
      [[{"F": 1}], [{"m": 1, "a": 1}]],
      ["Eylemsiz (ivmesiz) referans sistemi", "F_net tüm dış kuvvetlerin vektörel toplamı", "Kütle sabit"],
      ["Tek bir kuvvet (bileşke değil) konursa", "Programda: farklı ivmeli cisimlerden oluşan sistemlerin tek denklemle çözümü (kapsam dışı)"],
      ["Etki-tepki kuvvetlerini aynı cisme etki ediyor sanıp birbirini götürmek", "Ağırlığı ve normal kuvveti her durumda eşit sanmak", "Hız yönünü ivme yönü sanmak"],
      ["newton-ikinci-yasa", "bileske-kuvvet"]),
    F("weight", "Ağırlık", "G = m·g", "G eşittir m çarpı g", "Cisme etki eden yer çekimi kuvveti.", ["FİZ.11.1.5", "FİZ.11.1.10"], 116,
      [V("G", "ağırlık", "N", "F"), V("m", "kütle", "kg", "m"), V("g", "yer çekimi ivmesi", "m/s²", "g")],
      [[{"F": 1}], [{"m": 1, "g": 1}]],
      ["Yer yüzeyine yakın, g sabit"],
      ["Kütle ile ağırlığın aynı nicelik olarak kullanılması"],
      ["Kütle birimini N, ağırlık birimini kg yazmak"],
      ["agirlik", "yer-cekimi-ivmesi"], notes="10. sınıf ön koşulu; kitapta serbest cisim diyagramlarında kullanılıyor."),
    F("frictionless-incline", "Sürtünmesiz eğik düzlemde ivme", "a = g·sinθ", "a eşittir g sinüs teta",
      "Sürtünmesiz eğik düzlemde serbest kayan cismin ivmesi; ağırlığın düzleme paralel bileşeninden gelir.", ["FİZ.11.1.5"], 60,
      [V("a", "ivme", "m/s²", "a"), V("g", "yer çekimi ivmesi", "m/s²", "g"), V("θ", "eğim açısı (yatayla)", "°", "ang")],
      [[{"a": 1}], [{"g": 1, "ang": 1}]],
      ["Sürtünme yok", "Cisme yalnız ağırlık ve normal kuvvet etki ediyor", "θ yatayla ölçülür"],
      ["Sürtünmeli eğik düzlemde", "Cisme ek bir kuvvet uygulanıyorsa", "Açı düşeyle verilmişse"],
      ["sin yerine cos almak", "Normal kuvveti ağırlığa eşit almak (eğik düzlemde N = m·g·cosθ)"],
      ["egik-duzlem", "vektor-bilesenleri", "newton-ikinci-yasa"], level="derived_in_textbook"),
    F("pendulum-in-accelerating-car", "İvmeli araçta asılı cismin sapma açısı", "tanθ = a/g", "tanjant teta eşittir a bölü g",
      "Yatayda a ivmesiyle hızlanan araçta tavana asılı cismin düşeyle yaptığı açı.", ["FİZ.11.1.5"], 63,
      [V("θ", "düşeyle açı", "°", "ang"), V("a", "aracın ivmesi", "m/s²", "a"), V("g", "yer çekimi ivmesi", "m/s²", "g")],
      [[{"ang": 1}], [{"a": 1, "g": -1}]],
      ["Araç sabit ivmeli, cisim araca göre durgun", "Hava direnci ihmal"],
      ["Araç sabit hızla gidiyorsa (θ = 0)", "Cisim salınım yapıyorsa"],
      ["Açının kütleye bağlı olduğunu sanmak", "Sapmanın ivme yönünde olduğunu sanmak (ivmenin tersine sapar)"],
      ["newton-ikinci-yasa", "serbest-cisim-diyagrami", "gerilme-kuvveti"], level="derived_in_textbook"),
    F("system-acceleration", "Aynı ivmeli bağlı sistemin ivmesi", "a = ΣF_dış / Σm", "a eşittir dış kuvvetlerin toplamı bölü toplam kütle",
      "Birlikte aynı ivmeyle hareket eden cisimler tek cisim gibi ele alınır.", ["FİZ.11.1.5", "FİZ.11.1.7"], 80,
      [V("a", "sistem ivmesi", "m/s²", "a"), V("ΣF_dış", "dış kuvvetlerin bileşkesi", "N", "F"), V("Σm", "toplam kütle", "kg", "m")],
      [[{"a": 1}], [{"F": 1, "m": -1}]],
      ["Tüm cisimler aynı büyüklükte ivmeyle hareket ediyor (ip gergin, kaymıyor)", "İp kütlesiz, makara sürtünmesiz"],
      ["Cisimler farklı ivmeyle hareket ediyorsa (program: kapsam dışı)", "İp gevşekse", "İç kuvvetler (ip gerilmesi) dış kuvvet gibi toplanırsa"],
      ["İp gerilmesini dış kuvvet sanmak", "Sistem ivmesini bulduktan sonra ip gerilmesini tek cisim üzerinden hesaplamamak"],
      ["bagli-cisim-sistemi", "newton-ikinci-yasa", "gerilme-kuvveti"], level="derived_in_textbook"),
    F("friction-model", "Sürtünme kuvvetinin matematiksel modeli", "f = k·N  (statik: f_s ≤ k_s·N ;  kinetik: f_k = k_k·N)",
      "f eşittir k çarpı N", "Sürtünme kuvveti, sürtünme katsayısı ile normal kuvvetin çarpımıdır; statikte bu değer üst sınırdır.",
      ["FİZ.11.1.7"], 85,
      [V("f", "sürtünme kuvveti", "N", "F"), V("k", "sürtünme katsayısı", "—", "kf"), V("N", "normal kuvvet", "N", "F")],
      [[{"F": 1}], [{"kf": 1, "F": 1}]],
      ["Kinetik: cisim yüzeyde kayıyor", "Statik: k_s·N maksimum değerdir; cisim kaymıyorsa f_s uygulanan kuvvete eşittir (f_s = F)", "Kuru yüzeyler"],
      ["Cisim kaymıyorken f_s = k_s·N almak (yalnız harekete geçme sınırında geçerli)", "Normal kuvvet yerine her durumda m·g almak (eğik düzlem, ek düşey kuvvet)",
       "Akışkan direncinde (hız ve kesit alanına bağlı, F_d = k·A·ϑ²)"],
      ["Statik sürtünmeyi her zaman maksimum değerinde sanmak", "Sürtünmenin temas yüzey alanına bağlı olduğunu sanmak", "Sürtünmenin her zaman harekete zıt olduğunu sanmak (yürümede ileri yönlüdür)"],
      ["surtunme-kuvveti", "statik-surtunme", "kinetik-surtunme", "surtunme-katsayisi", "normal-kuvvet", "maksimum-statik-surtunme"]),
    F("kinetic-coefficient-incline", "Eğik düzlemde sabit hızla kaymadan katsayı", "k_k = tanθ", "k kinetik eşittir tanjant teta",
      "Eğik düzlemde kendiliğinden sabit hızla kayan cisim için kinetik sürtünme katsayısı.", ["FİZ.11.1.7"], 82,
      [V("k_k", "kinetik sürtünme katsayısı", "—", "kf"), V("θ", "eğim açısı", "°", "ang")],
      [[{"kf": 1}], [{"ang": 1}]],
      ["Cisim yalnız ağırlık, normal ve sürtünme etkisinde", "Sabit hızla kayıyor (ivme sıfır)"],
      ["Cisim ivmeli kayıyorsa", "Ek bir kuvvet uygulanıyorsa", "Harekete geçme anı için statik katsayı aranıyorsa (k_s = tanθ_s, θ_s harekete başlama açısı)"],
      ["Statik ve kinetik katsayıyı karıştırmak"],
      ["surtunme-katsayisi", "egik-duzlem", "kinetik-surtunme"], level="derived_in_textbook"),
    F("drag-force", "Akışkan direnç kuvveti", "F_d = k·A·ϑ²", "F d eşittir k çarpı A çarpı hız kare",
      "Akışkan içinde hareket eden cisme etki eden direnç kuvvetinin büyüklüğü.", ["FİZ.11.1.8"], 90,
      [V("F_d", "direnç kuvveti", "N", "F"), V("k", "direnç katsayısı (ortam ve şekle bağlı)", "kg/m³", "kd"),
       V("A", "harekete dik kesit alanı", "m²", "A"), V("ϑ", "akışkana göre hız", "m/s", "v")],
      [[{"F": 1}], [{"kd": 1, "A": 1, "v": 2}]],
      ["Yüksek hızlı (türbülanslı) akış yaklaşımı", "k ortama ve cismin şekline bağlı sabit"],
      ["Programda sayısal hesap istenmez: FİZ.11.1.8 'yorumlamalarla sınırlı kalınır'", "Kuru yüzey sürtünmesinde (f = k·N)", "Çok düşük hızlarda (direnç hızla doğrusal artar)"],
      ["Direnç kuvvetinin kütleye bağlı olduğunu sanmak", "k'yı sürtünme katsayısıyla aynı (boyutsuz) sanmak"],
      ["hava-direnci", "kesit-alani", "limit-hiz"],
      notes="KAYNAK HATASI: Kitap Tablo 1.2 (s. 90) k'yı 'boyutsuz bir katsayı' olarak tanımlıyor. Boyut analizi k'nın birimini kg/m³ verir; k boyutsuz olamaz. Bu kayıt boyut testinde ayrıca doğrulanır (DIM_OVERRIDES)."),
    F("terminal-velocity", "Limit hız", "ϑ_limit = √( m·g / (k·A) )", "hız limit eşittir karekök içinde m g bölü k A",
      "Direnç kuvvetinin ağırlığa eşitlendiği andaki sabit hız.", ["FİZ.11.1.8"], 90,
      [V("ϑ_limit", "limit hız", "m/s", "v"), V("m", "kütle", "kg", "m"), V("g", "yer çekimi ivmesi", "m/s²", "g"),
       V("k", "direnç katsayısı", "kg/m³", "kd"), V("A", "kesit alanı", "m²", "A")],
      [[{"v": 2}], [{"m": 1, "g": 1, "kd": -1, "A": -1}]],
      ["F_d = k·A·ϑ² modeli geçerli", "Cisim düşey düşüyor, net kuvvet sıfır"],
      ["Programda sayısal hesap istenmez; yalnız orantı yorumu (m↑ → ϑ_limit↑, A↑ → ϑ_limit↓)", "Hava direnci ihmal edilen serbest düşmede"],
      ["Limit hızda ivmenin g olduğunu sanmak (ivme sıfırdır)", "Paraşüt açılınca cismin yukarı gittiğini sanmak (yavaşlar, yön değişmez)"],
      ["limit-hiz", "hava-direnci", "newton-birinci-yasa"], level="derived_in_textbook"),
    F("period-frequency", "Periyot-frekans ilişkisi", "T·f = 1", "T çarpı f eşittir bir",
      "Periyot ve frekans birbirinin tersidir.", ["FİZ.11.1.10", "FİZ.11.2.12"], 104,
      [V("T", "periyot", "s", "per"), V("f", "frekans", "Hz", "fr")],
      [[{"per": 1, "fr": 1}], [{"one": 1}]],
      ["Periyodik hareket"],
      ["Periyodik olmayan harekette"],
      ["Frekansı devir sayısı ile karıştırmak (birim zamandaki devir sayısıdır)", "Dakikadaki devir sayısını saniyeye çevirmemek"],
      ["periyot", "frekans"], notes="10. sınıf ön koşulu; kitap s. 104'te hatırlatma kutusunda."),
    F("linear-speed-circular", "Çizgisel sürat", "ϑ = 2·π·r / T = 2·π·r·f", "hız eşittir iki pi r bölü T",
      "Düzgün çembersel harekette birim zamanda alınan yay uzunluğu.", ["FİZ.11.1.10"], 104,
      [V("ϑ", "çizgisel sürat", "m/s", "v"), V("r", "yarıçap", "m", "r"), V("T", "periyot", "s", "per")],
      [[{"v": 1}], [{"r": 1, "per": -1}]],
      ["Düzgün çembersel hareket (sabit sürat)"],
      ["Sürat değişiyorsa (düzgün olmayan çembersel hareket)", "r yerine çap konursa"],
      ["Çizgisel hızın yönünün sabit olduğunu sanmak", "Çap ile yarıçapı karıştırmak"],
      ["cizgisel-surat", "cizgisel-hiz", "periyot"]),
    F("angular-speed", "Açısal hız", "ω = 2·π / T = 2·π·f", "omega eşittir iki pi bölü T",
      "Yarıçap vektörünün birim zamanda taradığı açı (radyan).", ["FİZ.11.1.10"], 104,
      [V("ω", "açısal hız", "rad/s", "w"), V("T", "periyot", "s", "per")],
      [[{"w": 1}], [{"per": -1}]],
      ["Düzgün çembersel hareket", "Açı radyan cinsinden"],
      ["Açı derece cinsinden kullanılırsa"],
      ["ω'yi frekansla aynı sanmak (ω = 2πf)", "Aynı eksende dönen noktaların açısal hızlarını farklı sanmak"],
      ["acisal-hiz", "periyot", "frekans"]),
    F("v-omega-r", "Çizgisel ve açısal hız ilişkisi", "ϑ = ω·r", "hız eşittir omega çarpı r",
      "Çizgisel sürat, açısal hız ile yarıçapın çarpımıdır.", ["FİZ.11.1.10"], 104,
      [V("ϑ", "çizgisel sürat", "m/s", "v"), V("ω", "açısal hız", "rad/s", "w"), V("r", "yarıçap", "m", "r")],
      [[{"v": 1}], [{"w": 1, "r": 1}]],
      ["Açısal hız radyan/saniye"],
      ["Kayışla ya da temasla bağlı farklı tekerleklerde ω'nin eşit sanılması (bu durumda çizgisel süratler eşittir)"],
      ["Aynı eksenli tekerleklerde ϑ'nin, kayışla bağlı tekerleklerde ω'nin eşit olduğunu karıştırmak"],
      ["cizgisel-surat", "acisal-hiz"]),
    F("centripetal-acceleration", "Merkezcil ivme", "a = ϑ²/r = ω²·r = 4·π²·f²·r", "a eşittir hız kare bölü r",
      "Hız vektörünün yön değişiminden doğan, merkeze yönelik ivme.", ["FİZ.11.1.10"], 109,
      [V("a", "merkezcil ivme", "m/s²", "a"), V("ϑ", "çizgisel sürat", "m/s", "v"), V("r", "yarıçap", "m", "r")],
      [[{"a": 1}], [{"v": 2, "r": -1}, {"w": 2, "r": 1}, {"fr": 2, "r": 1}]],
      ["Düzgün çembersel hareket"],
      ["Teğetsel ivmenin olduğu (sürati değişen) harekette toplam ivme yerine kullanılması"],
      ["Sabit süratte ivme olmadığını sanmak", "İvmenin dışa (merkezkaç) yönlü olduğunu sanmak"],
      ["merkezcil-ivme", "cizgisel-hiz", "acisal-hiz"]),
    F("centripetal-force", "Merkezcil kuvvet", "F_m = m·ϑ²/r = m·ω²·r", "F m eşittir m hız kare bölü r",
      "Çembersel hareketi sağlayan, merkeze yönelik bileşke kuvvet.", ["FİZ.11.1.10"], 108,
      [V("F_m", "merkezcil kuvvet", "N", "F"), V("m", "kütle", "kg", "m"), V("ϑ", "çizgisel sürat", "m/s", "v"), V("r", "yarıçap", "m", "r")],
      [[{"F": 1}], [{"m": 1, "v": 2, "r": -1}, {"m": 1, "w": 2, "r": 1}]],
      ["Düzgün çembersel hareket", "F_m, cisme etki eden gerçek kuvvetlerin merkeze yönelik bileşkesidir"],
      ["Serbest cisim diyagramına ayrı bir 'merkezcil kuvvet' oku eklenirse (çift sayım)", "Ray sistemlerinde sayısal hesap (program: kapsam dışı)"],
      ["Merkezcil kuvveti ayrı bir kuvvet türü sanmak", "Merkezkaç kuvvetini gerçek kuvvet sanmak", "İp koptuğunda cismin dışa doğru gideceğini sanmak (teğet doğrultuda gider)"],
      ["merkezcil-kuvvet", "newton-ikinci-yasa", "bileske-kuvvet"]),
    F("vertical-circle-forces", "Düşey düzlemde çembersel harekette kuvvetler", "Tepe: F_m = T + G ;  Dip: F_m = T − G ;  Yan: F_m = T",
      "tepede F m eşittir T artı G; dipte F m eşittir T eksi G",
      "İpe bağlı cismin farklı noktalarında merkezcil kuvveti veren bağıntılar (kitap Tablo 1.3).", ["FİZ.11.1.10"], 110,
      [V("F_m", "merkezcil kuvvet", "N", "F"), V("T", "ip gerilmesi", "N", "F"), V("G", "ağırlık", "N", "F")],
      [[{"F": 1}], [{"F": 1}, {"F": 1}]],
      ["Kitap ve programda sabit süratle (düzgün) dönen cisim kabulü", "İp kütlesiz"],
      ["Gerçekte sürat tepe ve dipte farklıysa her noktada aynı ϑ kullanılması (kitap s. 112 bunu enerji korunumuyla ayrıca ele alır)",
       "Çubuk/ray sistemlerinde (ray: kapsam dışı)"],
      ["Tepe noktasında ağırlığın yönünü yanlış almak", "Dipte gerilmenin ağırlıktan küçük olabileceğini sanmak"],
      ["dusey-duzlemde-cembersel", "merkezcil-kuvvet", "gerilme-kuvveti", "agirlik"], level="derived_in_textbook"),
    F("vertical-circle-min-speed", "Düşey çemberin tepesinde en küçük hız", "ϑ_min = √(g·r)", "hız min eşittir karekök g r",
      "İpe bağlı cismin (ya da kovadaki suyun) tepe noktasından geçebilmesi için gereken en küçük sürat; ip gerilmesi sıfır.", ["FİZ.11.1.10"], 111,
      [V("ϑ_min", "en küçük sürat", "m/s", "v"), V("g", "yer çekimi ivmesi", "m/s²", "g"), V("r", "yarıçap", "m", "r")],
      [[{"v": 2}], [{"g": 1, "r": 1}]],
      ["İp ya da kova (yalnız çekebilen/itebilen tek yönlü bağ)", "Tepe noktası"],
      ["Çubuğa bağlı cisimde (çubuk itebilir, ϑ_min = 0 olabilir)", "Dip noktasında"],
      ["Kütleye bağlı olduğunu sanmak"],
      ["dusey-duzlemde-cembersel", "merkezcil-kuvvet"], level="derived_in_textbook"),
    F("banked-curve-speed", "Sürtünmesiz eğimli virajda güvenli hız", "ϑ = √(tanθ·g·r)", "hız eşittir karekök tanjant teta g r",
      "Sürtünme olmadan, normal kuvvetin yatay bileşeniyle dönülebilen hız.", ["FİZ.11.1.10"], 116,
      [V("ϑ", "güvenli hız", "m/s", "v"), V("θ", "viraj eğim açısı", "°", "ang"), V("g", "yer çekimi ivmesi", "m/s²", "g"), V("r", "yarıçap", "m", "r")],
      [[{"v": 2}], [{"ang": 1, "g": 1, "r": 1}]],
      ["Sürtünme yok", "θ yatayla ölçülür"],
      ["Sürtünmeli eğimli virajda (hız aralığı değişir)", "Yatay virajda (θ = 0)"],
      ["Güvenli hızın araç kütlesine bağlı olduğunu sanmak"],
      ["egimli-viraj", "merkezcil-kuvvet", "normal-kuvvet"], level="derived_in_textbook",
      notes="KAYNAK TUTARSIZLIĞI: Kitap s. 116'da metin N_x'i yatay (merkezcil), N_y'yi düşey bileşen olarak tanımlıyor; hemen altındaki denklemlerde alt indisler ters (N_y = N·sinθ = F_m, N_x = N·cosθ = m·g). Sonuç formülü doğru."),
    F("flat-curve-max-speed", "Yatay virajda kaymadan dönme hızı", "ϑ_max = √(k_s·g·r)", "hız max eşittir karekök k g r",
      "Merkezcil kuvveti statik sürtünmenin sağladığı yatay virajda kaymadan dönülebilecek en büyük hız.", ["FİZ.11.1.10"], None,
      [V("ϑ_max", "en büyük hız", "m/s", "v"), V("k_s", "statik sürtünme katsayısı", "—", "kf"), V("g", "yer çekimi ivmesi", "m/s²", "g"), V("r", "yarıçap", "m", "r")],
      [[{"v": 2}], [{"kf": 1, "g": 1, "r": 1}]],
      ["Yatay yol", "Merkezcil kuvveti yalnız statik sürtünme sağlar"],
      ["Eğimli virajda", "Araç kayıyorsa (kinetik sürtünme)"],
      ["Kinetik sürtünme katsayısını kullanmak", "Kütleye bağlı olduğunu sanmak"],
      ["yatay-viraj", "statik-surtunme", "merkezcil-kuvvet"], level="derived",
      notes="Kitapta s. 109 (41. Alıştırma) ve s. 117 (45c) bu modeli gerektiren sorular var; formül kutusu sayfa görüntüsünde doğrulanmadı."),

    # ===================== ÜNİTE 2 =====================
    F("coulomb-law", "Coulomb Yasası", "F = k·q₁·q₂ / d²", "F eşittir k çarpı q bir çarpı q iki bölü d kare",
      "İki noktasal yük arasındaki elektriksel kuvvetin büyüklüğü.", ["FİZ.11.2.1"], 160,
      [V("F", "elektriksel kuvvet", "N", "F"), V("k", "Coulomb sabiti", "N·m²/C²", "kc"), V("q₁, q₂", "yükler", "C", "q"), V("d", "yükler arası uzaklık", "m", "d")],
      [[{"F": 1}], [{"kc": 1, "q": 2, "d": -2}]],
      ["Noktasal yükler (boyutlar d'ye göre küçük)", "Yükler durgun", "k ortama bağlı (boşlukta ≈ 9·10⁹)"],
      ["PROGRAM: FİZ.11.2.1 'matematiksel hesaplamalara girmeden'; sayısal hesap yerine oran/yön yorumu beklenir", "Yüklü küre içinde/üzerinde ya da noktasal olmayan dağılımlarda"],
      ["d yerine d² almamak", "Kuvvetlerin yük büyüklükleri farklıyken de eşit olduğunu unutmak (etki-tepki)", "Yük işaretini büyüklük hesabına katıp yönü işaretten okumaya çalışmak"],
      ["coulomb-yasasi", "elektriksel-kuvvet", "ters-kare-iliskisi", "coulomb-sabiti"]),
    F("coulomb-constant", "Coulomb sabiti", "k = 1/(4·π·ε₀) ≈ 9·10⁹ N·m²/C²", "k eşittir bir bölü dört pi epsilon sıfır",
      "Boşlukta Coulomb sabitinin değeri ve elektriksel geçirgenlikle ilişkisi.", ["FİZ.11.2.1"], 161,
      [V("k", "Coulomb sabiti", "N·m²/C²", "kc"), V("ε₀", "boşluğun elektriksel geçirgenliği", "C²/(N·m²)", "eps0")],
      [[{"kc": 1}], [{"eps0": -1}]],
      ["Boşluk (hava için yaklaşık aynı)"],
      ["Yalıtkan ortamda boşluk değeri kullanılırsa (k küçülür)"],
      ["k'nın her ortamda aynı olduğunu sanmak"],
      ["coulomb-sabiti"], notes="Kitapta kenar notu (s. 161)."),
    F("electric-field-definition", "Elektriksel alanın tanımı", "E = F / q₀", "E eşittir F bölü q sıfır",
      "Birim (deneme) yük başına düşen elektriksel kuvvet.", ["FİZ.11.2.2"], 185,
      [V("E", "elektriksel alan", "N/C", "E"), V("F", "kuvvet", "N", "F"), V("q₀", "deneme yükü", "C", "q")],
      [[{"E": 1}], [{"F": 1, "q": -1}]],
      ["q₀ alanı bozmayacak kadar küçük pozitif deneme yükü"],
      ["PROGRAM: FİZ.11.2.2 hesaplamasız", "q₀ alanı oluşturan yükün kendisi alınırsa"],
      ["Alanın deneme yüküne bağlı olduğunu sanmak"],
      ["elektriksel-alan"]),
    F("point-charge-field", "Noktasal yükün elektriksel alanı", "E = k·q / d²", "E eşittir k q bölü d kare",
      "Noktasal yükün d uzaklıkta oluşturduğu alanın büyüklüğü; yön + yükten dışa, − yüke doğru.", ["FİZ.11.2.2"], 185,
      [V("E", "elektriksel alan", "N/C", "E"), V("k", "Coulomb sabiti", "N·m²/C²", "kc"), V("q", "kaynak yük", "C", "q"), V("d", "uzaklık", "m", "d")],
      [[{"E": 1}], [{"kc": 1, "q": 1, "d": -2}]],
      ["Noktasal yük", "Birden çok yükte alanlar vektörel toplanır"],
      ["PROGRAM: FİZ.11.2.2 hesaplamasız; oran ve yön yorumu beklenir", "Bileşke alan büyüklükleri skaler toplanırsa"],
      ["Alanları vektörel değil cebirsel toplamak", "Negatif yükün alan yönünü dışa doğru çizmek"],
      ["elektriksel-alan", "bileske-elektriksel-alan", "ters-kare-iliskisi"]),
    F("uniform-field-plates", "Paralel levhalar arasında düzgün elektriksel alan", "E = V / d", "E eşittir V bölü d",
      "Potansiyel farkı V, aralığı d olan paralel levhalar arasındaki düzgün alan.", ["FİZ.11.2.2"], 185,
      [V("E", "elektriksel alan", "N/C (= V/m)", "E"), V("V", "potansiyel fark", "V", "V"), V("d", "levhalar arası uzaklık", "m", "d")],
      [[{"E": 1}], [{"V": 1, "d": -1}]],
      ["Levhalar paralel ve geniş, kenar etkileri ihmal"],
      ["Noktasal yük alanında", "PROGRAM: FİZ.11.2.2 hesaplamasız ve programda 'düzgün alan/levha' açıkça yok"],
      ["Alanın levhalara yakınlığa göre değiştiğini sanmak (düzgün alanda her yerde aynı)"],
      ["elektriksel-alan", "potansiyel-fark"],
      notes="Kitapta var (s. 176, 185); programın 11. sınıf çıktılarında levha/düzgün alan adı geçmiyor. Kapsam belirsiz."),
    F("straight-wire-field", "Akım geçen düz telin manyetik alanı", "B = 2·K·i / d", "B eşittir iki K i bölü d",
      "Sonsuz uzun düz telden d uzaklıktaki manyetik alanın büyüklüğü; yön sağ el kuralıyla.", ["FİZ.11.2.5"], 235,
      [V("B", "manyetik alan", "T", "B"), V("K", "manyetik alan katsayısı (10⁻⁷ T·m/A)", "T·m/A", "Km"), V("i", "akım", "A", "i"), V("d", "telden uzaklık", "m", "d")],
      [[{"B": 1}], [{"Km": 1, "i": 1, "d": -1}]],
      ["Uzun düz tel", "d tel uzunluğuna göre küçük"],
      ["PROGRAM: FİZ.11.2.5 'matematiksel hesaplamalara girmeden'; oran/yön yorumu beklenir", "Halka ya da makara için"],
      ["B'nin d² ile ters orantılı olduğunu sanmak (d ile ters orantılı)", "Alan yönünü tele paralel çizmek (tel etrafında çemberseldir)"],
      ["duz-telin-manyetik-alani", "manyetik-alan-katsayisi", "sag-el-kurali"]),
    F("solenoid-field", "Akım makarasının merkez eksenindeki manyetik alan", "B = 4·π·K·i·N / L", "B eşittir dört pi K i N bölü L",
      "Uzunluğu L, sarım sayısı N olan makaranın ekseninde oluşan alan.", ["FİZ.11.2.6"], 235,
      [V("B", "manyetik alan", "T", "B"), V("K", "manyetik alan katsayısı", "T·m/A", "Km"), V("i", "akım", "A", "i"), V("N", "sarım sayısı", "—", "N"), V("L", "makara boyu", "m", "len")],
      [[{"B": 1}], [{"Km": 1, "i": 1, "N": 1, "len": -1}]],
      ["Uzun makara, merkez ekseni", "Hava çekirdekli"],
      ["Demir çekirdekli makarada (alan çok artar)", "Makara uçlarında"],
      ["Alanın makara yarıçapına bağlı olduğunu sanmak", "N/L yerine yalnız N'ye bakmak"],
      ["akim-makarasi", "sarim-sayisi", "manyetik-alan-katsayisi"],
      notes="Program FİZ.11.2.6 için açık hesap sınırı koymuyor; kitapta formül var."),
    F("force-on-wire", "Manyetik alanda akım geçen tele etki eden kuvvet", "F = B·i·L·sinθ", "F eşittir B i L sinüs teta",
      "Manyetik alandaki akım geçen düz tele etki eden kuvvet; θ alan ile tel arasındaki açı.", ["FİZ.11.2.8"], 235,
      [V("F", "manyetik kuvvet", "N", "F"), V("B", "manyetik alan", "T", "B"), V("i", "akım", "A", "i"), V("L", "tel uzunluğu (alan içindeki)", "m", "len"), V("θ", "alan-tel açısı", "°", "ang")],
      [[{"F": 1}], [{"B": 1, "i": 1, "len": 1, "ang": 1}]],
      ["Düzgün manyetik alan", "Düz tel"],
      ["Tel alana paralelse (θ = 0, F = 0)", "Hareketli tek yüke etki eden kuvvet (qϑB) bu çıktıda yok"],
      ["Kuvvet yönünü alan yönünde sanmak (kuvvet hem alana hem tele diktir)", "sinθ'yı unutmak"],
      ["tele-etki-eden-manyetik-kuvvet", "manyetik-kuvvet", "sag-el-kurali"]),
    F("magnetic-flux", "Manyetik akı", "Φ = B·A·cosθ", "fi eşittir B A kosinüs teta",
      "Bir yüzeyden geçen manyetik alan çizgilerinin ölçüsü; θ alan ile yüzey normali arasındaki açı.", ["FİZ.11.2.10"], 262,
      [V("Φ", "manyetik akı", "Wb", "phiB"), V("B", "manyetik alan", "T", "B"), V("A", "yüzey alanı", "m²", "A"), V("θ", "alan-normal açısı", "°", "ang")],
      [[{"phiB": 1}], [{"B": 1, "A": 1, "ang": 1}]],
      ["Düzgün alan, düz yüzey"],
      ["θ yüzeyle ölçülen açı alınırsa (cos yerine sin gerekir)", "Program: 'kavramsal olarak açıklar' (FİZ.11.2.10)"],
      ["Açıyı yüzeyle ölçmek", "Akının vektör olduğunu sanmak"],
      ["manyetik-aki", "manyetik-alan"]),
    F("faraday-law", "İndüksiyon gerilimi (Faraday Yasası)", "ε = −N·ΔΦ / Δt", "epsilon eşittir eksi N delta fi bölü delta t",
      "Bobinden geçen akı değiştiğinde oluşan gerilim; eksi işaret Lenz Yasası'nı gösterir.", ["FİZ.11.2.11"], 262,
      [V("ε", "indüksiyon gerilimi", "V", "V"), V("N", "sarım sayısı", "—", "N"), V("ΔΦ", "akı değişimi", "Wb", "phiB"), V("Δt", "süre", "s", "dt")],
      [[{"V": 1}], [{"N": 1, "phiB": 1, "dt": -1}]],
      ["Akı değişimi Δt süresince düzgün (ortalama gerilim)"],
      ["Akı sabitse (alan büyük olsa bile ε = 0)"],
      ["Akı büyüklüğünü akı değişimiyle karıştırmak", "N'yi unutmak", "Eksi işaretini büyüklük hesabında taşıyıp yönü yanlış yorumlamak"],
      ["faraday-induksiyon-yasasi", "induksiyon-gerilimi", "manyetik-aki", "lenz-yasasi"]),
    F("ohm-law", "Ohm Yasası (indüksiyon akımında)", "ε = i·R", "epsilon eşittir i çarpı R",
      "İndüksiyon geriliminin direnç R'li devrede oluşturduğu akım.", ["FİZ.11.2.11"], 248,
      [V("ε", "gerilim", "V", "V"), V("i", "akım", "A", "i"), V("R", "direnç", "Ω", "R")],
      [[{"V": 1}], [{"i": 1, "R": 1}]],
      ["Omik direnç"],
      ["Devre açıksa (akım yok, gerilim var)"],
      ["Gerilim varsa her zaman akım olduğunu sanmak"],
      ["induksiyon-akimi", "direnc", "potansiyel-fark"], notes="10. sınıf ön koşulu (FİZ.10.3.3)."),
    F("ac-rms", "Alternatif akımda maksimum ve etkin değer", "V_max = V_etkin·√2 ;  i_max = i_etkin·√2",
      "V max eşittir V etkin çarpı kök iki", "Sinüzoidal alternatif akımda tepe değer ile etkin değer ilişkisi.", ["FİZ.11.2.12"], 259,
      [V("V_max", "maksimum gerilim", "V", "V"), V("V_etkin", "etkin gerilim", "V", "V")],
      [[{"V": 1}], [{"V": 1}]],
      ["Sinüzoidal dalga"],
      ["Kare/üçgen dalgada", "Program metninde etkin değer adı geçmiyor; ders kitabında var"],
      ["Voltmetrenin maksimum değeri ölçtüğünü sanmak (etkin değeri ölçer)", "√2 ile çarpmak yerine bölmek"],
      ["etkin-deger", "alternatif-akim"]),
    F("electric-power", "Elektriksel güç ve iletim kaybı", "P = V·i ;  P_kayıp = i²·R", "P eşittir V i; kayıp eşittir i kare R",
      "Üretilen güç ve iletim hattında ısıya dönüşen güç.", ["FİZ.11.2.13"], 263,
      [V("P", "güç", "W", "P"), V("V", "gerilim", "V", "V"), V("i", "akım", "A", "i"), V("R", "hat direnci", "Ω", "R")],
      [[{"P": 1}], [{"V": 1, "i": 1}, {"i": 2, "R": 1}]],
      ["P = V·i: toplam güç; i²R: direnç üzerindeki ısı kaybı"],
      ["P_kayıp = V²/R'de V olarak hattın iki ucu arası değil şebeke gerilimi konursa"],
      ["Gerilim artınca kaybın arttığını sanmak (aynı güçte akım azalır, kayıp azalır)"],
      ["iletimde-enerji-kaybi", "transformator", "direnc"]),
    F("ideal-transformer", "İdeal transformatör", "V_p / V_s = N_p / N_s = i_s / i_p", "V p bölü V s eşittir N p bölü N s eşittir i s bölü i p",
      "İdeal transformatörde gerilim sarım sayısıyla doğru, akım sarım sayısıyla ters orantılı.", ["FİZ.11.2.13"], 273,
      [V("V_p, V_s", "birincil/ikincil gerilim", "V", "V"), V("N_p, N_s", "sarım sayıları", "—", "N"), V("i_p, i_s", "birincil/ikincil akım", "A", "i")],
      [[{"V": 1, "V#": -1}], [{"N": 1}]],
      ["İdeal (kayıpsız) transformatör: giriş gücü = çıkış gücü", "Alternatif akım"],
      ["PROGRAM: FİZ.11.2.13 'Matematiksel işlemlerden kaçınılır'; yalnız nitel ilişki", "Doğru akımla (çıkış gerilimi sıfır)", "İdeal olmayan transformatörde akım oranında"],
      ["Akım oranını sarım oranıyla doğru orantılı yazmak", "Transformatörün enerji ürettiğini sanmak", "DC'de çalıştığını sanmak"],
      ["transformator", "birincil-ikincil-sarim", "sarim-sayisi"],
      notes="KAYNAK ÇELİŞKİSİ (Tier 1 – Tier 1): Program 'Matematiksel işlemlerden kaçınılır' derken kitap bu bağıntıyı ve sayısal alıştırma (47a, s. 272) veriyor."),
    F("transformer-efficiency", "Transformatörün verimi", "verim = (V_s·i_s) / (V_p·i_p)", "verim eşittir V s i s bölü V p i p",
      "Çıkış gücünün giriş gücüne oranı.", ["FİZ.11.2.13"], 273,
      [V("verim", "verim", "—", "eta"), V("V·i", "güçler", "W", "P")],
      [[{"eta": 1}], [{"V": 1, "i": 1, "P": -1}]],
      ["İdeal olmayan transformatör"],
      ["PROGRAM: FİZ.11.2.13 hesaplamasız"],
      ["Verimin 1'den büyük olabileceğini sanmak"],
      ["transformator"]),

    # ===================== ÜNİTE 3 =====================
    F("illuminance-definition", "Aydınlanma", "E = Φ / A", "E eşittir fi bölü A",
      "Yüzeye dik düşen ışık akısının birim alana düşen miktarı.", ["FİZ.11.3.1"], 311,
      [V("E", "aydınlanma", "lx", "Ev"), V("Φ", "ışık akısı", "lm", "phiV"), V("A", "yüzey alanı", "m²", "A")],
      [[{"Ev": 1}], [{"phiV": 1, "A": -1}]],
      ["Akı yüzeye dik ve düzgün dağılmış"],
      ["Işınlar yüzeye eğik geliyorsa (dik bileşen gerekir)"],
      ["Işık akısı ile ışık şiddetini karıştırmak"],
      ["aydinlanma", "isik-akisi"]),
    F("total-luminous-flux", "Kapalı yüzeyde toplam ışık akısı", "Φ = 4·π·I", "fi eşittir dört pi I",
      "Noktasal kaynağın her yöne yaydığı toplam ışık akısı; yüzeyin şekline ve uzaklığa bağlı değildir.", ["FİZ.11.3.1"], 311,
      [V("Φ", "toplam ışık akısı", "lm", "phiV"), V("I", "ışık şiddeti", "cd", "Iv")],
      [[{"phiV": 1}], [{"Iv": 1}]],
      ["Noktasal, her yöne eşit ışık veren kaynak", "Kaynağı tamamen saran kapalı yüzey"],
      ["Kaynak yönlüyse (el feneri)", "Yüzey kaynağı tamamen sarmıyorsa"],
      ["Kürenin yarıçapı büyüyünce toplam akının azaldığını sanmak"],
      ["isik-akisi", "isik-siddeti"]),
    F("illuminance-point-source", "Noktasal kaynağın aydınlanması", "E = I / r²", "E eşittir I bölü r kare",
      "Noktasal kaynaktan r uzaklıktaki yüzeye dik gelen ışınların oluşturduğu aydınlanma.", ["FİZ.11.3.1"], 311,
      [V("E", "aydınlanma", "lx", "Ev"), V("I", "ışık şiddeti", "cd", "Iv"), V("r", "uzaklık", "m", "r")],
      [[{"Ev": 1}], [{"Iv": 1, "r": -2}]],
      ["Noktasal kaynak", "Işınlar yüzeye dik"],
      ["Paralel ışık veren kaynakta (el feneri: uzaklıkla değişmez)", "Eğik gelişte (cos çarpanı gerekir; kitapta yok)"],
      ["Uzaklıkla doğrusal azaldığını sanmak", "Paralel ışında da ters kare uygulamak"],
      ["aydinlanma", "isik-siddeti", "ters-kare-iliskisi"]),
    F("refractive-index", "Kırma indisi", "n = c / ϑ", "n eşittir c bölü hız",
      "Işığın boşluktaki süratinin ortamdaki süratine oranı.", ["FİZ.11.3.5"], 352,
      [V("n", "kırma indisi", "—", "n"), V("c", "ışığın boşluktaki sürati", "m/s", "c"), V("ϑ", "ışığın ortamdaki sürati", "m/s", "v")],
      [[{"n": 1}], [{"c": 1, "v": -1}]],
      ["Saydam ortam"],
      ["n < 1 sonucu çıkarsa (sıradan ortamlarda olmaz)"],
      ["Kırma indisi büyük ortamda ışığın daha hızlı gittiğini sanmak"],
      ["kirma-indisi"]),
    F("snell-law", "Snell Yasası", "n₁·sin î = n₂·sin r̂", "n bir sinüs i eşittir n iki sinüs r",
      "Kırılmada gelme ve kırılma açıları ile ortamların kırma indisleri arasındaki ilişki; açılar normalle ölçülür.", ["FİZ.11.3.5", "FİZ.11.3.8"], 352,
      [V("n₁, n₂", "kırma indisleri", "—", "n"), V("î, r̂", "gelme ve kırılma açıları (normalle)", "°", "ang")],
      [[{"n": 1, "ang": 1}], [{"n": 1, "ang": 1}]],
      ["Açılar yüzey normaliyle ölçülür", "Tek renkli ışık"],
      ["Açılar yüzeyle ölçülmüşse", "Gelme açısı sınır açısından büyükse (kırılma yok, tam yansıma)"],
      ["Açıyı yüzeyle ölçmek", "Az kırıcıdan çok kırıcıya geçişte ışının normalden uzaklaştığını sanmak (yaklaşır)"],
      ["snell-yasasi", "kirma-indisi", "trigonometrik-oranlar"]),
    F("critical-angle", "Sınır açısı", "sin θ_s = n₂ / n₁   (n₁ > n₂)", "sinüs teta s eşittir n iki bölü n bir",
      "Çok kırıcıdan az kırıcıya geçişte kırılma açısını 90° yapan gelme açısı.", ["FİZ.11.3.5", "FİZ.11.3.7"], None,
      [V("θ_s", "sınır açısı", "°", "ang"), V("n₁", "ışığın geldiği (çok kırıcı) ortam", "—", "n"), V("n₂", "az kırıcı ortam", "—", "n")],
      [[{"ang": 1}], [{"n": 1, "n#": -1}]],
      ["n₁ > n₂ (ışık çok kırıcıdan az kırıcıya gidiyor)"],
      ["Işık az kırıcıdan çok kırıcıya gidiyorsa (sınır açısı ve tam yansıma yok)"],
      ["Tam yansımanın her geçişte olabileceğini sanmak"],
      ["sinir-acisi", "tam-yansima", "snell-yasasi"], level="derived",
      notes="Kitap sınır açısını tanımla veriyor (s. 353) ve camdan havaya 42° değerini kullanıyor (s. 372); formül kutusu doğrulanmadı. Snell'den r̂ = 90° konarak türetilir."),
    F("mirror-radius-focal", "Küresel aynada eğrilik yarıçapı ve odak uzaklığı", "r = 2·f", "r eşittir iki f",
      "Merkez ile tepe noktası arası, odak uzaklığının iki katıdır.", ["FİZ.11.3.3"], 341,
      [V("r", "eğrilik yarıçapı", "m", "r"), V("f", "odak uzaklığı", "m", "r")],
      [[{"r": 1}], [{"r": 1}]],
      ["Küçük açılı (asal eksene yakın) ışınlar"],
      ["Asal eksenden uzak ışınlarda (küresel sapınç)"],
      ["Odağı merkez noktasıyla karıştırmak"],
      ["odak-uzakligi", "egrilik-merkezi", "kuresel-ayna"]),
    F("plane-mirror-image", "Düzlem aynada görüntü konumu ve boyu", "d_görüntü = d_cisim ;  h_görüntü = h_cisim",
      "görüntünün aynaya uzaklığı cismin aynaya uzaklığına eşit",
      "Düzlem aynada görüntü aynaya göre cismin simetriğidir, cisimle eşit boyda, düz ve sanaldır.", ["FİZ.11.3.2"], 322,
      [V("d", "aynaya dik uzaklık", "m", "d"), V("h", "boy", "m", "h")],
      [[{"d": 1}], [{"d": 1}]],
      ["Düzlem ayna"],
      ["Küresel aynalarda"],
      ["Görüntünün aynanın yüzeyinde oluştuğunu sanmak", "Aynaya yaklaşınca görüntünün büyüdüğünü sanmak"],
      ["duzlem-ayna", "goruntu"]),

    # ===== Kapsam dışı (kitapta YOK) — yapay zekâ beklenen yöntem olarak öğretmemeli =====
    F("mirror-lens-equation", "Ayna / mercek denklemi (KAPSAM DIŞI)", "1/f = 1/d_c + 1/d_g", "bir bölü f eşittir bir bölü d c artı bir bölü d g",
      "Küresel ayna ve ince mercekte cisim, görüntü uzaklığı ve odak uzaklığı ilişkisi.", ["FİZ.11.3.4", "FİZ.11.3.10"], None,
      [V("f", "odak uzaklığı", "m", "r"), V("d_c", "cisim uzaklığı", "m", "r"), V("d_g", "görüntü uzaklığı", "m", "r")],
      [[{"r": -1}], [{"r": -1}, {"r": -1}]],
      ["Asal eksene yakın ışınlar, ince mercek", "İşaret kuralı tutarlı"],
      ["11. sınıf Maarif programı ve ders kitabında YOK: görüntü konumu özel ışın çizimi ve konum tablosuyla bulunur",
       "Yapay zekâ bunu öğrenciye beklenen yöntem olarak sunmamalı; yalnız sonucu kendi içinde doğrulamak için kullanabilir"],
      ["İşaret kuralını karıştırmak"],
      ["kuresel-aynada-goruntu", "mercekte-goruntu", "odak-uzakligi"], level="out_of_curriculum", verified=False,
      notes="Ders kitabının 416 sayfasında 'ayna denklemi' / 'mercek denklemi' ifadesi ve bu bağıntı bulunmadı."),
    F("plane-mirror-image-count", "Açılı düzlem aynalarda görüntü sayısı (KAPSAM DIŞI)", "n = 360°/α − 1",
      "n eşittir üç yüz altmış bölü alfa eksi bir", "Aralarında α açısı olan iki düzlem aynada oluşan görüntü sayısı.", ["FİZ.11.3.2"], None,
      [V("n", "görüntü sayısı", "—", "n"), V("α", "aynalar arası açı", "°", "ang")],
      [[{"n": 1}], [{"ang": 1}, {"one": 1}]],
      ["360/α tam sayı ve cisim açıortay üzerinde"],
      ["11. sınıf Maarif ders kitabında YOK", "360/α tam sayı değilse ya da cisim simetrik konumda değilse formül doğrudan geçersiz"],
      ["360/α tam sayı değilken formülü kullanmak"],
      ["duzlem-ayna", "goruntu"], level="out_of_curriculum", verified=False,
      notes="Eski programa göre yazılmış piyasa kaynaklarında sık görülür; ders kitabında 'görüntü sayısı' ifadesi geçmiyor."),
]
